// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxwpn

// DeviceRoot is the Device root of ADMX_WPN.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_WPN"

// DeviceNoToastNotification is ./Device/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification
const DeviceNoToastNotification = "./Device/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification"

// UserRoot is the User root of ADMX_WPN.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN"

// UserQuietHoursDailyBeginMinute is ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyBeginMinute.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyBeginMinute
const UserQuietHoursDailyBeginMinute = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyBeginMinute"

// UserQuietHoursDailyEndMinute is ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyEndMinute.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyEndMinute
const UserQuietHoursDailyEndMinute = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/QuietHoursDailyEndMinute"

// UserNoCallsDuringQuietHours is ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoCallsDuringQuietHours.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoCallsDuringQuietHours
const UserNoCallsDuringQuietHours = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoCallsDuringQuietHours"

// UserNoQuietHours is ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoQuietHours.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoQuietHours
const UserNoQuietHours = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoQuietHours"

// UserNoToastNotification is ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification
const UserNoToastNotification = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoToastNotification"

// UserNoLockScreenToastNotification is ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoLockScreenToastNotification.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoLockScreenToastNotification
const UserNoLockScreenToastNotification = "./User/Vendor/MSFT/Policy/Config/ADMX_WPN/NoLockScreenToastNotification"
