// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxsharedfolders

// Root is the User root of ADMX_SharedFolders.
const Root = "./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders"

// PublishDfsRoots is ./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders/PublishDfsRoots.
// ./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders/PublishDfsRoots
const PublishDfsRoots = "./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders/PublishDfsRoots"

// PublishSharedFolders is ./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders/PublishSharedFolders.
// ./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders/PublishSharedFolders
const PublishSharedFolders = "./User/Vendor/MSFT/Policy/Config/ADMX_SharedFolders/PublishSharedFolders"
