// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package defender

// ConfigurationEnableFileHashComputation values (ENUM).
const (
	// Disable
	ConfigurationEnableFileHashComputationDisable = "0"
	// Enable
	ConfigurationEnableFileHashComputationEnable = "1"
)

// ConfigurationMeteredConnectionUpdates values (ENUM).
const (
	// Allowed
	ConfigurationMeteredConnectionUpdatesAllowed = "1"
	// Not Allowed
	ConfigurationMeteredConnectionUpdatesNotAllowed = "0"
)

// ConfigurationAllowNetworkProtectionOnWinServer values (ENUM).
const (
	// Allow
	ConfigurationAllowNetworkProtectionOnWinServerAllow = "1"
	// Disallow
	ConfigurationAllowNetworkProtectionOnWinServerDisallow = "0"
)

// ConfigurationDisableCpuThrottleOnIdleScans values (ENUM).
const (
	// Disable CPU Throttle on idle scans
	ConfigurationDisableCpuThrottleOnIdleScansDisableCPUThrottleOn = "1"
	// Enable CPU Throttle on idle scans
	ConfigurationDisableCpuThrottleOnIdleScansEnableCPUThrottleOn = "0"
)

// ConfigurationDisableLocalAdminMerge values (ENUM).
const (
	// Yes
	ConfigurationDisableLocalAdminMergeYes = "1"
	// No
	ConfigurationDisableLocalAdminMergeNo = "0"
)

// ConfigurationDisableTlsParsing values (ENUM).
const (
	// TLS parsing is disabled
	ConfigurationDisableTlsParsingTLSParsingIsDisabled = "1"
	// TLS parsing is enabled
	ConfigurationDisableTlsParsingTLSParsingIsEnabled = "0"
)

// ConfigurationDisableFtpParsing values (ENUM).
const (
	// FTP parsing is disabled
	ConfigurationDisableFtpParsingFTPParsingIsDisabled = "1"
	// FTP parsing is enabled
	ConfigurationDisableFtpParsingFTPParsingIsEnabled = "0"
)

// ConfigurationDisableHttpParsing values (ENUM).
const (
	// HTTP parsing is disabled
	ConfigurationDisableHttpParsingHTTPParsingIsDisabled = "1"
	// HTTP parsing is enabled
	ConfigurationDisableHttpParsingHTTPParsingIsEnabled = "0"
)

// ConfigurationDisableDnsParsing values (ENUM).
const (
	// DNS parsing is disabled
	ConfigurationDisableDnsParsingDNSParsingIsDisabled = "1"
	// DNS parsing is enabled
	ConfigurationDisableDnsParsingDNSParsingIsEnabled = "0"
)

// ConfigurationDisableDnsOverTcpParsing values (ENUM).
const (
	// DNS over TCP parsing is disabled
	ConfigurationDisableDnsOverTcpParsingDNSOverTCPParsing = "1"
	// DNS over TCP parsing is enabled
	ConfigurationDisableDnsOverTcpParsingDNSOverTCPParsing2 = "0"
)

// ConfigurationDisableSshParsing values (ENUM).
const (
	// SSH parsing is disabled
	ConfigurationDisableSshParsingSSHParsingIsDisabled = "1"
	// SSH parsing is enabled
	ConfigurationDisableSshParsingSSHParsingIsEnabled = "0"
)

// ConfigurationPlatformUpdatesChannel values (ENUM).
const (
	// Not configured (Default). The device will stay up to date automatically during the gradual release cycle. Suitable for most devices.
	ConfigurationPlatformUpdatesChannelNotConfiguredDefaultThe = "0"
	// Beta Channel: Devices set to this channel will be the first to receive new updates. Select Beta Channel to participate in identifying and reporting issues to Microsoft. Devices in the Windows Insider Program are subscribed to this channel by default. For use in (manual) test environments only and a limited number of devices.
	ConfigurationPlatformUpdatesChannelBetaChannelDevicesSet = "2"
	// Current Channel (Preview): Devices set to this channel will be offered updates earliest during the monthly gradual release cycle. Suggested for pre-production/validation environments.
	ConfigurationPlatformUpdatesChannelCurrentChannelPreviewDevices = "3"
	// Current Channel (Staged): Devices will be offered updates after the monthly gradual release cycle. Suggested to apply to a small, representative part of your production population (~10%).
	ConfigurationPlatformUpdatesChannelCurrentChannelStagedDevices = "4"
	// Current Channel (Broad): Devices will be offered updates only after the gradual release cycle completes. Suggested to apply to a broad set of devices in your production population (~10-100%).
	ConfigurationPlatformUpdatesChannelCurrentChannelBroadDevices = "5"
	// Critical - Time delay: Devices will be offered updates with a 48-hour delay. Suggested for critical environments only.
	ConfigurationPlatformUpdatesChannelCriticalTimeDelayDevices = "6"
)

// ConfigurationEngineUpdatesChannel values (ENUM).
const (
	// Not configured (Default). The device will stay up to date automatically during the gradual release cycle. Suitable for most devices.
	ConfigurationEngineUpdatesChannelNotConfiguredDefaultThe = "0"
	// Beta Channel: Devices set to this channel will be the first to receive new updates. Select Beta Channel to participate in identifying and reporting issues to Microsoft. Devices in the Windows Insider Program are subscribed to this channel by default. For use in (manual) test environments only and a limited number of devices.
	ConfigurationEngineUpdatesChannelBetaChannelDevicesSet = "2"
	// Current Channel (Preview): Devices set to this channel will be offered updates earliest during the monthly gradual release cycle. Suggested for pre-production/validation environments.
	ConfigurationEngineUpdatesChannelCurrentChannelPreviewDevices = "3"
	// Current Channel (Staged): Devices will be offered updates after the monthly gradual release cycle. Suggested to apply to a small, representative part of your production population (~10%).
	ConfigurationEngineUpdatesChannelCurrentChannelStagedDevices = "4"
	// Current Channel (Broad): Devices will be offered updates only after the gradual release cycle completes. Suggested to apply to a broad set of devices in your production population (~10-100%).
	ConfigurationEngineUpdatesChannelCurrentChannelBroadDevices = "5"
	// Critical - Time delay: Devices will be offered updates with a 48-hour delay. Suggested for critical environments only.
	ConfigurationEngineUpdatesChannelCriticalTimeDelayDevices = "6"
)

// ConfigurationSecurityIntelligenceUpdatesChannel values (ENUM).
const (
	// Not configured (Default). Microsoft will either assign the device to Current Channel (Broad) or a beta channel early in the gradual release cycle. The channel selected by Microsoft might be one that receives updates early during the gradual release cycle, which may not be suitable for devices in a production or critical environment
	ConfigurationSecurityIntelligenceUpdatesChannelNotConfiguredDefaultMicrosoft = "0"
	// Current Channel (Staged): Same as Current Channel (Broad).
	ConfigurationSecurityIntelligenceUpdatesChannelCurrentChannelStagedSame = "4"
	// Current Channel (Broad): Devices will be offered updates only after the gradual release cycle completes. Suggested to apply to a broad set of devices in all populations, including production.
	ConfigurationSecurityIntelligenceUpdatesChannelCurrentChannelBroadDevices = "5"
)

// ConfigurationDisableGradualRelease values (ENUM).
const (
	// Gradual release is disabled
	ConfigurationDisableGradualReleaseGradualReleaseIsDisabled = "1"
	// Gradual release is enabled
	ConfigurationDisableGradualReleaseGradualReleaseIsEnabled = "0"
)

// ConfigurationAllowNetworkProtectionDownLevel values (ENUM).
const (
	// Network protection will be enabled downlevel.
	ConfigurationAllowNetworkProtectionDownLevelNetworkProtectionWillBe = "1"
	// Network protection will be disabled downlevel.
	ConfigurationAllowNetworkProtectionDownLevelNetworkProtectionWillBe2 = "0"
)

// ConfigurationEnableDnsSinkhole values (ENUM).
const (
	// DNS Sinkhole is disabled
	ConfigurationEnableDnsSinkholeDNSSinkholeIsDisabled = "0"
	// DNS Sinkhole is enabled
	ConfigurationEnableDnsSinkholeDNSSinkholeIsEnabled = "1"
)

// ConfigurationDisableInboundConnectionFiltering values (ENUM).
const (
	// Inbound connection filtering is disabled
	ConfigurationDisableInboundConnectionFilteringInboundConnectionFilteringIs = "1"
	// Inbound connection filtering is enabled
	ConfigurationDisableInboundConnectionFilteringInboundConnectionFilteringIs2 = "0"
)

// ConfigurationDisableRdpParsing values (ENUM).
const (
	// RDP Parsing is disabled
	ConfigurationDisableRdpParsingRDPParsingIsDisabled = "1"
	// RDP Parsing is enabled
	ConfigurationDisableRdpParsingRDPParsingIsEnabled = "0"
)

// ConfigurationAllowDatagramProcessingOnWinServer values (ENUM).
const (
	// Datagram processing on Windows Server is enabled.
	ConfigurationAllowDatagramProcessingOnWinServerDatagramProcessingOnWindows = "1"
	// Datagram processing on Windows Server is disabled.
	ConfigurationAllowDatagramProcessingOnWinServerDatagramProcessingOnWindows2 = "0"
)

// ConfigurationDisableDatagramProcessing values (ENUM).
const (
	// UDP inspection is off
	ConfigurationDisableDatagramProcessingUDPInspectionIsOff = "1"
	// UDP inspection is on
	ConfigurationDisableDatagramProcessingUDPInspectionIsOn = "0"
)

// ConfigurationEnableConvertWarnToBlock values (ENUM).
const (
	// Warn verdicts are converted to block
	ConfigurationEnableConvertWarnToBlockWarnVerdictsAreConverted = "1"
	// Warn verdicts are not converted to block
	ConfigurationEnableConvertWarnToBlockWarnVerdictsAreNot = "0"
)

// ConfigurationDisableNetworkProtectionPerfTelemetry values (ENUM).
const (
	// Network protection telemetry is disabled
	ConfigurationDisableNetworkProtectionPerfTelemetryNetworkProtectionTelemetryIs = "1"
	// Network protection telemetry is enabled
	ConfigurationDisableNetworkProtectionPerfTelemetryNetworkProtectionTelemetryIs2 = "0"
)

// ConfigurationHideExclusionsFromLocalAdmins values (ENUM).
const (
	// If you enable this setting, local admins will no longer be able to see the exclusion list in Windows Security App or via PowerShell.
	ConfigurationHideExclusionsFromLocalAdminsIfYouEnableThis = "1"
	// If you disable or do not configure this setting, local admins will be able to see exclusions in the Windows Security App and via PowerShell.
	ConfigurationHideExclusionsFromLocalAdminsIfYouDisableOr = "0"
)

// ConfigurationHideExclusionsFromLocalUsers values (ENUM).
const (
	// If you enable this setting, local users will no longer be able to see the exclusion list in Windows Security App or via PowerShell.
	ConfigurationHideExclusionsFromLocalUsersIfYouEnableThis = "1"
	// If you disable or do not configure this setting, local users will be able to see exclusions in the Windows Security App and via PowerShell.
	ConfigurationHideExclusionsFromLocalUsersIfYouDisableOr = "0"
)

// ConfigurationOobeEnableRtpAndSigUpdate values (ENUM).
const (
	// If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
	ConfigurationOobeEnableRtpAndSigUpdateIfYouEnableThis = "1"
	// If you either disable or do not configure this setting, real-time protection and Security Intelligence Updates during OOBE is not enabled.
	ConfigurationOobeEnableRtpAndSigUpdateIfYouEitherDisable = "0"
)

// ConfigurationPerformanceModeStatus values (ENUM).
const (
	// Performance mode is enabled (default).
	ConfigurationPerformanceModeStatusPerformanceModeIsEnabled = "0"
	// Performance mode is disabled.
	ConfigurationPerformanceModeStatusPerformanceModeIsDisabled = "1"
)

// ConfigurationQuickScanIncludeExclusions values (ENUM).
const (
	// If you set this setting to 0 or do not configure it, exclusions are not scanned during quick scans.
	ConfigurationQuickScanIncludeExclusionsIfYouSetThis = "0"
	// If you set this setting to 1, all files and directories that are excluded from real-time protection using contextual exclusions are scanned during a quick scan.
	ConfigurationQuickScanIncludeExclusionsIfYouSetThis2 = "1"
)

// ConfigurationSecurityIntelligenceLocationUpdateAtScheduledTimeOnly values (ENUM).
const (
	// If you enable this setting and configure SecurityIntelligenceLocation, updates from the configured location occur only at the previously configured scheduled update time.
	ConfigurationSecurityIntelligenceLocationUpdateAtScheduledTimeOnlyIfYouEnableThis = "1"
	// If you either disable or do not configure this setting, updates occur whenever a new security intelligence update is detected at the location that is specified by SecurityIntelligenceLocation.
	ConfigurationSecurityIntelligenceLocationUpdateAtScheduledTimeOnlyIfYouEitherDisable = "0"
)

// ConfigurationScheduleSecurityIntelligenceUpdateDay values (ENUM).
const (
	// Daily
	ConfigurationScheduleSecurityIntelligenceUpdateDayDaily = "0"
	// Sunday
	ConfigurationScheduleSecurityIntelligenceUpdateDaySunday = "1"
	// Monday
	ConfigurationScheduleSecurityIntelligenceUpdateDayMonday = "2"
	// Tuesday
	ConfigurationScheduleSecurityIntelligenceUpdateDayTuesday = "3"
	// Wednesday
	ConfigurationScheduleSecurityIntelligenceUpdateDayWednesday = "4"
	// Thursday
	ConfigurationScheduleSecurityIntelligenceUpdateDayThursday = "5"
	// Friday
	ConfigurationScheduleSecurityIntelligenceUpdateDayFriday = "6"
	// Saturday
	ConfigurationScheduleSecurityIntelligenceUpdateDaySaturday = "7"
	// Never
	ConfigurationScheduleSecurityIntelligenceUpdateDayNever = "8"
)

// ConfigurationThrottleForScheduledScanOnly values (ENUM).
const (
	// If you enable this setting, CPU throttling will apply only to scheduled scans.
	ConfigurationThrottleForScheduledScanOnlyIfYouEnableThis = "1"
	// If you disable this setting, CPU throttling will apply to scheduled and custom scans.
	ConfigurationThrottleForScheduledScanOnlyIfYouDisableThis = "0"
)

// ConfigurationSecuredDevicesConfiguration values (ENUM).
const (
	// RemovableMediaDevices
	ConfigurationSecuredDevicesConfigurationRemovableMediaDevices = "RemovableMediaDevices"
	// CdRomDevices
	ConfigurationSecuredDevicesConfigurationCdRomDevices = "CdRomDevices"
	// WpdDevices
	ConfigurationSecuredDevicesConfigurationWpdDevices = "WpdDevices"
	// PrinterDevices
	ConfigurationSecuredDevicesConfigurationPrinterDevices = "PrinterDevices"
)

// ConfigurationDeviceControlEnabled values (ENUM).
const (
	// Device Control is enabled
	ConfigurationDeviceControlEnabledDeviceControlIsEnabled = "1"
	// Device Control is disabled
	ConfigurationDeviceControlEnabledDeviceControlIsDisabled = "0"
)

// ConfigurationDefaultEnforcement values (ENUM).
const (
	// Default Allow Enforcement
	ConfigurationDefaultEnforcementDefaultAllowEnforcement = "1"
	// Default Deny Enforcement
	ConfigurationDefaultEnforcementDefaultDenyEnforcement = "2"
)

// ConfigurationPassiveRemediation values (Flag).
const (
	// Passive Remediation is turned off (default)
	ConfigurationPassiveRemediationPassiveRemediationIsTurned = "0x0"
	// PASSIVE_REMEDIATION_FLAG_SENSE_AUTO_REMEDIATION: Passive Remediation Sense AutoRemediation
	ConfigurationPassiveRemediationPASSIVEREMEDIATIONFLAGSENSE = "0x1"
	// PASSIVE_REMEDIATION_FLAG_RTP_AUDIT: Passive Remediation Realtime Protection Audit
	ConfigurationPassiveRemediationPASSIVEREMEDIATIONFLAGRTP = "0x2"
	// PASSIVE_REMEDIATION_FLAG_RTP_REMEDIATION: Passive Remediation Realtime Protection Remediation
	ConfigurationPassiveRemediationPASSIVEREMEDIATIONFLAGRTP2 = "0x4"
)

// ConfigurationDisableCoreServiceECSIntegration values (Flag).
const (
	// The Defender core service will use the Experimentation and Configuration Service (ECS) to rapidly deliver critical, org-specific fixes.
	ConfigurationDisableCoreServiceECSIntegrationTheDefenderCoreService = "0x0"
	// The Defender core service stops using the Experimentation and Configuration Service (ECS). Fixes will continue to be delivered through security intelligence updates.
	ConfigurationDisableCoreServiceECSIntegrationTheDefenderCoreService2 = "0x1"
)

// ConfigurationDisableCoreServiceTelemetry values (Flag).
const (
	// The Defender core service will use the OneDsCollector framework to rapidly collect telemetry.
	ConfigurationDisableCoreServiceTelemetryTheDefenderCoreService = "0x0"
	// The Defender core service stops using the OneDsCollector framework to rapidly collect telemetry, impacting Microsoft's ability to quickly recognize and address poor performance, false positives, and other problems.
	ConfigurationDisableCoreServiceTelemetryTheDefenderCoreService2 = "0x1"
)

// ConfigurationIntelTDTEnabled values (ENUM).
const (
	// If you do not configure this setting, the default value will be applied. The default value is controlled by Microsoft security intelligence updates. Microsoft will enable Intel TDT if there is a known threat.
	ConfigurationIntelTDTEnabledIfYouDoNot = "0"
	// If you configure this setting to enabled, Intel TDT integration will turn on.
	ConfigurationIntelTDTEnabledIfYouConfigureThis = "1"
	// If you configure this setting to disabled, Intel TDT integration will turn off.
	ConfigurationIntelTDTEnabledIfYouConfigureThis2 = "2"
)

// ConfigurationDisableSmtpParsing values (ENUM).
const (
	// SMTP parsing is disabled
	ConfigurationDisableSmtpParsingSMTPParsingIsDisabled = "1"
	// SMTP parsing is enabled
	ConfigurationDisableSmtpParsingSMTPParsingIsEnabled = "0"
)

// ConfigurationDisableQuicParsing values (ENUM).
const (
	// QUIC parsing is disabled
	ConfigurationDisableQuicParsingQUICParsingIsDisabled = "1"
	// QUIC parsing is enabled
	ConfigurationDisableQuicParsingQUICParsingIsEnabled = "0"
)

// ConfigurationNetworkProtectionReputationMode values (ENUM).
const (
	// Use standard reputation engine
	ConfigurationNetworkProtectionReputationModeUseStandardReputationEngine = "0"
	// Use ESP reputation engine
	ConfigurationNetworkProtectionReputationModeUseESPReputationEngine = "1"
)

// ConfigurationEnableUdpSegmentationOffload values (ENUM).
const (
	// Udp Segmentation Offload is disabled
	ConfigurationEnableUdpSegmentationOffloadUdpSegmentationOffloadIs = "0"
	// Udp Segmentation Offload is enabled
	ConfigurationEnableUdpSegmentationOffloadUdpSegmentationOffloadIs2 = "1"
)

// ConfigurationEnableUdpReceiveOffload values (ENUM).
const (
	// Udp Receive Offload is disabled
	ConfigurationEnableUdpReceiveOffloadUdpReceiveOffloadIs = "0"
	// Udp Receive Offload is enabled
	ConfigurationEnableUdpReceiveOffloadUdpReceiveOffloadIs2 = "1"
)

// ConfigurationAllowSwitchToAsyncInspection values (ENUM).
const (
	// Allow switching to asynchronous inspection
	ConfigurationAllowSwitchToAsyncInspectionAllowSwitchingToAsynchronous = "1"
	// Don’t allow asynchronous inspection
	ConfigurationAllowSwitchToAsyncInspectionDonTAllowAsynchronous = "0"
)

// ConfigurationRandomizeScheduleTaskTimes values (ENUM).
const (
	// Widen or narrow the randomization period for scheduled scans. Specify a randomization window of between 1 and 23 hours by using the setting SchedulerRandomizationTime.
	ConfigurationRandomizeScheduleTaskTimesWidenOrNarrowThe = "1"
	// Scheduled tasks will not be randomized.
	ConfigurationRandomizeScheduleTaskTimesScheduledTasksWillNot = "0"
)

// ConfigurationScanOnlyIfIdleEnabled values (ENUM).
const (
	// Runs scheduled scans only if the system is idle.
	ConfigurationScanOnlyIfIdleEnabledRunsScheduledScansOnly = "1"
	// Runs scheduled scans regardless of whether the system is idle.
	ConfigurationScanOnlyIfIdleEnabledRunsScheduledScansRegardless = "0"
)

// ConfigurationDisableCacheMaintenance values (ENUM).
const (
	// Cache maintenance is disabled
	ConfigurationDisableCacheMaintenanceCacheMaintenanceIsDisabled = "1"
	// Cache maintenance is enabled (default)
	ConfigurationDisableCacheMaintenanceCacheMaintenanceIsEnabled = "0"
)

// ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionConfiguredState values (ENUM).
const (
	// Not configured: Apply defaults set for the antivirus engine and platform
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionConfiguredStateNotConfiguredApplyDefaults = "0"
	// Block: Prevent suspicious and malicious behaviors
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionConfiguredStateBlockPreventSuspiciousAnd = "1"
	// Audit: Generate EDR detections without blocking
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionConfiguredStateAuditGenerateEDRDetections = "2"
	// Off: Feature is off with no performance impact
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionConfiguredStateOffFeatureIsOff = "4"
)

// ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionAggressiveness values (ENUM).
const (
	// Low: Block only when confidence level is 100% (Default)
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionAggressivenessLowBlockOnlyWhen = "0"
	// Medium: Use cloud aggregation and block when confidence level is above 99%
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionAggressivenessMediumUseCloudAggregation = "1"
	// High: Use cloud intel and context, and block when confidence level is above 90%
	ConfigurationBehavioralNetworkBlocksRemoteEncryptionProtectionRemoteEncryptionProtectionAggressivenessHighUseCloudIntel = "2"
)

// ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionConfiguredState values (ENUM).
const (
	// Not configured: Apply defaults set by the antivirus engine and platform
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionConfiguredStateNotConfiguredApplyDefaults = "0"
	// Block: Prevent suspicious and malicious behaviors
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionConfiguredStateBlockPreventSuspiciousAnd = "1"
	// Audit: Generate EDR detections without blocking
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionConfiguredStateAuditGenerateEDRDetections = "2"
	// Off: Feature is disabled with no performance impact
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionConfiguredStateOffFeatureIsDisabled = "4"
)

// ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionAggressiveness values (ENUM).
const (
	// Low: Only IP addresses that are 100% confidence malicious (default)
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionAggressivenessLowOnlyIPAddresses = "0"
	// Medium: Use cloud aggregation to block IP addresses that are over 99% likely malicious
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionAggressivenessMediumUseCloudAggregation = "1"
	// High: Block IP addresses identified using client intelligence and context to block IP addresses that are over 90% likely malicious
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionAggressivenessHighBlockIPAddresses = "2"
)

// ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionPluginsBruteForceProtectionLocalNetworkBlocking values (ENUM).
const (
	// Brute-force protection will not block local network addresses
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionPluginsBruteForceProtectionLocalNetworkBlockingBruteForceProtectionWill = "0"
	// Brute-force protection will block local network addresses
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionPluginsBruteForceProtectionLocalNetworkBlockingBruteForceProtectionWill2 = "1"
)

// ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionPluginsBruteForceProtectionSkipLearningPeriod values (ENUM).
const (
	// Brute-force protection blocks threats only after completing a 2-week learning period
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionPluginsBruteForceProtectionSkipLearningPeriodBruteForceProtectionBlocks = "0"
	// Brute-force protection starts blocking threats immediately
	ConfigurationBehavioralNetworkBlocksBruteForceProtectionBruteForceProtectionPluginsBruteForceProtectionSkipLearningPeriodBruteForceProtectionStarts = "1"
)

// ConfigurationReportingEnableDynamicSignatureDroppedEventReporting values (ENUM).
const (
	// Dynamic Security intelligence update dropped events will not be reported.
	ConfigurationReportingEnableDynamicSignatureDroppedEventReportingDynamicSecurityIntelligenceUpdate = "0"
	// Dynamic Security intelligence update events will be reported.
	ConfigurationReportingEnableDynamicSignatureDroppedEventReportingDynamicSecurityIntelligenceUpdate2 = "1"
)

// Scan values (ENUM).
const (
	// quick scan
	ScanQuickScan = "1"
	// full scan
	ScanFullScan = "2"
)
