// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package kerberos

// PKInitHashAlgorithmConfiguration values (ENUM).
const (
	// Disabled / Not Configured
	PKInitHashAlgorithmConfigurationDisabledNotConfigured = "0"
	// Enabled
	PKInitHashAlgorithmConfigurationEnabled = "1"
)

// PKInitHashAlgorithmSHA1 values (ENUM).
const (
	// Not Supported
	PKInitHashAlgorithmSHA1NotSupported = "0"
	// Default
	PKInitHashAlgorithmSHA1Default = "1"
	// Audited
	PKInitHashAlgorithmSHA1Audited = "2"
	// Supported
	PKInitHashAlgorithmSHA1Supported = "3"
)

// PKInitHashAlgorithmSHA256 values (ENUM).
const (
	// Not Supported
	PKInitHashAlgorithmSHA256NotSupported = "0"
	// Default
	PKInitHashAlgorithmSHA256Default = "1"
	// Audited
	PKInitHashAlgorithmSHA256Audited = "2"
	// Supported
	PKInitHashAlgorithmSHA256Supported = "3"
)

// PKInitHashAlgorithmSHA384 values (ENUM).
const (
	// Not Supported
	PKInitHashAlgorithmSHA384NotSupported = "0"
	// Default
	PKInitHashAlgorithmSHA384Default = "1"
	// Audited
	PKInitHashAlgorithmSHA384Audited = "2"
	// Supported
	PKInitHashAlgorithmSHA384Supported = "3"
)

// PKInitHashAlgorithmSHA512 values (ENUM).
const (
	// Not Supported
	PKInitHashAlgorithmSHA512NotSupported = "0"
	// Default
	PKInitHashAlgorithmSHA512Default = "1"
	// Audited
	PKInitHashAlgorithmSHA512Audited = "2"
	// Supported
	PKInitHashAlgorithmSHA512Supported = "3"
)

// CloudKerberosTicketRetrievalEnabled values (ENUM).
const (
	// Disabled.
	CloudKerberosTicketRetrievalEnabledDisabled = "0"
	// Enabled.
	CloudKerberosTicketRetrievalEnabledEnabled = "1"
)
