// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package devicepreparation

// Root is the Device root of DevicePreparation.
const Root = "./Device/Vendor/MSFT/DevicePreparation"

// PageEnabled is ./Device/Vendor/MSFT/DevicePreparation/PageEnabled.
// This node determines whether to show the Device Preparation page during OOBE.
const PageEnabled = "./Device/Vendor/MSFT/DevicePreparation/PageEnabled"

// PageStatus is ./Device/Vendor/MSFT/DevicePreparation/PageStatus.
// This node provides status of the Device Preparation page.
const PageStatus = "./Device/Vendor/MSFT/DevicePreparation/PageStatus"

// PageErrorPhase is ./Device/Vendor/MSFT/DevicePreparation/PageErrorPhase.
// This node provides the specific phase that failed during the Device Preparation page.
const PageErrorPhase = "./Device/Vendor/MSFT/DevicePreparation/PageErrorPhase"

// PageErrorCode is ./Device/Vendor/MSFT/DevicePreparation/PageErrorCode.
// This node provides specific overall HRESULT causing a fatal error on the Device Preparation page.
const PageErrorCode = "./Device/Vendor/MSFT/DevicePreparation/PageErrorCode"

// PageErrorDetails is ./Device/Vendor/MSFT/DevicePreparation/PageErrorDetails.
// This node provides optional details for any fatal error on the Device Preparation page.
const PageErrorDetails = "./Device/Vendor/MSFT/DevicePreparation/PageErrorDetails"

// PageSettings is ./Device/Vendor/MSFT/DevicePreparation/PageSettings.
// This node configures the Device Preparation page settings.
const PageSettings = "./Device/Vendor/MSFT/DevicePreparation/PageSettings"

// BootstrapperAgent is ./Device/Vendor/MSFT/DevicePreparation/BootstrapperAgent.
// Parent node for configuring agent that orchestrage provioning and communicate status to Device Preparation page.
const BootstrapperAgent = "./Device/Vendor/MSFT/DevicePreparation/BootstrapperAgent"

// BootstrapperAgentExecutionContext is ./Device/Vendor/MSFT/DevicePreparation/BootstrapperAgent/ExecutionContext.
// This node holds opaque data that will be passed to the Bootstrapper Agent as a parameter when it is invoked to execute.
const BootstrapperAgentExecutionContext = "./Device/Vendor/MSFT/DevicePreparation/BootstrapperAgent/ExecutionContext"

// MDMProvider is ./Device/Vendor/MSFT/DevicePreparation/MDMProvider.
// Parent node for configuring the MDM provider that interacts with the BootstrapperAgent.
const MDMProvider = "./Device/Vendor/MSFT/DevicePreparation/MDMProvider"

// MDMProviderProgress is ./Device/Vendor/MSFT/DevicePreparation/MDMProvider/Progress.
// Node for reporting progress status as opaque data.
const MDMProviderProgress = "./Device/Vendor/MSFT/DevicePreparation/MDMProvider/Progress"

// MDMProviderMdmAgentInstalled is ./Device/Vendor/MSFT/DevicePreparation/MDMProvider/MdmAgentInstalled.
// This node indicates whether the mdm agent was installed or not.
const MDMProviderMdmAgentInstalled = "./Device/Vendor/MSFT/DevicePreparation/MDMProvider/MdmAgentInstalled"

// MDMProviderRebootRequired is ./Device/Vendor/MSFT/DevicePreparation/MDMProvider/RebootRequired.
// This node indicates whether an MDM policy was provisioned that requires a reboot.
const MDMProviderRebootRequired = "./Device/Vendor/MSFT/DevicePreparation/MDMProvider/RebootRequired"

// IsPostOobeProvisioningAllowed is ./Device/Vendor/MSFT/DevicePreparation/IsPostOobeProvisioningAllowed.
// This node determines whether Autopilot Device Preparation provisioning can be executed after OOBE has completed.
const IsPostOobeProvisioningAllowed = "./Device/Vendor/MSFT/DevicePreparation/IsPostOobeProvisioningAllowed"
