// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package bits

// Root is the Device root of BITS.
const Root = "./Device/Vendor/MSFT/Policy/Config/BITS"

// JobInactivityTimeout is ./Device/Vendor/MSFT/Policy/Config/BITS/JobInactivityTimeout.
// This policy setting specifies the number of days a pending BITS job can remain inactive before the job is considered abandoned.
const JobInactivityTimeout = "./Device/Vendor/MSFT/Policy/Config/BITS/JobInactivityTimeout"

// BandwidthThrottlingStartTime is ./Device/Vendor/MSFT/Policy/Config/BITS/BandwidthThrottlingStartTime.
// This policy specifies the bandwidth throttling start time that Background Intelligent Transfer Service (BITS) uses for background transfers.
const BandwidthThrottlingStartTime = "./Device/Vendor/MSFT/Policy/Config/BITS/BandwidthThrottlingStartTime"

// BandwidthThrottlingEndTime is ./Device/Vendor/MSFT/Policy/Config/BITS/BandwidthThrottlingEndTime.
// This policy specifies the bandwidth throttling end time that Background Intelligent Transfer Service (BITS) uses for background transfers.
const BandwidthThrottlingEndTime = "./Device/Vendor/MSFT/Policy/Config/BITS/BandwidthThrottlingEndTime"

// BandwidthThrottlingTransferRate is ./Device/Vendor/MSFT/Policy/Config/BITS/BandwidthThrottlingTransferRate.
// This policy specifies the bandwidth throttling transfer rate in kilobits per second (Kbps) that Background Intelligent Transfer Service (BITS) uses for background transfers.
const BandwidthThrottlingTransferRate = "./Device/Vendor/MSFT/Policy/Config/BITS/BandwidthThrottlingTransferRate"

// CostedNetworkBehaviorForegroundPriority is ./Device/Vendor/MSFT/Policy/Config/BITS/CostedNetworkBehaviorForegroundPriority.
// This policy setting defines the default behavior that the foreground Intelligent Transfer Service (BITS) uses for foreground transfers when the system is connected to a costed network (3G, etc.
const CostedNetworkBehaviorForegroundPriority = "./Device/Vendor/MSFT/Policy/Config/BITS/CostedNetworkBehaviorForegroundPriority"

// CostedNetworkBehaviorBackgroundPriority is ./Device/Vendor/MSFT/Policy/Config/BITS/CostedNetworkBehaviorBackgroundPriority.
// This policy setting defines the default behavior that the Background Intelligent Transfer Service (BITS) uses for background transfers when the system is connected to a costed network (3G, etc.
const CostedNetworkBehaviorBackgroundPriority = "./Device/Vendor/MSFT/Policy/Config/BITS/CostedNetworkBehaviorBackgroundPriority"
