// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package eventlogservice

// Root is the Device root of EventLogService.
const Root = "./Device/Vendor/MSFT/Policy/Config/EventLogService"

// ControlEventLogBehavior is ./Device/Vendor/MSFT/Policy/Config/EventLogService/ControlEventLogBehavior.
// ./Device/Vendor/MSFT/Policy/Config/EventLogService/ControlEventLogBehavior
const ControlEventLogBehavior = "./Device/Vendor/MSFT/Policy/Config/EventLogService/ControlEventLogBehavior"

// SpecifyMaximumFileSizeApplicationLog is ./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeApplicationLog.
// ./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeApplicationLog
const SpecifyMaximumFileSizeApplicationLog = "./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeApplicationLog"

// SpecifyMaximumFileSizeSecurityLog is ./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeSecurityLog.
// ./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeSecurityLog
const SpecifyMaximumFileSizeSecurityLog = "./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeSecurityLog"

// SpecifyMaximumFileSizeSystemLog is ./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeSystemLog.
// ./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeSystemLog
const SpecifyMaximumFileSizeSystemLog = "./Device/Vendor/MSFT/Policy/Config/EventLogService/SpecifyMaximumFileSizeSystemLog"
