// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package controlpolicyconflict

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/ControlPolicyConflict.
var Tree = csp.Inherit(&csp.Tree{Name: "ControlPolicyConflict", File: "ControlPolicyConflict_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "ControlPolicyConflict", URI: "./Device/Vendor/MSFT/Policy/Config/ControlPolicyConflict", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "MDMWinsOverGP", URI: "./Device/Vendor/MSFT/Policy/Config/ControlPolicyConflict/MDMWinsOverGP", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "If set to 1 then any MDM policy that is set that has an equivalent GP policy will result in GP service blocking the setting of the policy by GP MMC. Setting the value to 0 (zero) or deleting the policy will remove the GP policy blocks restore the saved GP policies.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.17134"}, CspVersion: "7.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: ""}, {Value: "1", Description: "The MDM policy is used and the GP policy is blocked."}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of ControlPolicyConflict in this package.
var Trees = []*csp.Tree{Tree}
