// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxpreviousversions

// DeviceRoot is the Device root of ADMX_PreviousVersions.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions"

// DeviceDisableLocalPage2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalPage_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalPage_2
const DeviceDisableLocalPage2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalPage_2"

// DeviceDisableRemotePage2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemotePage_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemotePage_2
const DeviceDisableRemotePage2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemotePage_2"

// DeviceHideBackupEntries2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/HideBackupEntries_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/HideBackupEntries_2
const DeviceHideBackupEntries2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/HideBackupEntries_2"

// DeviceDisableLocalRestore2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalRestore_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalRestore_2
const DeviceDisableLocalRestore2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalRestore_2"

// DeviceDisableBackupRestore2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableBackupRestore_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableBackupRestore_2
const DeviceDisableBackupRestore2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableBackupRestore_2"

// DeviceDisableRemoteRestore2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemoteRestore_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemoteRestore_2
const DeviceDisableRemoteRestore2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemoteRestore_2"

// UserRoot is the User root of ADMX_PreviousVersions.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions"

// UserDisableLocalPage1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalPage_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalPage_1
const UserDisableLocalPage1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalPage_1"

// UserDisableRemotePage1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemotePage_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemotePage_1
const UserDisableRemotePage1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemotePage_1"

// UserHideBackupEntries1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/HideBackupEntries_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/HideBackupEntries_1
const UserHideBackupEntries1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/HideBackupEntries_1"

// UserDisableLocalRestore1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalRestore_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalRestore_1
const UserDisableLocalRestore1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableLocalRestore_1"

// UserDisableBackupRestore1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableBackupRestore_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableBackupRestore_1
const UserDisableBackupRestore1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableBackupRestore_1"

// UserDisableRemoteRestore1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemoteRestore_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemoteRestore_1
const UserDisableRemoteRestore1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PreviousVersions/DisableRemoteRestore_1"
