// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package credentialproviders

// Root is the Device root of CredentialProviders.
const Root = "./Device/Vendor/MSFT/Policy/Config/CredentialProviders"

// BlockPicturePassword is ./Device/Vendor/MSFT/Policy/Config/CredentialProviders/BlockPicturePassword.
// ./Device/Vendor/MSFT/Policy/Config/CredentialProviders/BlockPicturePassword
const BlockPicturePassword = "./Device/Vendor/MSFT/Policy/Config/CredentialProviders/BlockPicturePassword"

// AllowPINLogon is ./Device/Vendor/MSFT/Policy/Config/CredentialProviders/AllowPINLogon.
// ./Device/Vendor/MSFT/Policy/Config/CredentialProviders/AllowPINLogon
const AllowPINLogon = "./Device/Vendor/MSFT/Policy/Config/CredentialProviders/AllowPINLogon"

// DisableAutomaticReDeploymentCredentials is ./Device/Vendor/MSFT/Policy/Config/CredentialProviders/DisableAutomaticReDeploymentCredentials.
// Boolean policy to disable the visibility of the credential provider that triggers the PC refresh on a device.
const DisableAutomaticReDeploymentCredentials = "./Device/Vendor/MSFT/Policy/Config/CredentialProviders/DisableAutomaticReDeploymentCredentials"
