// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package remoteassistance

// Root is the Device root of RemoteAssistance.
const Root = "./Device/Vendor/MSFT/Policy/Config/RemoteAssistance"

// UnsolicitedRemoteAssistance is ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance.
// ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance
const UnsolicitedRemoteAssistance = "./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/UnsolicitedRemoteAssistance"

// SolicitedRemoteAssistance is ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance.
// ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance
const SolicitedRemoteAssistance = "./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SolicitedRemoteAssistance"

// CustomizeWarningMessages is ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages.
// ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages
const CustomizeWarningMessages = "./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/CustomizeWarningMessages"

// SessionLogging is ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging.
// ./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging
const SessionLogging = "./Device/Vendor/MSFT/Policy/Config/RemoteAssistance/SessionLogging"
