// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package humanpresence

// Root is the Device root of HumanPresence.
const Root = "./Device/Vendor/MSFT/Policy/Config/HumanPresence"

// ForceInstantWake is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceInstantWake.
// Determines whether Wake on Arrival is forced on/off by the MDM policy.
const ForceInstantWake = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceInstantWake"

// ForceInstantLock is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceInstantLock.
// Determines whether Lock on Leave is forced on/off by the MDM policy.
const ForceInstantLock = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceInstantLock"

// ForceLockTimeout is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceLockTimeout.
// Determines the timeout for Lock on Leave forced by the MDM policy.
const ForceLockTimeout = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceLockTimeout"

// ForceInstantDim is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceInstantDim.
// Determines whether Attention Based Display Dimming is forced on/off by the MDM policy.
const ForceInstantDim = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceInstantDim"

// ForceDisableWakeWhenBatterySaverOn is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceDisableWakeWhenBatterySaverOn.
// Determines whether Disable Wake on Approach When Battery Saver On checkbox is forced checked/unchecked by the MDM policy.
const ForceDisableWakeWhenBatterySaverOn = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceDisableWakeWhenBatterySaverOn"

// ForceAllowWakeWhenExternalDisplayConnected is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceAllowWakeWhenExternalDisplayConnected.
// Determines whether Allow Wake on Approach When External Display Connected checkbox is forced checked/unchecked by the MDM policy.
const ForceAllowWakeWhenExternalDisplayConnected = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceAllowWakeWhenExternalDisplayConnected"

// ForceAllowLockWhenExternalDisplayConnected is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceAllowLockWhenExternalDisplayConnected.
// Determines whether Allow Lock on Leave When External Display Connected checkbox is forced checked/unchecked by the MDM policy.
const ForceAllowLockWhenExternalDisplayConnected = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceAllowLockWhenExternalDisplayConnected"

// ForceAllowDimWhenExternalDisplayConnected is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceAllowDimWhenExternalDisplayConnected.
// Determines whether Allow Adaptive Dimming When External Display Connected checkbox is forced checked/unchecked by the MDM policy.
const ForceAllowDimWhenExternalDisplayConnected = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceAllowDimWhenExternalDisplayConnected"

// ForceOnlookerDetection is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceOnlookerDetection.
// Determines whether detect when other people are looking at my screen is forced on/off by the MDM policy.
const ForceOnlookerDetection = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceOnlookerDetection"

// ForceOnlookerDetectionAction is ./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceOnlookerDetectionAction.
// Determines whether the Onlooker Detection action is forced by the MDM policy.
const ForceOnlookerDetectionAction = "./Device/Vendor/MSFT/Policy/Config/HumanPresence/ForceOnlookerDetectionAction"
