// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package authentication

// DeviceRoot is the Device root of Authentication.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/Authentication"

// DeviceAllowFastReconnect is ./Device/Vendor/MSFT/Policy/Config/Authentication/AllowFastReconnect.
// Allows EAP Fast Reconnect from being attempted for EAP Method TLS.
const DeviceAllowFastReconnect = "./Device/Vendor/MSFT/Policy/Config/Authentication/AllowFastReconnect"

// DeviceAllowSecondaryAuthenticationDevice is ./Device/Vendor/MSFT/Policy/Config/Authentication/AllowSecondaryAuthenticationDevice.
// Allows secondary authentication devices to work with Windows.
const DeviceAllowSecondaryAuthenticationDevice = "./Device/Vendor/MSFT/Policy/Config/Authentication/AllowSecondaryAuthenticationDevice"

// DeviceAllowAadPasswordReset is ./Device/Vendor/MSFT/Policy/Config/Authentication/AllowAadPasswordReset.
// Specifies whether password reset is enabled for AAD accounts.
const DeviceAllowAadPasswordReset = "./Device/Vendor/MSFT/Policy/Config/Authentication/AllowAadPasswordReset"

// DevicePreferredAadTenantDomainName is ./Device/Vendor/MSFT/Policy/Config/Authentication/PreferredAadTenantDomainName.
// Specifies the preferred domain among available domains in the AAD tenant.
const DevicePreferredAadTenantDomainName = "./Device/Vendor/MSFT/Policy/Config/Authentication/PreferredAadTenantDomainName"

// DeviceEnableWebSignIn is ./Device/Vendor/MSFT/Policy/Config/Authentication/EnableWebSignIn.
// Specifies whether web-based sign-in is allowed for signing in to Windows
const DeviceEnableWebSignIn = "./Device/Vendor/MSFT/Policy/Config/Authentication/EnableWebSignIn"

// DeviceEnableFastFirstSignIn is ./Device/Vendor/MSFT/Policy/Config/Authentication/EnableFastFirstSignIn.
// Specifies whether new non-admin AAD accounts should auto-connect to pre-created candidate local accounts
const DeviceEnableFastFirstSignIn = "./Device/Vendor/MSFT/Policy/Config/Authentication/EnableFastFirstSignIn"

// DeviceConfigureWebcamAccessDomainNames is ./Device/Vendor/MSFT/Policy/Config/Authentication/ConfigureWebcamAccessDomainNames.
// Specifies a list of domains that are allowed to access the webcam in Web Sign-in based authentication scenarios.
const DeviceConfigureWebcamAccessDomainNames = "./Device/Vendor/MSFT/Policy/Config/Authentication/ConfigureWebcamAccessDomainNames"

// DeviceConfigureWebSignInAllowedUrls is ./Device/Vendor/MSFT/Policy/Config/Authentication/ConfigureWebSignInAllowedUrls.
// Specifies a list of URLs that are navigable in Web Sign-in based authentication scenarios.
const DeviceConfigureWebSignInAllowedUrls = "./Device/Vendor/MSFT/Policy/Config/Authentication/ConfigureWebSignInAllowedUrls"

// DeviceEnablePasswordlessExperience is ./Device/Vendor/MSFT/Policy/Config/Authentication/EnablePasswordlessExperience.
// Specifies whether connected users on AADJ devices receive a Passwordless experience on Windows
const DeviceEnablePasswordlessExperience = "./Device/Vendor/MSFT/Policy/Config/Authentication/EnablePasswordlessExperience"

// UserRoot is the User root of Authentication.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/Authentication"

// UserAllowEAPCertSSO is ./User/Vendor/MSFT/Policy/Config/Authentication/AllowEAPCertSSO.
// Allows an EAP cert-based authentication for a single sign on (SSO) to access internal resources.
const UserAllowEAPCertSSO = "./User/Vendor/MSFT/Policy/Config/Authentication/AllowEAPCertSSO"
