// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package bluetooth

// Root is the Device root of Bluetooth.
const Root = "./Device/Vendor/MSFT/Policy/Config/Bluetooth"

// AllowAdvertising is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowAdvertising.
// Specifies whether the device can send out Bluetooth advertisements.
const AllowAdvertising = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowAdvertising"

// AllowDiscoverableMode is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowDiscoverableMode.
// Specifies whether other Bluetooth-enabled devices can discover the device.
const AllowDiscoverableMode = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowDiscoverableMode"

// AllowPrepairing is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowPrepairing.
// Specifies whether to allow specific bundled Bluetooth peripherals to automatically pair with the host device.
const AllowPrepairing = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowPrepairing"

// AllowPromptedProximalConnections is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowPromptedProximalConnections.
// This policy allows the IT admin to block users on these managed devices from using Swift Pair and other proximity based scenarios.
const AllowPromptedProximalConnections = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/AllowPromptedProximalConnections"

// LocalDeviceName is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/LocalDeviceName.
// Sets the local Bluetooth device name.
const LocalDeviceName = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/LocalDeviceName"

// ServicesAllowedList is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/ServicesAllowedList.
// Set a list of allowable services and profiles.
const ServicesAllowedList = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/ServicesAllowedList"

// SetMinimumEncryptionKeySize is ./Device/Vendor/MSFT/Policy/Config/Bluetooth/SetMinimumEncryptionKeySize.
// There are multiple levels of encryption strength when pairing Bluetooth devices.
const SetMinimumEncryptionKeySize = "./Device/Vendor/MSFT/Policy/Config/Bluetooth/SetMinimumEncryptionKeySize"
