// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxwdi

// Root is the Device root of ADMX_WDI.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_WDI"

// WdiDpsScenarioExecutionPolicy is ./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioExecutionPolicy.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioExecutionPolicy
const WdiDpsScenarioExecutionPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioExecutionPolicy"

// WdiDpsScenarioDataSizeLimitPolicy is ./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioDataSizeLimitPolicy.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioDataSizeLimitPolicy
const WdiDpsScenarioDataSizeLimitPolicy = "./Device/Vendor/MSFT/Policy/Config/ADMX_WDI/WdiDpsScenarioDataSizeLimitPolicy"
