// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package messaging

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/Messaging.
var Tree = csp.Inherit(&csp.Tree{Name: "Messaging", File: "Messaging_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "Messaging", URI: "./Device/Vendor/MSFT/Policy/Config/Messaging", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AllowMessageSync", URI: "./Device/Vendor/MSFT/Policy/Config/Messaging/AllowMessageSync", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy setting allows backup and restore of cellular text messages to Microsoft's cloud services.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.14393"}, CspVersion: "4.1", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "message sync is not allowed and cannot be changed by the user."}, {Value: "1", Description: "message sync is allowed. The user can change this setting."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "AllowMessageSync", AreaPath: "messaging~AT~WindowsComponents~Messaging_Category", Element: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
		&csp.Node{
			Name: "AllowMMS", URI: "./Device/Vendor/MSFT/Policy/Config/Messaging/AllowMMS", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy setting allows you to enable or disable the sending and receiving cellular MMS messages.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: nil, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "1", Description: "Allow"}, {Value: "0", Description: "Block"}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
		&csp.Node{
			Name: "AllowRCS", URI: "./Device/Vendor/MSFT/Policy/Config/Messaging/AllowRCS", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy setting allows you to enable or disable the sending and receiving of cellular RCS (Rich Communication Services) messages.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: nil, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "1", Description: "Allow"}, {Value: "0", Description: "Block"}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
	},
}})

// Trees lists every root of Messaging in this package.
var Trees = []*csp.Tree{Tree}
