// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package windowsautopilot

// Root is the Device root of WindowsAutopilot.
const Root = "./Device/Vendor/MSFT/Policy/Config/WindowsAutopilot"

// EnableAgilityPostEnrollment is ./Device/Vendor/MSFT/Policy/Config/WindowsAutopilot/EnableAgilityPostEnrollment.
// Specifies whether to check for Windows Autopilot updates after enrollment.
const EnableAgilityPostEnrollment = "./Device/Vendor/MSFT/Policy/Config/WindowsAutopilot/EnableAgilityPostEnrollment"
