// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxdwm

// DeviceRoot is the Device root of ADMX_DWM.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_DWM"

// DeviceDwmDisallowAnimations2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2
const DeviceDwmDisallowAnimations2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_2"

// DeviceDwmDisallowColorizationColorChanges2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2
const DeviceDwmDisallowColorizationColorChanges2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_2"

// DeviceDwmDefaultColorizationColor2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2
const DeviceDwmDefaultColorizationColor2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_2"

// UserRoot is the User root of ADMX_DWM.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM"

// UserDwmDisallowAnimations1 is ./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_1
const UserDwmDisallowAnimations1 = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowAnimations_1"

// UserDwmDisallowColorizationColorChanges1 is ./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_1
const UserDwmDisallowColorizationColorChanges1 = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDisallowColorizationColorChanges_1"

// UserDwmDefaultColorizationColor1 is ./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_1
const UserDwmDefaultColorizationColor1 = "./User/Vendor/MSFT/Policy/Config/ADMX_DWM/DwmDefaultColorizationColor_1"
