// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package sudo

// EnableSudo values (ENUM).
const (
	// Sudo is disabled.
	EnableSudoSudoIsDisabled = "0"
	// Sudo is allowed in 'force new window' mode.
	EnableSudoSudoIsAllowedIn = "1"
	// Sudo is allowed in 'disable input' mode.
	EnableSudoSudoIsAllowedIn2 = "2"
	// Sudo is allowed in 'inline' mode.
	EnableSudoSudoIsAllowedIn3 = "3"
)
