// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package federatedauthentication

// EnableWebSignInForPrimaryUser values (ENUM).
const (
	// Feature defaults as appropriate for edition and device capabilities. As of now, all editions/devices exhibit Disabled behavior by default. However, this may change for future editions/devices.
	EnableWebSignInForPrimaryUserFeatureDefaultsAsAppropriate = "0"
	// Enabled. Web Sign-in Credential Provider will be enabled for device sign-in.
	EnableWebSignInForPrimaryUserEnabledWebSignIn = "1"
	// Disabled. Web Sign-in Credential Provider will be not be enabled for device sign-in.
	EnableWebSignInForPrimaryUserDisabledWebSignIn = "2"
)
