// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package localpoliciessecurityoptions

// AccountsEnableAdministratorAccountStatus values (ENUM).
const (
	// Enable
	AccountsEnableAdministratorAccountStatusEnable = "1"
	// Disable
	AccountsEnableAdministratorAccountStatusDisable = "0"
)

// AccountsBlockMicrosoftAccounts values (ENUM).
const (
	// Disabled (users will be able to use Microsoft accounts with Windows).
	AccountsBlockMicrosoftAccountsDisabledUsersWillBe = "0"
	// Enabled (users can't add Microsoft accounts).
	AccountsBlockMicrosoftAccountsEnabledUsersCanT = "1"
	// Users can't add or log on with Microsoft accounts
	AccountsBlockMicrosoftAccountsUsersCanTAdd = "3"
)

// AccountsEnableGuestAccountStatus values (ENUM).
const (
	// Enable
	AccountsEnableGuestAccountStatusEnable = "1"
	// Disable
	AccountsEnableGuestAccountStatusDisable = "0"
)

// AccountsLimitLocalAccountUseOfBlankPasswordsToConsoleLogonOnly values (ENUM).
const (
	// Disabled
	AccountsLimitLocalAccountUseOfBlankPasswordsToConsoleLogonOnlyDisabled = "0"
	// Enabled
	AccountsLimitLocalAccountUseOfBlankPasswordsToConsoleLogonOnlyEnabled = "1"
)

// AuditAuditTheUseOfBackupAndRestoreprivilege values (ENUM).
const (
	// Enable
	AuditAuditTheUseOfBackupAndRestoreprivilegeEnable = "AQ=="
	// Disable
	AuditAuditTheUseOfBackupAndRestoreprivilegeDisable = "AA=="
)

// DevicesAllowUndockWithoutHavingToLogon values (ENUM).
const (
	// Allow
	DevicesAllowUndockWithoutHavingToLogonAllow = "1"
	// Block
	DevicesAllowUndockWithoutHavingToLogonBlock = "0"
)

// DevicesPreventUsersFromInstallingPrinterDriversWhenConnectingToSharedPrinters values (ENUM).
const (
	// Enable
	DevicesPreventUsersFromInstallingPrinterDriversWhenConnectingToSharedPrintersEnable = "1"
	// Disable
	DevicesPreventUsersFromInstallingPrinterDriversWhenConnectingToSharedPrintersDisable = "0"
)

// InteractiveLogonDisplayUserInformationWhenTheSessionIsLocked values (ENUM).
const (
	// User display name, domain and user names
	InteractiveLogonDisplayUserInformationWhenTheSessionIsLockedUserDisplayNameDomain = "1"
	// User display name only
	InteractiveLogonDisplayUserInformationWhenTheSessionIsLockedUserDisplayNameOnly = "2"
	// Do not display user information
	InteractiveLogonDisplayUserInformationWhenTheSessionIsLockedDoNotDisplayUser = "3"
	// Domain and user names only
	InteractiveLogonDisplayUserInformationWhenTheSessionIsLockedDomainAndUserNames = "4"
)

// InteractiveLogonDoNotRequireCTRLALTDEL values (ENUM).
const (
	// Disabled
	InteractiveLogonDoNotRequireCTRLALTDELDisabled = "0"
	// Enabled (a user is not required to press CTRL+ALT+DEL to log on)
	InteractiveLogonDoNotRequireCTRLALTDELEnabledAUserIs = "1"
)

// InteractiveLogonDoNotDisplayLastSignedIn values (ENUM).
const (
	// Disabled (username will be shown)
	InteractiveLogonDoNotDisplayLastSignedInDisabledUsernameWillBe = "0"
	// Enabled (username will not be shown)
	InteractiveLogonDoNotDisplayLastSignedInEnabledUsernameWillNot = "1"
)

// InteractiveLogonDoNotDisplayUsernameAtSignIn values (ENUM).
const (
	// Disabled (username will be shown)
	InteractiveLogonDoNotDisplayUsernameAtSignInDisabledUsernameWillBe = "0"
	// Enabled (username will not be shown)
	InteractiveLogonDoNotDisplayUsernameAtSignInEnabledUsernameWillNot = "1"
)

// InteractiveLogonSmartCardRemovalBehavior values (ENUM).
const (
	// No Action
	InteractiveLogonSmartCardRemovalBehaviorNoAction = "0"
	// Lock Workstation
	InteractiveLogonSmartCardRemovalBehaviorLockWorkstation = "1"
	// Force Logoff
	InteractiveLogonSmartCardRemovalBehaviorForceLogoff = "2"
	// Disconnect if a Remote Desktop Services session
	InteractiveLogonSmartCardRemovalBehaviorDisconnectIfARemote = "3"
)

// MicrosoftNetworkClientDigitallySignCommunicationsAlways values (ENUM).
const (
	// Enable
	MicrosoftNetworkClientDigitallySignCommunicationsAlwaysEnable = "1"
	// Disable
	MicrosoftNetworkClientDigitallySignCommunicationsAlwaysDisable = "0"
)

// MicrosoftNetworkClientDigitallySignCommunicationsIfServerAgrees values (ENUM).
const (
	// Enable
	MicrosoftNetworkClientDigitallySignCommunicationsIfServerAgreesEnable = "1"
	// Disable
	MicrosoftNetworkClientDigitallySignCommunicationsIfServerAgreesDisable = "0"
)

// MicrosoftNetworkClientSendUnencryptedPasswordToThirdPartySMBServers values (ENUM).
const (
	// Enable
	MicrosoftNetworkClientSendUnencryptedPasswordToThirdPartySMBServersEnable = "1"
	// Disable
	MicrosoftNetworkClientSendUnencryptedPasswordToThirdPartySMBServersDisable = "0"
)

// MicrosoftNetworkServerDigitallySignCommunicationsAlways values (ENUM).
const (
	// Enable
	MicrosoftNetworkServerDigitallySignCommunicationsAlwaysEnable = "1"
	// Disable
	MicrosoftNetworkServerDigitallySignCommunicationsAlwaysDisable = "0"
)

// MicrosoftNetworkServerDigitallySignCommunicationsIfClientAgrees values (ENUM).
const (
	// Enable
	MicrosoftNetworkServerDigitallySignCommunicationsIfClientAgreesEnable = "1"
	// Disable
	MicrosoftNetworkServerDigitallySignCommunicationsIfClientAgreesDisable = "0"
)

// NetworkAccessAllowAnonymousSIDOrNameTranslation values (ENUM).
const (
	// Enable
	NetworkAccessAllowAnonymousSIDOrNameTranslationEnable = "1"
	// Disable
	NetworkAccessAllowAnonymousSIDOrNameTranslationDisable = "0"
)

// NetworkAccessDoNotAllowAnonymousEnumerationOfSAMAccounts values (ENUM).
const (
	// Enabled
	NetworkAccessDoNotAllowAnonymousEnumerationOfSAMAccountsEnabled = "1"
	// Disabled
	NetworkAccessDoNotAllowAnonymousEnumerationOfSAMAccountsDisabled = "0"
)

// NetworkAccessDoNotAllowAnonymousEnumerationOfSamAccountsAndShares values (ENUM).
const (
	// Enabled
	NetworkAccessDoNotAllowAnonymousEnumerationOfSamAccountsAndSharesEnabled = "1"
	// Disabled
	NetworkAccessDoNotAllowAnonymousEnumerationOfSamAccountsAndSharesDisabled = "0"
)

// NetworkAccessRestrictAnonymousAccessToNamedPipesAndShares values (ENUM).
const (
	// Enable
	NetworkAccessRestrictAnonymousAccessToNamedPipesAndSharesEnable = "1"
	// Disable
	NetworkAccessRestrictAnonymousAccessToNamedPipesAndSharesDisable = "0"
)

// NetworkSecurityAllowLocalSystemToUseComputerIdentityForNTLM values (ENUM).
const (
	// Allow
	NetworkSecurityAllowLocalSystemToUseComputerIdentityForNTLMAllow = "1"
	// Block
	NetworkSecurityAllowLocalSystemToUseComputerIdentityForNTLMBlock = "0"
)

// NetworkSecurityAllowPKU2UAuthenticationRequests values (ENUM).
const (
	// Block
	NetworkSecurityAllowPKU2UAuthenticationRequestsBlock = "0"
	// Allow
	NetworkSecurityAllowPKU2UAuthenticationRequestsAllow = "1"
)

// NetworkSecurityDoNotStoreLANManagerHashValueOnNextPasswordChange values (ENUM).
const (
	// Enable
	NetworkSecurityDoNotStoreLANManagerHashValueOnNextPasswordChangeEnable = "1"
	// Disable
	NetworkSecurityDoNotStoreLANManagerHashValueOnNextPasswordChangeDisable = "0"
)

// NetworkSecurityForceLogoffWhenLogonHoursExpire values (ENUM).
const (
	// Enable
	NetworkSecurityForceLogoffWhenLogonHoursExpireEnable = "1"
	// Disable
	NetworkSecurityForceLogoffWhenLogonHoursExpireDisable = "0"
)

// NetworkSecurityLANManagerAuthenticationLevel values (ENUM).
const (
	// Send LM and NTLM responses
	NetworkSecurityLANManagerAuthenticationLevelSendLMAndNTLM = "0"
	// Send LM and NTLM-use NTLMv2 session security if negotiated
	NetworkSecurityLANManagerAuthenticationLevelSendLMAndNTLM2 = "1"
	// Send LM and NTLM responses only
	NetworkSecurityLANManagerAuthenticationLevelSendLMAndNTLM3 = "2"
	// Send LM and NTLMv2 responses only
	NetworkSecurityLANManagerAuthenticationLevelSendLMAndNTLMv2 = "3"
	// Send LM and NTLMv2 responses only. Refuse LM
	NetworkSecurityLANManagerAuthenticationLevelSendLMAndNTLMv22 = "4"
	// Send LM and NTLMv2 responses only. Refuse LM and NTLM
	NetworkSecurityLANManagerAuthenticationLevelSendLMAndNTLMv23 = "5"
)

// NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedClients values (ENUM).
const (
	// None
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedClientsNone = "0"
	// Require NTLMv2 session security
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedClientsRequireNTLMv2SessionSecurity = "524288"
	// Require 128-bit encryption
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedClientsRequire128BitEncryption = "536870912"
	// Require NTLM and 128-bit encryption
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedClientsRequireNTLMAnd128 = "537395200"
)

// NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedServers values (ENUM).
const (
	// None
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedServersNone = "0"
	// Require NTLMv2 session security
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedServersRequireNTLMv2SessionSecurity = "524288"
	// Require 128-bit encryption
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedServersRequire128BitEncryption = "536870912"
	// Require NTLM and 128-bit encryption
	NetworkSecurityMinimumSessionSecurityForNTLMSSPBasedServersRequireNTLMAnd128 = "537395200"
)

// NetworkSecurityRestrictNTLMAuditIncomingNTLMTraffic values (ENUM).
const (
	// Disable
	NetworkSecurityRestrictNTLMAuditIncomingNTLMTrafficDisable = "0"
	// Enable auditing for domain accounts
	NetworkSecurityRestrictNTLMAuditIncomingNTLMTrafficEnableAuditingForDomain = "1"
	// Enable auditing for all accounts
	NetworkSecurityRestrictNTLMAuditIncomingNTLMTrafficEnableAuditingForAll = "2"
)

// NetworkSecurityRestrictNTLMIncomingNTLMTraffic values (ENUM).
const (
	// Allow all
	NetworkSecurityRestrictNTLMIncomingNTLMTrafficAllowAll = "0"
	// Deny all domain accounts
	NetworkSecurityRestrictNTLMIncomingNTLMTrafficDenyAllDomainAccounts = "1"
	// Deny all accounts
	NetworkSecurityRestrictNTLMIncomingNTLMTrafficDenyAllAccounts = "2"
)

// NetworkSecurityRestrictNTLMOutgoingNTLMTrafficToRemoteServers values (ENUM).
const (
	// Allow all
	NetworkSecurityRestrictNTLMOutgoingNTLMTrafficToRemoteServersAllowAll = "0"
	// Deny all domain accounts
	NetworkSecurityRestrictNTLMOutgoingNTLMTrafficToRemoteServersDenyAllDomainAccounts = "1"
	// Deny all accounts
	NetworkSecurityRestrictNTLMOutgoingNTLMTrafficToRemoteServersDenyAllAccounts = "2"
)

// ShutdownAllowSystemToBeShutDownWithoutHavingToLogOn values (ENUM).
const (
	// disabled
	ShutdownAllowSystemToBeShutDownWithoutHavingToLogOnDisabled = "0"
	// enabled (allow system to be shut down without having to log on)
	ShutdownAllowSystemToBeShutDownWithoutHavingToLogOnEnabledAllowSystemTo = "1"
)

// ShutdownClearVirtualMemoryPageFile values (ENUM).
const (
	// Enable
	ShutdownClearVirtualMemoryPageFileEnable = "1"
	// Disable
	ShutdownClearVirtualMemoryPageFileDisable = "0"
)

// UserAccountControlUseAdminApprovalMode values (ENUM).
const (
	// Enable
	UserAccountControlUseAdminApprovalModeEnable = "1"
	// Disable
	UserAccountControlUseAdminApprovalModeDisable = "0"
)

// UserAccountControlAllowUIAccessApplicationsToPromptForElevation values (ENUM).
const (
	// disabled
	UserAccountControlAllowUIAccessApplicationsToPromptForElevationDisabled = "0"
	// enabled (allow UIAccess applications to prompt for elevation without using the secure desktop)
	UserAccountControlAllowUIAccessApplicationsToPromptForElevationEnabledAllowUIAccessApplications = "1"
)

// UserAccountControlBehaviorOfTheElevationPromptForAdministrators values (ENUM).
const (
	// Elevate without prompting
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorsElevateWithoutPrompting = "0"
	// Prompt for credentials on the secure desktop
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorsPromptForCredentialsOn = "1"
	// Prompt for consent on the secure desktop
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorsPromptForConsentOn = "2"
	// Prompt for credentials
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorsPromptForCredentials = "3"
	// Prompt for consent
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorsPromptForConsent = "4"
	// Prompt for consent for non-Windows binaries
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorsPromptForConsentFor = "5"
)

// UserAccountControlBehaviorOfTheElevationPromptForAdministratorProtection values (ENUM).
const (
	// Prompt for credentials on the secure desktop
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorProtectionPromptForCredentialsOn = "1"
	// Prompt for consent on the secure desktop
	UserAccountControlBehaviorOfTheElevationPromptForAdministratorProtectionPromptForConsentOn = "2"
)

// UserAccountControlBehaviorOfTheElevationPromptForStandardUsers values (ENUM).
const (
	// Automatically deny elevation requests
	UserAccountControlBehaviorOfTheElevationPromptForStandardUsersAutomaticallyDenyElevationRequests = "0"
	// Prompt for credentials on the secure desktop
	UserAccountControlBehaviorOfTheElevationPromptForStandardUsersPromptForCredentialsOn = "1"
	// Prompt for credentials
	UserAccountControlBehaviorOfTheElevationPromptForStandardUsersPromptForCredentials = "3"
)

// UserAccountControlOnlyElevateExecutableFilesThatAreSignedAndValidated values (ENUM).
const (
	// Disabled: Does not enforce validation.
	UserAccountControlOnlyElevateExecutableFilesThatAreSignedAndValidatedDisabledDoesNotEnforce = "0"
	// Enabled: Enforces validation.
	UserAccountControlOnlyElevateExecutableFilesThatAreSignedAndValidatedEnabledEnforcesValidation = "1"
)

// UserAccountControlOnlyElevateUIAccessApplicationsThatAreInstalledInSecureLocations values (ENUM).
const (
	// Disabled: Application runs with UIAccess integrity even if it does not reside in a secure location.
	UserAccountControlOnlyElevateUIAccessApplicationsThatAreInstalledInSecureLocationsDisabledApplicationRunsWith = "0"
	// Enabled: Application runs with UIAccess integrity only if it resides in secure location.
	UserAccountControlOnlyElevateUIAccessApplicationsThatAreInstalledInSecureLocationsEnabledApplicationRunsWith = "1"
)

// UserAccountControlRunAllAdministratorsInAdminApprovalMode values (ENUM).
const (
	// Disabled
	UserAccountControlRunAllAdministratorsInAdminApprovalModeDisabled = "0"
	// Enabled
	UserAccountControlRunAllAdministratorsInAdminApprovalModeEnabled = "1"
)

// UserAccountControlTypeOfAdminApprovalMode values (ENUM).
const (
	// Legacy Admin Approval Mode
	UserAccountControlTypeOfAdminApprovalModeLegacyAdminApprovalMode = "1"
	// Admin Approval Mode with Administrator protection
	UserAccountControlTypeOfAdminApprovalModeAdminApprovalModeWith = "2"
)

// UserAccountControlSwitchToTheSecureDesktopWhenPromptingForElevation values (ENUM).
const (
	// Disabled
	UserAccountControlSwitchToTheSecureDesktopWhenPromptingForElevationDisabled = "0"
	// Enabled
	UserAccountControlSwitchToTheSecureDesktopWhenPromptingForElevationEnabled = "1"
)

// UserAccountControlVirtualizeFileAndRegistryWriteFailuresToPerUserLocations values (ENUM).
const (
	// Disabled
	UserAccountControlVirtualizeFileAndRegistryWriteFailuresToPerUserLocationsDisabled = "0"
	// Enabled
	UserAccountControlVirtualizeFileAndRegistryWriteFailuresToPerUserLocationsEnabled = "1"
)

// UserAccountControlDetectApplicationInstallationsAndPromptForElevation values (ENUM).
const (
	// Enable
	UserAccountControlDetectApplicationInstallationsAndPromptForElevationEnable = "1"
	// Disable
	UserAccountControlDetectApplicationInstallationsAndPromptForElevationDisable = "0"
)
