// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxctrlaltdel

// Root is the User root of ADMX_CtrlAltDel.
const Root = "./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel"

// DisableChangePassword is ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableChangePassword.
// ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableChangePassword
const DisableChangePassword = "./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableChangePassword"

// DisableLockComputer is ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableLockComputer.
// ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableLockComputer
const DisableLockComputer = "./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableLockComputer"

// NoLogoff is ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/NoLogoff.
// ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/NoLogoff
const NoLogoff = "./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/NoLogoff"

// DisableTaskMgr is ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableTaskMgr.
// ./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableTaskMgr
const DisableTaskMgr = "./User/Vendor/MSFT/Policy/Config/ADMX_CtrlAltDel/DisableTaskMgr"
