// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxtabletpcinputpanel

// DeviceRoot is the Device root of ADMX_TabletPCInputPanel.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel"

// DevicePrediction2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/Prediction_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/Prediction_2
const DevicePrediction2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/Prediction_2"

// DeviceIPTIPTarget2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTarget_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTarget_2
const DeviceIPTIPTarget2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTarget_2"

// DeviceIPTIPTouchTarget2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTouchTarget_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTouchTarget_2
const DeviceIPTIPTouchTarget2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTouchTarget_2"

// DeviceRareChar2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/RareChar_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/RareChar_2
const DeviceRareChar2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/RareChar_2"

// DeviceEdgeTarget2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/EdgeTarget_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/EdgeTarget_2
const DeviceEdgeTarget2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/EdgeTarget_2"

// DeviceAutoComplete2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/AutoComplete_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/AutoComplete_2
const DeviceAutoComplete2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/AutoComplete_2"

// DevicePasswordSecurity2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/PasswordSecurity_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/PasswordSecurity_2
const DevicePasswordSecurity2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/PasswordSecurity_2"

// DeviceScratchOut2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/ScratchOut_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/ScratchOut_2
const DeviceScratchOut2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/ScratchOut_2"

// UserRoot is the User root of ADMX_TabletPCInputPanel.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel"

// UserPrediction1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/Prediction_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/Prediction_1
const UserPrediction1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/Prediction_1"

// UserIPTIPTarget1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTarget_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTarget_1
const UserIPTIPTarget1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTarget_1"

// UserIPTIPTouchTarget1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTouchTarget_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTouchTarget_1
const UserIPTIPTouchTarget1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/IPTIPTouchTarget_1"

// UserRareChar1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/RareChar_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/RareChar_1
const UserRareChar1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/RareChar_1"

// UserEdgeTarget1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/EdgeTarget_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/EdgeTarget_1
const UserEdgeTarget1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/EdgeTarget_1"

// UserAutoComplete1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/AutoComplete_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/AutoComplete_1
const UserAutoComplete1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/AutoComplete_1"

// UserPasswordSecurity1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/PasswordSecurity_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/PasswordSecurity_1
const UserPasswordSecurity1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/PasswordSecurity_1"

// UserScratchOut1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/ScratchOut_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/ScratchOut_1
const UserScratchOut1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletPCInputPanel/ScratchOut_1"
