// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package remotedesktop

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// DeviceTree is the Device root ./Device/Vendor/MSFT/Policy/Config/RemoteDesktop.
var DeviceTree = csp.Inherit(&csp.Tree{Name: "RemoteDesktop", File: "RemoteDesktop_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "RemoteDesktop", URI: "./Device/Vendor/MSFT/Policy/Config/RemoteDesktop", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "LoadAadCredKeyFromProfile", URI: "./Device/Vendor/MSFT/Policy/Config/RemoteDesktop/LoadAadCredKeyFromProfile", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Allow encrypted DPAPI cred keys to be loaded from user profiles for AAD accounts.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000"}, CspVersion: "11.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
	},
}})

// UserTree is the User root ./User/Vendor/MSFT/Policy/Config/RemoteDesktop.
var UserTree = csp.Inherit(&csp.Tree{Name: "RemoteDesktop", File: "RemoteDesktop_AreaDDF.xml", Scope: "User", PolicyArea: true, Root: &csp.Node{
	Name: "RemoteDesktop", URI: "./User/Vendor/MSFT/Policy/Config/RemoteDesktop", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AutoSubscription", URI: "./User/Vendor/MSFT/Policy/Config/RemoteDesktop/AutoSubscription", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19044.1370", "10.0.19043.1370", "10.0.19042.1370", "10.0.19041.1370"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "None", Value: "", Enum: nil, ADMX: nil, ListDelimiter: "|"},
			GpMapping:          &csp.GpMapping{EnglishName: "AutoSubscription", AreaPath: "TerminalServer~AT~WindowsComponents~TS_GP_NODE~TS_TERMINAL_SERVER~AutoSubscription", Element: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of RemoteDesktop in this package.
var Trees = []*csp.Tree{DeviceTree, UserTree}
