// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package remotedesktop

// DeviceRoot is the Device root of RemoteDesktop.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/RemoteDesktop"

// DeviceLoadAadCredKeyFromProfile is ./Device/Vendor/MSFT/Policy/Config/RemoteDesktop/LoadAadCredKeyFromProfile.
// Allow encrypted DPAPI cred keys to be loaded from user profiles for AAD accounts.
const DeviceLoadAadCredKeyFromProfile = "./Device/Vendor/MSFT/Policy/Config/RemoteDesktop/LoadAadCredKeyFromProfile"

// UserRoot is the User root of RemoteDesktop.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/RemoteDesktop"

// UserAutoSubscription is ./User/Vendor/MSFT/Policy/Config/RemoteDesktop/AutoSubscription.
// ./User/Vendor/MSFT/Policy/Config/RemoteDesktop/AutoSubscription
const UserAutoSubscription = "./User/Vendor/MSFT/Policy/Config/RemoteDesktop/AutoSubscription"
