// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package certificatestore

import "net/url"

// Root is the Device root of CertificateStore.
const Root = "./Device/Vendor/MSFT/CertificateStore"

// ROOT is ./Device/Vendor/MSFT/CertificateStore/ROOT.
// This store holds only root (self-signed) certificates.
const ROOT = "./Device/Vendor/MSFT/CertificateStore/ROOT"

// ROOTCertHash is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}.
// The SHA1 hash for the certificate.
func ROOTCertHash(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash)
}

// ROOTEncodedCertificate is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}/EncodedCertificate.
// The base64 Encoded X.509 certificate.
func ROOTEncodedCertificate(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash) + "/EncodedCertificate"
}

// ROOTIssuedBy is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}/IssuedBy.
// The name of the certificate issuer.
func ROOTIssuedBy(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash) + "/IssuedBy"
}

// ROOTIssuedTo is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}/IssuedTo.
// The name of the certificate subject.
func ROOTIssuedTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash) + "/IssuedTo"
}

// ROOTValidFrom is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}/ValidFrom.
// The starting date of the certificate's validity.
func ROOTValidFrom(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash) + "/ValidFrom"
}

// ROOTValidTo is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}/ValidTo.
// The expiration date of the certificate.
func ROOTValidTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash) + "/ValidTo"
}

// ROOTTemplateName is ./Device/Vendor/MSFT/CertificateStore/ROOT/{CertHash}/TemplateName.
// Returns the certificate template name.
func ROOTTemplateName(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/" + escape(certHash) + "/TemplateName"
}

// ROOTSystem is ./Device/Vendor/MSFT/CertificateStore/ROOT/System.
// This store holds the System portion of the root store.
const ROOTSystem = "./Device/Vendor/MSFT/CertificateStore/ROOT/System"

// ROOTSystemCertHash is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}.
// The SHA1 hash for the certificate.
func ROOTSystemCertHash(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash)
}

// ROOTSystemEncodedCertificate is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}/EncodedCertificate.
// The base64 Encoded X.509 certificate.
func ROOTSystemEncodedCertificate(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash) + "/EncodedCertificate"
}

// ROOTSystemIssuedBy is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}/IssuedBy.
// The name of the certificate issuer.
func ROOTSystemIssuedBy(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash) + "/IssuedBy"
}

// ROOTSystemIssuedTo is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}/IssuedTo.
// The name of the certificate subject.
func ROOTSystemIssuedTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash) + "/IssuedTo"
}

// ROOTSystemValidFrom is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}/ValidFrom.
// The starting date of the certificate's validity.
func ROOTSystemValidFrom(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash) + "/ValidFrom"
}

// ROOTSystemValidTo is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}/ValidTo.
// The expiration date of the certificate.
func ROOTSystemValidTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash) + "/ValidTo"
}

// ROOTSystemTemplateName is ./Device/Vendor/MSFT/CertificateStore/ROOT/System/{CertHash}/TemplateName.
// Returns the certificate template name.
func ROOTSystemTemplateName(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/ROOT/System/" + escape(certHash) + "/TemplateName"
}

// MY is ./Device/Vendor/MSFT/CertificateStore/MY.
// This store keeps all end-user personal certificates.
const MY = "./Device/Vendor/MSFT/CertificateStore/MY"

// MYUser is ./Device/Vendor/MSFT/CertificateStore/MY/User.
// This store holds the User portion of the MY store.
const MYUser = "./Device/Vendor/MSFT/CertificateStore/MY/User"

// MYUserCertHash is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}.
// The SHA1 hash for the certificate.
func MYUserCertHash(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash)
}

// MYUserEncodedCertificate is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}/EncodedCertificate.
// The base64 Encoded X.509 certificate.
func MYUserEncodedCertificate(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash) + "/EncodedCertificate"
}

// MYUserIssuedBy is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}/IssuedBy.
// The name of the certificate issuer.
func MYUserIssuedBy(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash) + "/IssuedBy"
}

// MYUserIssuedTo is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}/IssuedTo.
// The name of the certificate subject.
func MYUserIssuedTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash) + "/IssuedTo"
}

// MYUserValidFrom is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}/ValidFrom.
// The starting date of the certificate's validity.
func MYUserValidFrom(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash) + "/ValidFrom"
}

// MYUserValidTo is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}/ValidTo.
// The expiration date of the certificate.
func MYUserValidTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash) + "/ValidTo"
}

// MYUserTemplateName is ./Device/Vendor/MSFT/CertificateStore/MY/User/{CertHash}/TemplateName.
// Returns the certificate template name.
func MYUserTemplateName(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/User/" + escape(certHash) + "/TemplateName"
}

// MYSCEP is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP.
// This store holds the SCEP portion of the MY store and handle operations related to SCEP certificate enrollment.
const MYSCEP = "./Device/Vendor/MSFT/CertificateStore/MY/SCEP"

// MYSCEPUniqueID is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}.
// The UniqueID for the SCEP enrollment request.
func MYSCEPUniqueID(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID)
}

// MYSCEPInstall is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install.
// The group to represent the install request
func MYSCEPInstall(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install"
}

// MYSCEPInstallServerURL is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/ServerURL.
// Specify the cert enrollment server.
func MYSCEPInstallServerURL(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/ServerURL"
}

// MYSCEPInstallChallenge is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/Challenge.
// Enroll requester authentication shared secret.
func MYSCEPInstallChallenge(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/Challenge"
}

// MYSCEPInstallEKUMapping is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/EKUMapping.
// Specify extended key usages.
func MYSCEPInstallEKUMapping(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/EKUMapping"
}

// MYSCEPInstallKeyUsage is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/KeyUsage.
// Specify the key usage bits (0x80, 0x20, 0xA0) for the cert.
func MYSCEPInstallKeyUsage(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/KeyUsage"
}

// MYSCEPInstallSubjectName is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/SubjectName.
// Specify the subject name.
func MYSCEPInstallSubjectName(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/SubjectName"
}

// MYSCEPInstallKeyProtection is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/KeyProtection.
// Specify where to keep the private key.
func MYSCEPInstallKeyProtection(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/KeyProtection"
}

// MYSCEPInstallRetryDelay is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/RetryDelay.
// When the SCEP server sends pending status, specify device retry waiting time in minutes.
func MYSCEPInstallRetryDelay(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/RetryDelay"
}

// MYSCEPInstallRetryCount is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/RetryCount.
// When the SCEP sends pending status, specify device retry times.
func MYSCEPInstallRetryCount(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/RetryCount"
}

// MYSCEPInstallTemplateName is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/TemplateName.
// Certificate Template Name OID (As in AD used by PKI infrastructure.
func MYSCEPInstallTemplateName(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/TemplateName"
}

// MYSCEPInstallKeyLength is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/KeyLength.
// Specify private key length (RSA).
func MYSCEPInstallKeyLength(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/KeyLength"
}

// MYSCEPInstallHashAlgrithm is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/HashAlgrithm.
// Client create Cert enroll request, get supported hash OIalgorithm from SCEP server and match it with one specified in this parameter.
func MYSCEPInstallHashAlgrithm(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/HashAlgrithm"
}

// MYSCEPInstallCAThumbPrint is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/CAThumbPrint.
// Specify root CA thumbprint.
func MYSCEPInstallCAThumbPrint(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/CAThumbPrint"
}

// MYSCEPInstallSubjectAlternativeNames is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/SubjectAlternativeNames.
// Specify subject alternative name.
func MYSCEPInstallSubjectAlternativeNames(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/SubjectAlternativeNames"
}

// MYSCEPInstallValidPeriod is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/ValidPeriod.
// Specify the period of time that cert is valid.
func MYSCEPInstallValidPeriod(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/ValidPeriod"
}

// MYSCEPInstallValidPeriodUnit is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/ValidPeriodUnit.
// Specify valid period unit type.
func MYSCEPInstallValidPeriodUnit(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/ValidPeriodUnit"
}

// MYSCEPInstallEnroll is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Install/Enroll.
// Start the cert enrollment.
func MYSCEPInstallEnroll(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Install/Enroll"
}

// MYSCEPCertThumbPrint is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/CertThumbPrint.
// Specify the current cert’s thumbprint.
func MYSCEPCertThumbPrint(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/CertThumbPrint"
}

// MYSCEPStatus is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/Status.
// Specify the latest status for the certificate due to enroll request.
func MYSCEPStatus(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/Status"
}

// MYSCEPErrorCode is ./Device/Vendor/MSFT/CertificateStore/MY/SCEP/{UniqueID}/ErrorCode.
// Specify the last hresult in case enroll action failed.
func MYSCEPErrorCode(uniqueID string) string {
	return "./Device/Vendor/MSFT/CertificateStore/MY/SCEP/" + escape(uniqueID) + "/ErrorCode"
}

// MYWSTEP is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP.
// The parent node that hosts client certificate that is enrolled via WSTEP, e.g.
const MYWSTEP = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP"

// MYWSTEPCertThumprint is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/CertThumprint.
// The thumb print of enrolled MDM client certificate.
const MYWSTEPCertThumprint = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/CertThumprint"

// MYWSTEPRenew is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew.
// The parent node to group renewal related settings.
const MYWSTEPRenew = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew"

// MYWSTEPRenewRenewPeriod is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RenewPeriod.
// Specify the number of days prior to the enrollment cert expiration to prompt the user to renew.
const MYWSTEPRenewRenewPeriod = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RenewPeriod"

// MYWSTEPRenewServerURL is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/ServerURL.
// Optional.
const MYWSTEPRenewServerURL = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/ServerURL"

// MYWSTEPRenewRetryInterval is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RetryInterval.
// Optional.
const MYWSTEPRenewRetryInterval = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RetryInterval"

// MYWSTEPRenewROBOSupport is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/ROBOSupport.
// Optional.
const MYWSTEPRenewROBOSupport = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/ROBOSupport"

// MYWSTEPRenewStatus is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/Status.
// Show the latest action status for this certificate.
const MYWSTEPRenewStatus = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/Status"

// MYWSTEPRenewErrorCode is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/ErrorCode.
// If certificate renew fails, this node provide the last hresult code during renew process.
const MYWSTEPRenewErrorCode = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/ErrorCode"

// MYWSTEPRenewLastRenewalAttemptTime is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/LastRenewalAttemptTime.
// Time of last attempted renew
const MYWSTEPRenewLastRenewalAttemptTime = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/LastRenewalAttemptTime"

// MYWSTEPRenewRenewNow is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RenewNow.
// Initiate a renew now
const MYWSTEPRenewRenewNow = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RenewNow"

// MYWSTEPRenewRetryAfterExpiryInterval is ./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RetryAfterExpiryInterval.
// How long after the enrollment cert has expiried to keep trying to renew
const MYWSTEPRenewRetryAfterExpiryInterval = "./Device/Vendor/MSFT/CertificateStore/MY/WSTEP/Renew/RetryAfterExpiryInterval"

// CA is ./Device/Vendor/MSFT/CertificateStore/CA.
// This cryptographic store contains intermediary certification authorities.
const CA = "./Device/Vendor/MSFT/CertificateStore/CA"

// CACertHash is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}.
// The SHA1 hash for the certificate.
func CACertHash(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash)
}

// CAEncodedCertificate is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}/EncodedCertificate.
// The base64 Encoded X.509 certificate
func CAEncodedCertificate(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash) + "/EncodedCertificate"
}

// CAIssuedBy is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}/IssuedBy.
// The name of the certificate issuer.
func CAIssuedBy(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash) + "/IssuedBy"
}

// CAIssuedTo is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}/IssuedTo.
// The name of the certificate subject.
func CAIssuedTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash) + "/IssuedTo"
}

// CAValidFrom is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}/ValidFrom.
// The starting date of the certificate's validity.
func CAValidFrom(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash) + "/ValidFrom"
}

// CAValidTo is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}/ValidTo.
// The expiration date of the certificate.
func CAValidTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash) + "/ValidTo"
}

// CATemplateName is ./Device/Vendor/MSFT/CertificateStore/CA/{CertHash}/TemplateName.
// Returns the certificate template name.
func CATemplateName(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/" + escape(certHash) + "/TemplateName"
}

// CASystem is ./Device/Vendor/MSFT/CertificateStore/CA/System.
// This store holds the System portion of the CA store.
const CASystem = "./Device/Vendor/MSFT/CertificateStore/CA/System"

// CASystemCertHash is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}.
// The SHA1 hash for the certificate.
func CASystemCertHash(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash)
}

// CASystemEncodedCertificate is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}/EncodedCertificate.
// The base64 Encoded X.509 certificate.
func CASystemEncodedCertificate(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash) + "/EncodedCertificate"
}

// CASystemIssuedBy is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}/IssuedBy.
// The name of the certificate issuer.
func CASystemIssuedBy(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash) + "/IssuedBy"
}

// CASystemIssuedTo is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}/IssuedTo.
// The name of the certificate subject.
func CASystemIssuedTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash) + "/IssuedTo"
}

// CASystemValidFrom is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}/ValidFrom.
// The starting date of the certificate's validity.
func CASystemValidFrom(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash) + "/ValidFrom"
}

// CASystemValidTo is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}/ValidTo.
// The expiration date of the certificate.
func CASystemValidTo(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash) + "/ValidTo"
}

// CASystemTemplateName is ./Device/Vendor/MSFT/CertificateStore/CA/System/{CertHash}/TemplateName.
// Returns the certificate template name.
func CASystemTemplateName(certHash string) string {
	return "./Device/Vendor/MSFT/CertificateStore/CA/System/" + escape(certHash) + "/TemplateName"
}

// escape encodes one dynamic segment for a LocURI.
func escape(s string) string { return url.PathEscape(s) }
