// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxtpm

// Root is the Device root of ADMX_TPM.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM"

// OptIntoDSHAName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OptIntoDSHA_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OptIntoDSHA_Name
const OptIntoDSHAName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OptIntoDSHA_Name"

// OSManagedAuthName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OSManagedAuth_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OSManagedAuth_Name
const OSManagedAuthName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/OSManagedAuth_Name"

// BlockedCommandsListName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/BlockedCommandsList_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/BlockedCommandsList_Name
const BlockedCommandsListName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/BlockedCommandsList_Name"

// ClearTPMIfNotReadyName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/ClearTPMIfNotReady_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/ClearTPMIfNotReady_Name
const ClearTPMIfNotReadyName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/ClearTPMIfNotReady_Name"

// UseLegacyDAPName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/UseLegacyDAP_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/UseLegacyDAP_Name
const UseLegacyDAPName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/UseLegacyDAP_Name"

// IgnoreDefaultListName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreDefaultList_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreDefaultList_Name
const IgnoreDefaultListName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreDefaultList_Name"

// IgnoreLocalListName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreLocalList_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreLocalList_Name
const IgnoreLocalListName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/IgnoreLocalList_Name"

// StandardUserAuthorizationFailureIndividualThresholdName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureIndividualThreshold_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureIndividualThreshold_Name
const StandardUserAuthorizationFailureIndividualThresholdName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureIndividualThreshold_Name"

// StandardUserAuthorizationFailureDurationName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureDuration_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureDuration_Name
const StandardUserAuthorizationFailureDurationName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureDuration_Name"

// StandardUserAuthorizationFailureTotalThresholdName is ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureTotalThreshold_Name.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureTotalThreshold_Name
const StandardUserAuthorizationFailureTotalThresholdName = "./Device/Vendor/MSFT/Policy/Config/ADMX_TPM/StandardUserAuthorizationFailureTotalThreshold_Name"
