// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package dataprotection

// Root is the Device root of DataProtection.
const Root = "./Device/Vendor/MSFT/Policy/Config/DataProtection"

// LegacySelectiveWipeID is ./Device/Vendor/MSFT/Policy/Config/DataProtection/LegacySelectiveWipeID.
// Important.
const LegacySelectiveWipeID = "./Device/Vendor/MSFT/Policy/Config/DataProtection/LegacySelectiveWipeID"

// AllowDirectMemoryAccess is ./Device/Vendor/MSFT/Policy/Config/DataProtection/AllowDirectMemoryAccess.
// This policy setting allows you to block direct memory access (DMA) for all hot pluggable PCI downstream ports until a user logs into Windows.
const AllowDirectMemoryAccess = "./Device/Vendor/MSFT/Policy/Config/DataProtection/AllowDirectMemoryAccess"
