// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package localsecurityauthority

// ConfigureLsaProtectedProcess values (ENUM).
const (
	// Disabled. Default value. LSA will not run as protected process.
	ConfigureLsaProtectedProcessDisabledDefaultValueLSA = "0"
	// Enabled with UEFI lock. LSA will run as protected process and this configuration is UEFI locked.
	ConfigureLsaProtectedProcessEnabledWithUEFILock = "1"
	// Enabled without UEFI lock. LSA will run as protected process and this configuration is not UEFI locked.
	ConfigureLsaProtectedProcessEnabledWithoutUEFILock = "2"
)
