// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package abovelock

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/AboveLock.
var Tree = csp.Inherit(&csp.Tree{Name: "AboveLock", File: "AboveLock_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "AboveLock", URI: "./Device/Vendor/MSFT/Policy/Config/AboveLock", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AllowActionCenterNotifications", URI: "./Device/Vendor/MSFT/Policy/Config/AboveLock/AllowActionCenterNotifications", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy is deprecated",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.10240"}, CspVersion: "1.0", EditionAllowList: nil, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LowestValueMostSecure",
			Deprecated:         &csp.Deprecated{OsBuildDeprecated: "10.0.22000"},
		},
		&csp.Node{
			Name: "AllowCortanaAboveLock", URI: "./Device/Vendor/MSFT/Policy/Config/AboveLock/AllowCortanaAboveLock", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Specifies whether or not the user can interact with Cortana using speech while the system is locked. If you enable or don’t configure this setting, the user can interact with Cortana using speech while the system is locked. If you disable this setting, the system will need to be unlocked for the user to interact with Cortana using speech.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.14393"}, CspVersion: "4.1", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "AllowCortanaAboveLock", AreaPath: "Search~AT~WindowsComponents~Search", Element: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
		&csp.Node{
			Name: "AllowToasts", URI: "./Device/Vendor/MSFT/Policy/Config/AboveLock/AllowToasts", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Specifies whether to allow toast notifications above the device lock screen. Most restricted value is 0.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.14393"}, CspVersion: "4.1", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Not allowed."}, {Value: "1", Description: "Allowed."}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
		&csp.Node{
			Name: "ConfigureAudioOnLockScreen", URI: "./Device/Vendor/MSFT/Policy/Config/AboveLock/ConfigureAudioOnLockScreen", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy will allow the audio above lock screen to be managed by IT admins and allow apps like digital signage to play audio above lock screen without having a user signed on.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"99.9.99999"}, CspVersion: "9.9", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "No audio playback or recording on lock screen (aside from OS defined exceptions)."}, {Value: "1", Description: "Audio playback allowed on lock screen. Audio recording is not allowed."}, {Value: "2", Description: "Audio playback and recording allowed on lock screen."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "ConfigureAudioOnLockScreen", AreaPath: "Audio~AT~WindowsComponents~Audio", Element: "ConfigureAudioOnLockScreen_Enum"},
			ConflictResolution: "LowestValueMostSecure",
		},
	},
}})

// Trees lists every root of AboveLock in this package.
var Trees = []*csp.Tree{Tree}
