// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxtabletshell

// DeviceRoot is the Device root of ADMX_TabletShell.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell"

// DeviceDisableInkball2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableInkball_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableInkball_2
const DeviceDisableInkball2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableInkball_2"

// DeviceDisableNoteWriterPrinting2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableNoteWriterPrinting_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableNoteWriterPrinting_2
const DeviceDisableNoteWriterPrinting2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableNoteWriterPrinting_2"

// DeviceDisableSnippingTool2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableSnippingTool_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableSnippingTool_2
const DeviceDisableSnippingTool2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableSnippingTool_2"

// DeviceDisableJournal2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableJournal_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableJournal_2
const DeviceDisableJournal2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableJournal_2"

// DeviceTurnOffFeedback2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffFeedback_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffFeedback_2
const DeviceTurnOffFeedback2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffFeedback_2"

// DevicePreventBackEscMapping2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventBackEscMapping_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventBackEscMapping_2
const DevicePreventBackEscMapping2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventBackEscMapping_2"

// DevicePreventLaunchApp2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventLaunchApp_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventLaunchApp_2
const DevicePreventLaunchApp2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventLaunchApp_2"

// DevicePreventPressAndHold2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventPressAndHold_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventPressAndHold_2
const DevicePreventPressAndHold2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventPressAndHold_2"

// DeviceTurnOffButtons2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffButtons_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffButtons_2
const DeviceTurnOffButtons2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffButtons_2"

// DevicePreventFlicksLearningMode2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicksLearningMode_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicksLearningMode_2
const DevicePreventFlicksLearningMode2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicksLearningMode_2"

// DevicePreventFlicks2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicks_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicks_2
const DevicePreventFlicks2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicks_2"

// UserRoot is the User root of ADMX_TabletShell.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell"

// UserDisableInkball1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableInkball_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableInkball_1
const UserDisableInkball1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableInkball_1"

// UserDisableNoteWriterPrinting1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableNoteWriterPrinting_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableNoteWriterPrinting_1
const UserDisableNoteWriterPrinting1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableNoteWriterPrinting_1"

// UserDisableSnippingTool1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableSnippingTool_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableSnippingTool_1
const UserDisableSnippingTool1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableSnippingTool_1"

// UserDisableJournal1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableJournal_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableJournal_1
const UserDisableJournal1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/DisableJournal_1"

// UserTurnOffFeedback1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffFeedback_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffFeedback_1
const UserTurnOffFeedback1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffFeedback_1"

// UserPreventBackEscMapping1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventBackEscMapping_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventBackEscMapping_1
const UserPreventBackEscMapping1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventBackEscMapping_1"

// UserPreventLaunchApp1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventLaunchApp_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventLaunchApp_1
const UserPreventLaunchApp1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventLaunchApp_1"

// UserPreventPressAndHold1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventPressAndHold_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventPressAndHold_1
const UserPreventPressAndHold1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventPressAndHold_1"

// UserTurnOffButtons1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffButtons_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffButtons_1
const UserTurnOffButtons1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/TurnOffButtons_1"

// UserPreventFlicksLearningMode1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicksLearningMode_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicksLearningMode_1
const UserPreventFlicksLearningMode1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicksLearningMode_1"

// UserPreventFlicks1 is ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicks_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicks_1
const UserPreventFlicks1 = "./User/Vendor/MSFT/Policy/Config/ADMX_TabletShell/PreventFlicks_1"
