// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxwindowscolorsystem

// DeviceRoot is the Device root of ADMX_WindowsColorSystem.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem"

// DeviceProhibitChangingInstalledProfileList2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem/ProhibitChangingInstalledProfileList_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem/ProhibitChangingInstalledProfileList_2
const DeviceProhibitChangingInstalledProfileList2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem/ProhibitChangingInstalledProfileList_2"

// UserRoot is the User root of ADMX_WindowsColorSystem.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem"

// UserProhibitChangingInstalledProfileList1 is ./User/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem/ProhibitChangingInstalledProfileList_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem/ProhibitChangingInstalledProfileList_1
const UserProhibitChangingInstalledProfileList1 = "./User/Vendor/MSFT/Policy/Config/ADMX_WindowsColorSystem/ProhibitChangingInstalledProfileList_1"
