// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxdnsclient

// Root is the Device root of ADMX_DnsClient.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient"

// DNSAppendToMultiLabelName is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_AppendToMultiLabelName.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_AppendToMultiLabelName
const DNSAppendToMultiLabelName = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_AppendToMultiLabelName"

// DNSAllowFQDNNetBiosQueries is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_AllowFQDNNetBiosQueries.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_AllowFQDNNetBiosQueries
const DNSAllowFQDNNetBiosQueries = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_AllowFQDNNetBiosQueries"

// DNSDomain is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_Domain.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_Domain
const DNSDomain = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_Domain"

// DNSNameServer is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_NameServer.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_NameServer
const DNSNameServer = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_NameServer"

// DNSSearchList is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SearchList.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SearchList
const DNSSearchList = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SearchList"

// DNSRegistrationEnabled is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationEnabled.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationEnabled
const DNSRegistrationEnabled = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationEnabled"

// DNSIdnMapping is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_IdnMapping.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_IdnMapping
const DNSIdnMapping = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_IdnMapping"

// DNSPreferLocalResponsesOverLowerOrderDns is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_PreferLocalResponsesOverLowerOrderDns.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_PreferLocalResponsesOverLowerOrderDns
const DNSPreferLocalResponsesOverLowerOrderDns = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_PreferLocalResponsesOverLowerOrderDns"

// DNSPrimaryDnsSuffix is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_PrimaryDnsSuffix.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_PrimaryDnsSuffix
const DNSPrimaryDnsSuffix = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_PrimaryDnsSuffix"

// DNSUseDomainNameDevolution is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UseDomainNameDevolution.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UseDomainNameDevolution
const DNSUseDomainNameDevolution = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UseDomainNameDevolution"

// DNSDomainNameDevolutionLevel is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_DomainNameDevolutionLevel.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_DomainNameDevolutionLevel
const DNSDomainNameDevolutionLevel = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_DomainNameDevolutionLevel"

// DNSRegisterAdapterName is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegisterAdapterName.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegisterAdapterName
const DNSRegisterAdapterName = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegisterAdapterName"

// DNSRegisterReverseLookup is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegisterReverseLookup.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegisterReverseLookup
const DNSRegisterReverseLookup = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegisterReverseLookup"

// DNSRegistrationRefreshInterval is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationRefreshInterval.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationRefreshInterval
const DNSRegistrationRefreshInterval = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationRefreshInterval"

// DNSRegistrationOverwritesInConflict is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationOverwritesInConflict.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationOverwritesInConflict
const DNSRegistrationOverwritesInConflict = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationOverwritesInConflict"

// DNSRegistrationTtl is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationTtl.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationTtl
const DNSRegistrationTtl = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_RegistrationTtl"

// DNSIdnEncoding is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_IdnEncoding.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_IdnEncoding
const DNSIdnEncoding = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_IdnEncoding"

// TurnOffMulticast is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/Turn_Off_Multicast.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/Turn_Off_Multicast
const TurnOffMulticast = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/Turn_Off_Multicast"

// DNSSmartMultiHomedNameResolution is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SmartMultiHomedNameResolution.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SmartMultiHomedNameResolution
const DNSSmartMultiHomedNameResolution = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SmartMultiHomedNameResolution"

// DNSSmartProtocolReorder is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SmartProtocolReorder.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SmartProtocolReorder
const DNSSmartProtocolReorder = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_SmartProtocolReorder"

// DNSUpdateSecurityLevel is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UpdateSecurityLevel.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UpdateSecurityLevel
const DNSUpdateSecurityLevel = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UpdateSecurityLevel"

// DNSUpdateTopLevelDomainZones is ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UpdateTopLevelDomainZones.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UpdateTopLevelDomainZones
const DNSUpdateTopLevelDomainZones = "./Device/Vendor/MSFT/Policy/Config/ADMX_DnsClient/DNS_UpdateTopLevelDomainZones"
