// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxdevicesetup

// Root is the Device root of ADMX_DeviceSetup.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup"

// DriverSearchPlacesSearchOrderConfiguration is ./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup/DriverSearchPlaces_SearchOrderConfiguration.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup/DriverSearchPlaces_SearchOrderConfiguration
const DriverSearchPlacesSearchOrderConfiguration = "./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup/DriverSearchPlaces_SearchOrderConfiguration"

// DeviceInstallBalloonTips is ./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup/DeviceInstall_BalloonTips.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup/DeviceInstall_BalloonTips
const DeviceInstallBalloonTips = "./Device/Vendor/MSFT/Policy/Config/ADMX_DeviceSetup/DeviceInstall_BalloonTips"
