// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package datausage

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/DataUsage.
var Tree = csp.Inherit(&csp.Tree{Name: "DataUsage", File: "DataUsage_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "DataUsage", URI: "./Device/Vendor/MSFT/Policy/Config/DataUsage", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "SetCost3G", URI: "./Device/Vendor/MSFT/Policy/Config/DataUsage/SetCost3G", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "wwansvc~AT~Network~WwanSvc_Category~NetworkCost_Category", Name: "SetCost3G", File: "wwansvc.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "SetCost4G", URI: "./Device/Vendor/MSFT/Policy/Config/DataUsage/SetCost4G", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "wwansvc~AT~Network~WwanSvc_Category~NetworkCost_Category", Name: "SetCost4G", File: "wwansvc.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of DataUsage in this package.
var Trees = []*csp.Tree{Tree}
