// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package kioskbrowser

// DeviceRoot is the Device root of KioskBrowser.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser"

// DeviceBlockedUrls is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls.
// List of blocked website URLs (with wildcard support).
const DeviceBlockedUrls = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls"

// DeviceBlockedUrlExceptions is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions.
// List of exceptions to the blocked website URLs (with wildcard support).
const DeviceBlockedUrlExceptions = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions"

// DeviceDefaultURL is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL.
// Configures the default URL kiosk browsers to navigate on launch and restart.
const DeviceDefaultURL = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL"

// DeviceEnableEndSessionButton is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton.
// Enable/disable kiosk browser's end session button.
const DeviceEnableEndSessionButton = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton"

// DeviceEnableHomeButton is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton.
// Enable/disable kiosk browser's home button.
const DeviceEnableHomeButton = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton"

// DeviceEnableNavigationButtons is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons.
// Enable/disable kiosk browser's navigation buttons (forward/back).
const DeviceEnableNavigationButtons = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons"

// DeviceRestartOnIdleTime is ./Device/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime.
// Amount of time in minutes the session is idle until the kiosk browser restarts in a fresh state.
const DeviceRestartOnIdleTime = "./Device/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime"

// UserRoot is the User root of KioskBrowser.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/KioskBrowser"

// UserBlockedUrls is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls.
// List of blocked website URLs (with wildcard support).
const UserBlockedUrls = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrls"

// UserBlockedUrlExceptions is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions.
// List of exceptions to the blocked website URLs (with wildcard support).
const UserBlockedUrlExceptions = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/BlockedUrlExceptions"

// UserDefaultURL is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL.
// Configures the default URL kiosk browsers to navigate on launch and restart.
const UserDefaultURL = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/DefaultURL"

// UserEnableEndSessionButton is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton.
// Enable/disable kiosk browser's end session button.
const UserEnableEndSessionButton = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableEndSessionButton"

// UserEnableHomeButton is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton.
// Enable/disable kiosk browser's home button.
const UserEnableHomeButton = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableHomeButton"

// UserEnableNavigationButtons is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons.
// Enable/disable kiosk browser's navigation buttons (forward/back).
const UserEnableNavigationButtons = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/EnableNavigationButtons"

// UserRestartOnIdleTime is ./User/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime.
// Amount of time in minutes the session is idle until the kiosk browser restarts in a fresh state.
const UserRestartOnIdleTime = "./User/Vendor/MSFT/Policy/Config/KioskBrowser/RestartOnIdleTime"
