// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package languagepackmanagement

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/LanguagePackManagement.
var Tree = csp.Inherit(&csp.Tree{Name: "LanguagePackManagement", File: "LanguagePackManagement.xml", Scope: "Device", PolicyArea: false, Root: &csp.Node{
	Name: "LanguagePackManagement", URI: "./Device/Vendor/MSFT/LanguagePackManagement", Format: "node",
	Access:           []csp.Access{"Add", "Delete", "Get"},
	Description:      "CSP for managing language packs and language settings.",
	Occurrence:       "One",
	Permanent:        true,
	OwnApplicability: true,
	Applicability:    &csp.Applicability{OsBuildVersions: []string{"99.9.9999"}, CspVersion: "1.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x62", "0x63", "0x64", "0x65", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF", "0xD2"}, RequiresAzureAd: false},
	Children: []*csp.Node{
		&csp.Node{
			Name: "InstalledLanguages", URI: "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages", Format: "node",
			Access:      []csp.Access{"Get"},
			Description: "Languages currently installed on the device.",
			Occurrence:  "One",
			Permanent:   true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "", URI: "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages/{Language ID}", Format: "node",
					Title:       "Language ID",
					Access:      []csp.Access{"Delete", "Get"},
					Description: "Language tag of an installed language on the device. Delete to uninstall.",
					Occurrence:  "OneOrMore",
					Dynamic:     true,
					Naming:      csp.Naming{Kind: "ClientInventory", Pattern: ""},
					Children: []*csp.Node{
						&csp.Node{
							Name: "Providers", URI: "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages/{Language ID}/Providers", Format: "int",
							Access:      []csp.Access{"Get"},
							Description: "Numeric representation of how a language is installed. 1 - The system language pack is installed; 2 - The Local Experience Pack is installed; 3 - Both are installed.",
							Occurrence:  "One",
						},
						&csp.Node{
							Name: "LanguageFeatures", URI: "./Device/Vendor/MSFT/LanguagePackManagement/InstalledLanguages/{Language ID}/LanguageFeatures", Format: "int",
							Access:      []csp.Access{"Get"},
							Description: "Numeric representation of the language features installed. Basic Typing - 1 (0x1), Fonts - 2 (0x2), Handwriting - 4 (0x4), Speech - 8 (0x8), TextToSpeech - 16 (0x10), OCR - 32 (0x20), LocaleData - 64 (0x40), SupplementFonts - 128 (0x80).",
							Occurrence:  "One",
						},
					},
				},
			},
		},
		&csp.Node{
			Name: "Install", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install", Format: "node",
			Access:      []csp.Access{"Get"},
			Description: "Language to be installed or being installed.",
			Occurrence:  "One",
			Permanent:   true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install/{Language ID}", Format: "node",
					Title:       "Language ID",
					Access:      []csp.Access{"Add", "Delete", "Get"},
					Description: "Language tag of the language to be installed or being installed.",
					Occurrence:  "ZeroOrMore",
					Dynamic:     true,
					Naming:      csp.Naming{Kind: "UniqueName", Pattern: "Language tag of the language to be installed or being installed."},
					Children: []*csp.Node{
						&csp.Node{
							Name: "Status", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install/{Language ID}/Status", Format: "int",
							Access:      []csp.Access{"Get"},
							Description: "Status of the language queued for install. 0 – not started; 1 – in progress; 2 – succeeded; 3 – failed; 4 – partially succeeded.",
							Occurrence:  "One",
						},
						&csp.Node{
							Name: "ErrorCode", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install/{Language ID}/ErrorCode", Format: "int",
							Access:      []csp.Access{"Get"},
							Description: "Error code of queued language installation. 0 if there is no error.",
							Occurrence:  "One",
						},
						&csp.Node{
							Name: "CopyToDeviceInternationalSettings", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install/{Language ID}/CopyToDeviceInternationalSettings", Format: "bool",
							Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
							Description:   "Copies the language to the international settings (i.e., locale, input layout, speech recognizer, preferred UI language) of the device immediately after installation if the value is true. Default value is false.",
							Default:       "false",
							Occurrence:    "One",
							AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "false", Description: "Don't copy the language to the international settings immediately after installation."}, {Value: "true", Description: "Copy the language to the international settings immediately after installation."}}, ADMX: nil, ListDelimiter: ""},
						},
						&csp.Node{
							Name: "EnableLanguageFeatureInstallations", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install/{Language ID}/EnableLanguageFeatureInstallations", Format: "bool",
							Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
							Description:   "Enables installations of all available language features when the value is true. Default value is true.",
							Default:       "true",
							Occurrence:    "One",
							AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "true", Description: "Install all available language features."}, {Value: "false", Description: "Install only the required language features."}}, ADMX: nil, ListDelimiter: ""},
						},
						&csp.Node{
							Name: "StartInstallation", URI: "./Device/Vendor/MSFT/LanguagePackManagement/Install/{Language ID}/StartInstallation", Format: "null",
							Access:      []csp.Access{"Exec"},
							Description: "Execution node to queue a language for installation on the device.",
							Occurrence:  "One",
						},
					},
				},
			},
		},
		&csp.Node{
			Name: "LanguageSettings", URI: "./Device/Vendor/MSFT/LanguagePackManagement/LanguageSettings", Format: "node",
			Access:      []csp.Access{"Get"},
			Description: "Language settings of the device.",
			Occurrence:  "One",
			Permanent:   true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "SystemPreferredUILanguages", URI: "./Device/Vendor/MSFT/LanguagePackManagement/LanguageSettings/SystemPreferredUILanguages", Format: "chr",
					Access:        []csp.Access{"Get", "Replace"},
					Description:   "System Preferred UI Language of the device.",
					Occurrence:    "One",
					Permanent:     true,
					AllowedValues: &csp.AllowedValues{Type: "None", Value: "", Enum: nil, ADMX: nil, ListDelimiter: ""},
				},
			},
		},
	},
}})

// Trees lists every root of LanguagePackManagement in this package.
var Trees = []*csp.Tree{Tree}
