// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package lockdown

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/LockDown.
var Tree = csp.Inherit(&csp.Tree{Name: "LockDown", File: "LockDown_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "LockDown", URI: "./Device/Vendor/MSFT/Policy/Config/LockDown", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AllowEdgeSwipe", URI: "./Device/Vendor/MSFT/Policy/Config/LockDown/AllowEdgeSwipe", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Allows the user to invoke any system user interface by swiping in from any screen edge using touch. The easiest way to verify the policy is to restart the explorer process or to reboot after the policy is applied. And then try to swipe from the right edge of the screen. The desired result is for Action Center to not be invoked by the swipe. You can also enter tablet mode and attempt to swipe from the top of the screen to rearrange. That will also be disabled.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.14393"}, CspVersion: "4.1", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Disallow edge swipe."}, {Value: "1", Description: "Allow edge swipe."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "AllowEdgeSwipe", AreaPath: "EdgeUI~AT~WindowsComponents~EdgeUI", Element: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
	},
}})

// Trees lists every root of LockDown in this package.
var Trees = []*csp.Tree{Tree}
