// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package lockdown

// AllowEdgeSwipe values (ENUM).
const (
	// Disallow edge swipe.
	AllowEdgeSwipeDisallowEdgeSwipe = "0"
	// Allow edge swipe.
	AllowEdgeSwipeAllowEdgeSwipe = "1"
)
