// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package textinput

// AllowIMELogging values (ENUM).
const (
	// Not allowed.
	AllowIMELoggingNotAllowed = "0"
	// Allowed.
	AllowIMELoggingAllowed = "1"
)

// AllowIMENetworkAccess values (ENUM).
const (
	// Not allowed.
	AllowIMENetworkAccessNotAllowed = "0"
	// Allowed.
	AllowIMENetworkAccessAllowed = "1"
)

// AllowInputPanel values (ENUM).
const (
	// Not allowed.
	AllowInputPanelNotAllowed = "0"
	// Allowed.
	AllowInputPanelAllowed = "1"
)

// AllowJapaneseIMESurrogatePairCharacters values (ENUM).
const (
	// Not allowed.
	AllowJapaneseIMESurrogatePairCharactersNotAllowed = "0"
	// Allowed.
	AllowJapaneseIMESurrogatePairCharactersAllowed = "1"
)

// AllowJapaneseIVSCharacters values (ENUM).
const (
	// Not allowed.
	AllowJapaneseIVSCharactersNotAllowed = "0"
	// Allowed.
	AllowJapaneseIVSCharactersAllowed = "1"
)

// AllowJapaneseNonPublishingStandardGlyph values (ENUM).
const (
	// Not allowed.
	AllowJapaneseNonPublishingStandardGlyphNotAllowed = "0"
	// Allowed.
	AllowJapaneseNonPublishingStandardGlyphAllowed = "1"
)

// AllowJapaneseUserDictionary values (ENUM).
const (
	// Not allowed.
	AllowJapaneseUserDictionaryNotAllowed = "0"
	// Allowed.
	AllowJapaneseUserDictionaryAllowed = "1"
)

// AllowKeyboardTextSuggestions values (ENUM).
const (
	// Disabled.
	AllowKeyboardTextSuggestionsDisabled = "0"
	// Enabled.
	AllowKeyboardTextSuggestionsEnabled = "1"
)

// AllowHardwareKeyboardTextSuggestions values (ENUM).
const (
	// Not allowed.
	AllowHardwareKeyboardTextSuggestionsNotAllowed = "0"
	// Allowed.
	AllowHardwareKeyboardTextSuggestionsAllowed = "1"
)

// AllowLanguageFeaturesUninstall values (ENUM).
const (
	// Not allowed.
	AllowLanguageFeaturesUninstallNotAllowed = "0"
	// Allowed.
	AllowLanguageFeaturesUninstallAllowed = "1"
)

// AllowLinguisticDataCollection values (ENUM).
const (
	// Not allowed.
	AllowLinguisticDataCollectionNotAllowed = "0"
	// Allowed.
	AllowLinguisticDataCollectionAllowed = "1"
)

// ExcludeJapaneseIMEExceptJIS0208 values (ENUM).
const (
	// No characters are filtered.
	ExcludeJapaneseIMEExceptJIS0208NoCharactersAreFiltered = "0"
	// All characters except JIS0208 are filtered.
	ExcludeJapaneseIMEExceptJIS0208AllCharactersExceptJIS0208 = "1"
)

// ExcludeJapaneseIMEExceptJIS0208andEUDC values (ENUM).
const (
	// No characters are filtered.
	ExcludeJapaneseIMEExceptJIS0208andEUDCNoCharactersAreFiltered = "0"
	// All characters except JIS0208 and EUDC are filtered.
	ExcludeJapaneseIMEExceptJIS0208andEUDCAllCharactersExceptJIS0208 = "1"
)

// ExcludeJapaneseIMEExceptShiftJIS values (ENUM).
const (
	// No characters are filtered.
	ExcludeJapaneseIMEExceptShiftJISNoCharactersAreFiltered = "0"
	// All characters except ShiftJIS are filtered.
	ExcludeJapaneseIMEExceptShiftJISAllCharactersExceptShiftJIS = "1"
)

// EnableTouchKeyboardAutoInvokeInDesktopMode values (ENUM).
const (
	// Never.
	EnableTouchKeyboardAutoInvokeInDesktopModeNever = "0"
	// When no keyboard attached.
	EnableTouchKeyboardAutoInvokeInDesktopModeWhenNoKeyboardAttached = "1"
	// Always.
	EnableTouchKeyboardAutoInvokeInDesktopModeAlways = "2"
)

// TouchKeyboardFullModeAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardFullModeAvailabilityTheOSDeterminesWhen = "0"
	// Full keyboard is always available.
	TouchKeyboardFullModeAvailabilityFullKeyboardIsAlways = "1"
	// Full keyboard is always disabled.
	TouchKeyboardFullModeAvailabilityFullKeyboardIsAlways2 = "2"
)

// TouchKeyboardWideModeAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardWideModeAvailabilityTheOSDeterminesWhen = "0"
	// Wide keyboard is always available.
	TouchKeyboardWideModeAvailabilityWideKeyboardIsAlways = "1"
	// Wide keyboard is always disabled.
	TouchKeyboardWideModeAvailabilityWideKeyboardIsAlways2 = "2"
)

// TouchKeyboardNarrowModeAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardNarrowModeAvailabilityTheOSDeterminesWhen = "0"
	// Narrow keyboard is always available.
	TouchKeyboardNarrowModeAvailabilityNarrowKeyboardIsAlways = "1"
	// Narrow keyboard is always disabled.
	TouchKeyboardNarrowModeAvailabilityNarrowKeyboardIsAlways2 = "2"
)

// TouchKeyboardHandwritingModeAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardHandwritingModeAvailabilityTheOSDeterminesWhen = "0"
	// Handwriting input panel is always available.
	TouchKeyboardHandwritingModeAvailabilityHandwritingInputPanelIs = "1"
	// Handwriting input panel is always disabled.
	TouchKeyboardHandwritingModeAvailabilityHandwritingInputPanelIs2 = "2"
)

// TouchKeyboardSplitModeAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardSplitModeAvailabilityTheOSDeterminesWhen = "0"
	// Split keyboard is always available.
	TouchKeyboardSplitModeAvailabilitySplitKeyboardIsAlways = "1"
	// Split keyboard is always disabled.
	TouchKeyboardSplitModeAvailabilitySplitKeyboardIsAlways2 = "2"
)

// TouchKeyboardControllerModeAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardControllerModeAvailabilityTheOSDeterminesWhen = "0"
	// Controller keyboard is always available.
	TouchKeyboardControllerModeAvailabilityControllerKeyboardIsAlways = "1"
	// Controller keyboard is always disabled.
	TouchKeyboardControllerModeAvailabilityControllerKeyboardIsAlways2 = "2"
)

// TouchKeyboardEmojiButtonAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardEmojiButtonAvailabilityTheOSDeterminesWhen = "0"
	// Emoji button on keyboard is always available.
	TouchKeyboardEmojiButtonAvailabilityEmojiButtonOnKeyboard = "1"
	// Emoji button on keyboard is always disabled.
	TouchKeyboardEmojiButtonAvailabilityEmojiButtonOnKeyboard2 = "2"
)

// ForceTouchKeyboardDockedState values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	ForceTouchKeyboardDockedStateTheOSDeterminesWhen = "0"
	// Touch keyboard is always docked.
	ForceTouchKeyboardDockedStateTouchKeyboardIsAlways = "1"
	// Touch keyboard docking can be changed.
	ForceTouchKeyboardDockedStateTouchKeyboardDockingCan = "2"
)

// TouchKeyboardDictationButtonAvailability values (ENUM).
const (
	// The OS determines when it's most appropriate to be available.
	TouchKeyboardDictationButtonAvailabilityTheOSDeterminesWhen = "0"
	// Dictation button on the keyboard is always available.
	TouchKeyboardDictationButtonAvailabilityDictationButtonOnThe = "1"
	// Dictation button on the keyboard is always disabled.
	TouchKeyboardDictationButtonAvailabilityDictationButtonOnThe2 = "2"
)

// ConfigureSimplifiedChineseIMEVersion values (ENUM).
const (
	// Allows you to configure which Microsoft Simplified Chinese IME version to use. The new Microsoft Simplified Chinese IME version is configured by default.
	ConfigureSimplifiedChineseIMEVersionAllowsYouToConfigure = "0"
	// Does not allow you to configure which Microsoft Simplified Chinese IME version to use. The previous version of Microsoft Simplified Chinese IME is always selected.
	ConfigureSimplifiedChineseIMEVersionDoesNotAllowYou = "1"
	// Does not allow you to configure which Microsoft Simplified Chinese IME version to use. The new Microsoft Simplified Chinese IME version is always selected.
	ConfigureSimplifiedChineseIMEVersionDoesNotAllowYou2 = "2"
)

// ConfigureTraditionalChineseIMEVersion values (ENUM).
const (
	// Allows you to configure which Microsoft Traditional Chinese IME version to use. The new Microsoft Traditional Chinese IME version is configured by default.
	ConfigureTraditionalChineseIMEVersionAllowsYouToConfigure = "0"
	// Does not allow you to configure which Microsoft Traditional Chinese IME version to use. The previous version of Microsoft Traditional Chinese IME is always selected.
	ConfigureTraditionalChineseIMEVersionDoesNotAllowYou = "1"
	// Does not allow you to configure which Microsoft Traditional Chinese IME version to use. The new Microsoft Traditional Chinese IME version is always selected.
	ConfigureTraditionalChineseIMEVersionDoesNotAllowYou2 = "2"
)

// ConfigureJapaneseIMEVersion values (ENUM).
const (
	// Allows you to configure which Microsoft Japanese IME version to use. The new Microsoft Japanese IME version is configured by default.
	ConfigureJapaneseIMEVersionAllowsYouToConfigure = "0"
	// Does not allow you to configure which Microsoft Japanese IME version to use. The previous version of Microsoft Japanese IME is always selected.
	ConfigureJapaneseIMEVersionDoesNotAllowYou = "1"
	// Does not allow you to configure which Microsoft Japanese IME version to use. The new Microsoft Japanese IME version is always selected.
	ConfigureJapaneseIMEVersionDoesNotAllowYou2 = "2"
)

// AllowTextInputSuggestionUpdate values (ENUM).
const (
	// Not allowed.
	AllowTextInputSuggestionUpdateNotAllowed = "0"
	// Allowed.
	AllowTextInputSuggestionUpdateAllowed = "1"
)
