// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxdistributedlinktracking

// Root is the Device root of ADMX_DistributedLinkTracking.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_DistributedLinkTracking"

// DLTAllowDomainMode is ./Device/Vendor/MSFT/Policy/Config/ADMX_DistributedLinkTracking/DLT_AllowDomainMode.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_DistributedLinkTracking/DLT_AllowDomainMode
const DLTAllowDomainMode = "./Device/Vendor/MSFT/Policy/Config/ADMX_DistributedLinkTracking/DLT_AllowDomainMode"
