// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package declaredconfiguration

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/DeclaredConfiguration.
var Tree = csp.Inherit(&csp.Tree{Name: "DeclaredConfiguration", File: "DeclaredConfiguration.xml", Scope: "Device", PolicyArea: false, Root: &csp.Node{
	Name: "DeclaredConfiguration", URI: "./Device/Vendor/MSFT/DeclaredConfiguration", Format: "node",
	Access:           []csp.Access{"Get"},
	Description:      "The Declared Configuration CSP (Configuration Service Provider) allows the OMA-DM server to provide the device with the complete collection of setting names and associated values based on a specified scenario. The Declared Configuration stack on the device is responsible for handling the configuration request along with maintaining its state including updates to the scenario. It also provides the means to retrieve a scenario’s settings from the device. The configuration request and settings retrieval request are performed asynchronously, freeing up the server’s worker thread to do other useful work. The subsequent results can be retrieved through Declared Configuration’s result nodes.",
	Occurrence:       "One",
	Permanent:        true,
	OwnApplicability: true,
	Applicability:    &csp.Applicability{OsBuildVersions: []string{"99.9.99999"}, CspVersion: "9.9", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x62", "0x63", "0x64", "0x65", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF", "0xD2"}, RequiresAzureAd: false},
	Children: []*csp.Node{
		&csp.Node{
			Name: "Host", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host", Format: "node",
			Access:      []csp.Access{"Add", "Delete", "Get"},
			Description: "The Host internal node indicates that the target of the configuration request or inventory request is the host OS. This node is for scope in case enclaves are ever targeted for configuration.",
			Occurrence:  "One",
			Children: []*csp.Node{
				&csp.Node{
					Name: "Complete", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete", Format: "node",
					Access:      []csp.Access{"Add", "Delete", "Get"},
					Description: "This internal node indicates that the configuration has discrete settings values and is self-contained with complete setting and value pairs that do not contain placeholders that need to be resolved later with additional data. The request is ready to be processed as is.",
					Occurrence:  "One",
					Children: []*csp.Node{
						&csp.Node{
							Name: "Documents", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents", Format: "node",
							Access:      []csp.Access{"Add", "Delete", "Get"},
							Description: "The Documents node indicates that the configuration is in the form of a document, which is a collection of settings used to configure a scenario by the Declared Configuration stack.",
							Occurrence:  "One",
							Children: []*csp.Node{
								&csp.Node{
									Name: "", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}", Format: "node",
									Title:         "DocID",
									Access:        []csp.Access{"Add", "Delete", "Get"},
									Description:   "Uniquely identifies the configuration document. No other document can have this id. The Id should be a GUID.",
									Occurrence:    "One",
									Dynamic:       true,
									Naming:        csp.Naming{Kind: "ServerGeneratedUniqueIdentifier", Pattern: ""},
									AllowedValues: &csp.AllowedValues{Type: "RegEx", Value: "[0-9A-Fa-f]{8}\\-[0-9A-Fa-f]{4}\\-[0-9A-Fa-f]{4}\\-[0-9A-Fa-f]{4}\\-[0-9A-Fa-f]{12}", Enum: nil, ADMX: nil, ListDelimiter: ""},
									Children: []*csp.Node{
										&csp.Node{
											Name: "Document", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}/Document", Format: "chr",
											Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
											Description:   "The Document node's value is an XML based document containing a collection of settings and values to configure the specified scenario. The Declared Configuration stack verifies the syntax of the document, the stack marks the document to be processed asynchronously by the client. The stack then returns control back to the OMA-DM service. The stack, in turn, asynchronously processes the request. Below is an example of a specified desired state configuration using the Declared Configuration URI ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/27FEA311-68B9-4320-9FC4-296F6FDFAFE2/Document",
											Occurrence:    "One",
											AllowedValues: &csp.AllowedValues{Type: "None", Value: "", Enum: nil, ADMX: nil, ListDelimiter: ""},
										},
										&csp.Node{
											Name: "Properties", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}/Properties", Format: "node",
											Access:      []csp.Access{"Add", "Delete", "Get"},
											Description: "The Properties node encapsulates the list of properties that apply to the specified document referenced by [DocID].",
											Occurrence:  "One",
											Children: []*csp.Node{
												&csp.Node{
													Name: "Abandoned", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}/Properties/Abandoned", Format: "int",
													Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
													Description:   "The Abandoned node allows the OMA-DM server to indicate that the document is no longer managed.",
													Default:       "0",
													Occurrence:    "One",
													AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "The document is no longer managed."}, {Value: "1", Description: "The document is managed."}}, ADMX: nil, ListDelimiter: ""},
												},
											},
										},
									},
								},
							},
						},
						&csp.Node{
							Name: "Results", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results", Format: "node",
							Access:      []csp.Access{"Get"},
							Description: "The Results node indicates that this is part of the URI path that will return an XML document containing the results of the configuration request.",
							Occurrence:  "One",
							Permanent:   true,
							Children: []*csp.Node{
								&csp.Node{
									Name: "", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results/{DocID}", Format: "node",
									Title:       "DocID",
									Access:      []csp.Access{"Get"},
									Description: "Uniquely identifies the configuration document in which results of the configuration request will be returned.",
									Occurrence:  "One",
									Dynamic:     true,
									Naming:      csp.Naming{Kind: "ClientInventory", Pattern: ""},
									Children: []*csp.Node{
										&csp.Node{
											Name: "Document", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results/{DocID}/Document", Format: "chr",
											Access:      []csp.Access{"Get"},
											Description: "The Document node's value is an XML based document containing a collection of setting results from the configuration request specified by [DocId].",
											Occurrence:  "One",
										},
									},
								},
							},
						},
					},
				},
				&csp.Node{
					Name: "Inventory", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory", Format: "node",
					Access:      []csp.Access{"Add", "Delete", "Get"},
					Description: "The Inventory internal node indicates that this is an inventory request. The setting values to be retrieved are specified in an XML document through the Document leaf node.",
					Occurrence:  "One",
					Children: []*csp.Node{
						&csp.Node{
							Name: "Documents", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents", Format: "node",
							Access:      []csp.Access{"Add", "Delete", "Get"},
							Description: "The Documents node indicates that the inventory request is in the form of a document, which is a collection of settings used to retrieve their values.",
							Occurrence:  "One",
							Children: []*csp.Node{
								&csp.Node{
									Name: "", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/{DocID}", Format: "node",
									Title:         "DocID",
									Access:        []csp.Access{"Add", "Delete", "Get"},
									Description:   "Uniquely identifies the inventory document. No other document can have this id. The Id should be a GUID.",
									Occurrence:    "One",
									Dynamic:       true,
									Naming:        csp.Naming{Kind: "ServerGeneratedUniqueIdentifier", Pattern: ""},
									AllowedValues: &csp.AllowedValues{Type: "RegEx", Value: "[0-9A-Fa-f]{8}\\-[0-9A-Fa-f]{4}\\-[0-9A-Fa-f]{4}\\-[0-9A-Fa-f]{4}\\-[0-9A-Fa-f]{12}", Enum: nil, ADMX: nil, ListDelimiter: ""},
									Children: []*csp.Node{
										&csp.Node{
											Name: "Document", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/{DocID}/Document", Format: "chr",
											Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
											Description:   "The Document node's value is an XML based document containing a collection of settings that will be used to retrieve their values. The Declared Configuration stack verifies the syntax of the document, the stack marks the document to be processed asynchronously by the client. The stack then returns control back to the OMA-DM service. The stack, in turn, asynchronously processes the request. Below is an example of a specified desired state configuration using the Declared Configuration URI ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/27FEA311-68B9-4320-9FC4-296F6FDFAFE2/Document",
											Occurrence:    "One",
											AllowedValues: &csp.AllowedValues{Type: "None", Value: "", Enum: nil, ADMX: nil, ListDelimiter: ""},
										},
									},
								},
							},
						},
						&csp.Node{
							Name: "Results", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results", Format: "node",
							Access:      []csp.Access{"Get"},
							Description: "The Results node indicates that this is part of the URI path that will return an XML document containing the results of the inventory request.",
							Occurrence:  "One",
							Permanent:   true,
							Children: []*csp.Node{
								&csp.Node{
									Name: "", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results/{DocID}", Format: "node",
									Title:       "DocID",
									Access:      []csp.Access{"Get"},
									Description: "Uniquely identifies the inventory document. No other document can have this id. The Id should be a GUID.",
									Occurrence:  "One",
									Dynamic:     true,
									Naming:      csp.Naming{Kind: "ClientInventory", Pattern: ""},
									Children: []*csp.Node{
										&csp.Node{
											Name: "Document", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results/{DocID}/Document", Format: "chr",
											Access:      []csp.Access{"Get"},
											Description: "The Document node's value is an XML based document containing a collection of setting results from the inventory request specified by [DocId].",
											Occurrence:  "One",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		&csp.Node{
			Name: "ManagementServiceConfiguration", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/ManagementServiceConfiguration", Format: "node",
			Access:      []csp.Access{"Get"},
			Description: "The ManagementServiceConfiguration node that is used to control certain Windows Declared Configuration behavior",
			Occurrence:  "One",
			Children: []*csp.Node{
				&csp.Node{
					Name: "ConflictResolution", URI: "./Device/Vendor/MSFT/DeclaredConfiguration/ManagementServiceConfiguration/ConflictResolution", Format: "int",
					Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
					Description:   "This node controls to turn on conflict resolution on and off.",
					Occurrence:    "One",
					AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "The conflict resolution is OFF."}, {Value: "1", Description: "The conflict resolution is ON."}}, ADMX: nil, ListDelimiter: ""},
				},
			},
		},
	},
}})

// Trees lists every root of DeclaredConfiguration in this package.
var Trees = []*csp.Tree{Tree}
