// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package declaredconfiguration

import "net/url"

// Root is the Device root of DeclaredConfiguration.
const Root = "./Device/Vendor/MSFT/DeclaredConfiguration"

// Host is ./Device/Vendor/MSFT/DeclaredConfiguration/Host.
// The Host internal node indicates that the target of the configuration request or inventory request is the host OS.
const Host = "./Device/Vendor/MSFT/DeclaredConfiguration/Host"

// HostComplete is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete.
// This internal node indicates that the configuration has discrete settings values and is self-contained with complete setting and value pairs that do not contain placeholders that need to be resolved l...
const HostComplete = "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete"

// HostCompleteDocuments is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents.
// The Documents node indicates that the configuration is in the form of a document, which is a collection of settings used to configure a scenario by the Declared Configuration stack.
const HostCompleteDocuments = "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents"

// HostCompleteDocumentsDocID is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}.
// Uniquely identifies the configuration document.
func HostCompleteDocumentsDocID(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/" + escape(docID)
}

// HostCompleteDocumentsDocument is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}/Document.
// The Document node's value is an XML based document containing a collection of settings and values to configure the specified scenario.
func HostCompleteDocumentsDocument(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/" + escape(docID) + "/Document"
}

// HostCompleteDocumentsProperties is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}/Properties.
// The Properties node encapsulates the list of properties that apply to the specified document referenced by [DocID].
func HostCompleteDocumentsProperties(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/" + escape(docID) + "/Properties"
}

// HostCompleteDocumentsPropertiesAbandoned is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/{DocID}/Properties/Abandoned.
// The Abandoned node allows the OMA-DM server to indicate that the document is no longer managed.
func HostCompleteDocumentsPropertiesAbandoned(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Documents/" + escape(docID) + "/Properties/Abandoned"
}

// HostCompleteResults is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results.
// The Results node indicates that this is part of the URI path that will return an XML document containing the results of the configuration request.
const HostCompleteResults = "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results"

// HostCompleteResultsDocID is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results/{DocID}.
// Uniquely identifies the configuration document in which results of the configuration request will be returned.
func HostCompleteResultsDocID(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results/" + escape(docID)
}

// HostCompleteResultsDocument is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results/{DocID}/Document.
// The Document node's value is an XML based document containing a collection of setting results from the configuration request specified by [DocId].
func HostCompleteResultsDocument(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Complete/Results/" + escape(docID) + "/Document"
}

// HostInventory is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory.
// The Inventory internal node indicates that this is an inventory request.
const HostInventory = "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory"

// HostInventoryDocuments is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents.
// The Documents node indicates that the inventory request is in the form of a document, which is a collection of settings used to retrieve their values.
const HostInventoryDocuments = "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents"

// HostInventoryDocumentsDocID is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/{DocID}.
// Uniquely identifies the inventory document.
func HostInventoryDocumentsDocID(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/" + escape(docID)
}

// HostInventoryDocumentsDocument is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/{DocID}/Document.
// The Document node's value is an XML based document containing a collection of settings that will be used to retrieve their values.
func HostInventoryDocumentsDocument(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Documents/" + escape(docID) + "/Document"
}

// HostInventoryResults is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results.
// The Results node indicates that this is part of the URI path that will return an XML document containing the results of the inventory request.
const HostInventoryResults = "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results"

// HostInventoryResultsDocID is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results/{DocID}.
// Uniquely identifies the inventory document.
func HostInventoryResultsDocID(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results/" + escape(docID)
}

// HostInventoryResultsDocument is ./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results/{DocID}/Document.
// The Document node's value is an XML based document containing a collection of setting results from the inventory request specified by [DocId].
func HostInventoryResultsDocument(docID string) string {
	return "./Device/Vendor/MSFT/DeclaredConfiguration/Host/Inventory/Results/" + escape(docID) + "/Document"
}

// ManagementServiceConfiguration is ./Device/Vendor/MSFT/DeclaredConfiguration/ManagementServiceConfiguration.
// The ManagementServiceConfiguration node that is used to control certain Windows Declared Configuration behavior
const ManagementServiceConfiguration = "./Device/Vendor/MSFT/DeclaredConfiguration/ManagementServiceConfiguration"

// ManagementServiceConfigurationConflictResolution is ./Device/Vendor/MSFT/DeclaredConfiguration/ManagementServiceConfiguration/ConflictResolution.
// This node controls to turn on conflict resolution on and off.
const ManagementServiceConfigurationConflictResolution = "./Device/Vendor/MSFT/DeclaredConfiguration/ManagementServiceConfiguration/ConflictResolution"

// escape encodes one dynamic segment for a LocURI.
func escape(s string) string { return url.PathEscape(s) }
