// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package remotelock

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/RemoteLock.
var Tree = csp.Inherit(&csp.Tree{Name: "RemoteLock", File: "RemoteLock.xml", Scope: "Device", PolicyArea: false, Root: &csp.Node{
	Name: "RemoteLock", URI: "./Device/Vendor/MSFT/RemoteLock", Format: "node",
	Access:           []csp.Access{"Get"},
	Occurrence:       "One",
	Permanent:        true,
	OwnApplicability: true,
	Applicability:    &csp.Applicability{OsBuildVersions: []string{"10.0.10586"}, CspVersion: "1.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x62", "0x63", "0x64", "0x65", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
	Children: []*csp.Node{
		&csp.Node{
			Name: "Lock", URI: "./Device/Vendor/MSFT/RemoteLock/Lock", Format: "null",
			Access:      []csp.Access{"Exec", "Get"},
			Description: "Required. The setting accepts requests to lock the device screen. The device screen will lock immediately if a PIN has been set. If no PIN is set, the lock request is ignored and the OMA DM (405) Forbidden error is returned over the management channel. All OMA DM errors are listed here in the protocol specification",
			Occurrence:  "One",
			Permanent:   true,
		},
		&csp.Node{
			Name: "LockAndResetPIN", URI: "./Device/Vendor/MSFT/RemoteLock/LockAndResetPIN", Format: "null",
			Access:      []csp.Access{"Exec", "Get"},
			Description: "This setting can be used to lock and reset the PIN on the device. It is used in conjunction with the NewPINValue node. After the Exec operation is called successfully on this node, the previous PIN will no longer work and cannot be recovered.",
			Occurrence:  "One",
			Permanent:   true,
		},
		&csp.Node{
			Name: "LockAndRecoverPIN", URI: "./Device/Vendor/MSFT/RemoteLock/LockAndRecoverPIN", Format: "null",
			Access:           []csp.Access{"Exec", "Get"},
			Description:      "This setting performs a similar function to the LockAndResetPIN node. With LockAndResetPIN any Windows Hello keys associated with the PIN gets deleted, but with LockAndRecoverPIN those keys are saved. After the Exec operation is called successfully on this setting, the new PIN can be retrieved from the NewPINValue setting. The previous PIN will no longer work. Executing this node requires a ticket from the Microsoft credential reset service. Additionally, the execution of this setting is only supported when the EnablePinRecovery policy is set on the client.",
			Occurrence:       "One",
			Permanent:        true,
			OwnApplicability: true,
			Applicability:    &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "1.0", EditionAllowList: nil, RequiresAzureAd: false},
		},
		&csp.Node{
			Name: "NewPINValue", URI: "./Device/Vendor/MSFT/RemoteLock/NewPINValue", Format: "chr",
			Access:      []csp.Access{"Get"},
			Description: "This setting contains the PIN after Exec has been called on /RemoteLock/LockAndResetPIN or /RemoteLock/LockAndRecoverPin. If LockAndResetPIN or LockAndResetPIN has never been called, the value will be null. If Get is called on this node after a successful Exec call on /RemoteLock/LockAndResetPIN or /RemoteLock/LockAndRecoverPin, then the new PIN will be provided. If another Get command is called on this node, the value will be null. If you need to reset the PIN again, then another LockAndResetPIN Exec can be communicated to the device to generate a new PIN. The PIN value will conform to the minimum PIN complexity requirements of the merged policies that are set on the device. If no PIN policy has been set on the device, the generated PIN will conform to the default policy of the device. A Get operation on this node must follow an Exec operation on the /RemoteLock/LockAndResetPIN or /RemoteLock/LockAndRecoverPin node in the proper order and in the same SyncML message. The Sequence tag can be used to guarantee the order in which commands are processed.",
			Occurrence:  "One",
			Permanent:   true,
		},
	},
}})

// Trees lists every root of RemoteLock in this package.
var Trees = []*csp.Tree{Tree}
