// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package remotelock

// Root is the Device root of RemoteLock.
const Root = "./Device/Vendor/MSFT/RemoteLock"

// Lock is ./Device/Vendor/MSFT/RemoteLock/Lock.
// Required.
const Lock = "./Device/Vendor/MSFT/RemoteLock/Lock"

// LockAndResetPIN is ./Device/Vendor/MSFT/RemoteLock/LockAndResetPIN.
// This setting can be used to lock and reset the PIN on the device.
const LockAndResetPIN = "./Device/Vendor/MSFT/RemoteLock/LockAndResetPIN"

// LockAndRecoverPIN is ./Device/Vendor/MSFT/RemoteLock/LockAndRecoverPIN.
// This setting performs a similar function to the LockAndResetPIN node.
const LockAndRecoverPIN = "./Device/Vendor/MSFT/RemoteLock/LockAndRecoverPIN"

// NewPINValue is ./Device/Vendor/MSFT/RemoteLock/NewPINValue.
// This setting contains the PIN after Exec has been called on /RemoteLock/LockAndResetPIN or /RemoteLock/LockAndRecoverPin.
const NewPINValue = "./Device/Vendor/MSFT/RemoteLock/NewPINValue"
