// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package cellular

// LetAppsAccessCellularData values (ENUM).
const (
	// User is in control
	LetAppsAccessCellularDataUserIsInControl = "0"
	// Force Allow
	LetAppsAccessCellularDataForceAllow = "1"
	// Force Deny
	LetAppsAccessCellularDataForceDeny = "2"
)
