// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package dnsclient

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/DnsClient.
var Tree = csp.Inherit(&csp.Tree{Name: "DnsClient", File: "DnsClient.xml", Scope: "Device", PolicyArea: false, Root: &csp.Node{
	Name: "DnsClient", URI: "./Device/Vendor/MSFT/DnsClient", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	Children: []*csp.Node{
		&csp.Node{
			Name: "LinkLocal", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal", Format: "node",
			Access:     []csp.Access{"Get"},
			Occurrence: "One",
			Permanent:  true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "NetBIOS", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/NetBIOS", Format: "node",
					Access:     []csp.Access{"Get"},
					Occurrence: "One",
					Permanent:  true,
					Children: []*csp.Node{
						&csp.Node{
							Name: "Enable", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/NetBIOS/Enable", Format: "int",
							Title:         "Enable NetBIOS",
							Access:        []csp.Access{"Get", "Replace"},
							Description:   "NetBIOS can be fully disabled, disabled only on public networks, enabled in learning mode, or  enabled entirely. By default, it runs in Learning Mode.",
							Occurrence:    "One",
							Permanent:     true,
							AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Disable NetBIOS"}, {Value: "1", Description: "Allow NetBIOS"}, {Value: "2", Description: "Disable NetBIOS on Public Networks"}, {Value: "3", Description: "Run NetBIOS in Learning Mode"}}, ADMX: nil, ListDelimiter: ""},
						},
						&csp.Node{
							Name: "AllowFQDN", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/NetBIOS/AllowFQDN", Format: "bool",
							Title:      "Allow FQDN NetBIOS Lookups",
							Access:     []csp.Access{"Get", "Replace"},
							Occurrence: "One",
							Permanent:  true,
						},
					},
				},
				&csp.Node{
					Name: "LLMNR", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/LLMNR", Format: "node",
					Title:       "Link-Local Multicast Name Resolution",
					Access:      []csp.Access{"Get"},
					Description: "LLMNR (Link Local Multicast Name Resolution) is a legacy protocol for local device lookup.",
					Occurrence:  "One",
					Permanent:   true,
					Children: []*csp.Node{
						&csp.Node{
							Name: "Enabled", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/LLMNR/Enabled", Format: "bool",
							Access:     []csp.Access{"Get", "Replace"},
							Occurrence: "One",
							Permanent:  true,
						},
					},
				},
				&csp.Node{
					Name: "mDNS", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/mDNS", Format: "node",
					Title:      "Multicast DNS",
					Access:     []csp.Access{"Get"},
					Occurrence: "One",
					Permanent:  true,
					Children: []*csp.Node{
						&csp.Node{
							Name: "Enabled", URI: "./Device/Vendor/MSFT/DnsClient/LinkLocal/mDNS/Enabled", Format: "bool",
							Access:     []csp.Access{"Get", "Replace"},
							Occurrence: "One",
							Permanent:  true,
						},
					},
				},
			},
		},
		&csp.Node{
			Name: "DynamicDNS", URI: "./Device/Vendor/MSFT/DnsClient/DynamicDNS", Format: "node",
			Access:     []csp.Access{"Get"},
			Occurrence: "One",
			Permanent:  true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "Enabled", URI: "./Device/Vendor/MSFT/DnsClient/DynamicDNS/Enabled", Format: "bool",
					Title:      "Enable DDNS",
					Access:     []csp.Access{"Get", "Replace"},
					Occurrence: "One",
					Permanent:  true,
				},
				&csp.Node{
					Name: "Overwrite", URI: "./Device/Vendor/MSFT/DnsClient/DynamicDNS/Overwrite", Format: "bool",
					Access:     []csp.Access{"Get", "Replace"},
					Occurrence: "One",
					Permanent:  true,
				},
			},
		},
		&csp.Node{
			Name: "Encryption", URI: "./Device/Vendor/MSFT/DnsClient/Encryption", Format: "node",
			Access:      []csp.Access{"Get"},
			Description: "Encrypted transport options for securing DNS traffic.",
			Occurrence:  "One",
			Permanent:   true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "DoH", URI: "./Device/Vendor/MSFT/DnsClient/Encryption/DoH", Format: "node",
					Access:      []csp.Access{"Get"},
					Description: "DNS over HTTPS",
					Occurrence:  "One",
					Permanent:   true,
					Children: []*csp.Node{
						&csp.Node{
							Name: "Status", URI: "./Device/Vendor/MSFT/DnsClient/Encryption/DoH/Status", Format: "int",
							Access:        []csp.Access{"Get", "Replace"},
							Description:   "Set if the DNS client is allowed to make DNS queries over HTTPS. The default state is to allow these queries.",
							Default:       "0",
							Occurrence:    "One",
							Permanent:     true,
							AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Allowed"}, {Value: "1", Description: "Blocked"}}, ADMX: nil, ListDelimiter: ""},
						},
					},
				},
				&csp.Node{
					Name: "DoT", URI: "./Device/Vendor/MSFT/DnsClient/Encryption/DoT", Format: "node",
					Access:      []csp.Access{"Get"},
					Description: "DNS over TLS",
					Occurrence:  "One",
					Permanent:   true,
					Children: []*csp.Node{
						&csp.Node{
							Name: "Status", URI: "./Device/Vendor/MSFT/DnsClient/Encryption/DoT/Status", Format: "int",
							Access:        []csp.Access{"Get", "Replace"},
							Description:   "Set if the DNS client is allowed to make DNS queries over TLS. The default state is to allow these queries.",
							Default:       "0",
							Occurrence:    "One",
							Permanent:     true,
							AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Allowed"}, {Value: "1", Description: "Blocked"}}, ADMX: nil, ListDelimiter: ""},
						},
					},
				},
				&csp.Node{
					Name: "Status", URI: "./Device/Vendor/MSFT/DnsClient/Encryption/Status", Format: "int",
					Access:        []csp.Access{"Get", "Replace"},
					Description:   "Define the system-wide status of encrypted DNS. Disabled will block any attempts at DoH or DoT through the client, Allowed offers both unencrypted requests, as well as encrypted requests when possible, and Enforced blocks any lookups that would be sent via an unencrypted configuration. The default value is",
					Occurrence:    "One",
					Permanent:     true,
					AllowedValues: &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Unconfigured"}, {Value: "1", Description: "Disabled"}, {Value: "2", Description: "Allowed"}, {Value: "3", Description: "Enforced"}}, ADMX: nil, ListDelimiter: ""},
				},
			},
		},
		&csp.Node{
			Name: "IDN", URI: "./Device/Vendor/MSFT/DnsClient/IDN", Format: "node",
			Access:     []csp.Access{"Get"},
			Occurrence: "One",
			Permanent:  true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "Encoded", URI: "./Device/Vendor/MSFT/DnsClient/IDN/Encoded", Format: "bool",
					Access:     []csp.Access{"Get", "Replace"},
					Occurrence: "One",
					Permanent:  true,
				},
				&csp.Node{
					Name: "Mapped", URI: "./Device/Vendor/MSFT/DnsClient/IDN/Mapped", Format: "bool",
					Access:     []csp.Access{"Get", "Replace"},
					Occurrence: "One",
					Permanent:  true,
				},
			},
		},
		&csp.Node{
			Name: "NRPT", URI: "./Device/Vendor/MSFT/DnsClient/NRPT", Format: "node",
			Title:          "Name Resolution Policy Table",
			Access:         []csp.Access{"Get"},
			Description:    "Contains entries identifying which DNS server should be used for requests applying to specific domains.",
			Occurrence:     "One",
			Permanent:      true,
			AtomicRequired: true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "", URI: "./Device/Vendor/MSFT/DnsClient/NRPT/{Policy Table Entry}", Format: "node",
					Title:              "Policy Table Entry",
					Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
					Description:        "A row in the name resolution policy table.",
					Occurrence:         "ZeroOrMore",
					Dynamic:            true,
					Naming:             csp.Naming{Kind: "UniqueName", Pattern: "Numerical identifier, in order."},
					AllowedValues:      &csp.AllowedValues{Type: "RegEx", Value: "", Enum: nil, ADMX: nil, ListDelimiter: ""},
					ConflictResolution: "LastWrite",
					AtomicRequired:     true,
					Children: []*csp.Node{
						&csp.Node{
							Name: "Namespace", URI: "./Device/Vendor/MSFT/DnsClient/NRPT/{Policy Table Entry}/Namespace", Format: "chr",
							Title:          "Entry namespace",
							Access:         []csp.Access{"Get", "Replace"},
							Description:    "The domain name being routed under this policy. Depending on the NamespaceType value, this may be any one of: FQDN, domain suffix, hostname (of any given domain), or IPv4 or IPv6 subnet.",
							Occurrence:     "One",
							AtomicRequired: true,
						},
						&csp.Node{
							Name: "NamespaceType", URI: "./Device/Vendor/MSFT/DnsClient/NRPT/{Policy Table Entry}/NamespaceType", Format: "chr",
							Access:         []csp.Access{"Get", "Replace"},
							Description:    "The type of the namespace declared by this table entry. This defines the scope that this policy applies to.",
							Occurrence:     "One",
							AllowedValues:  &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "FQDN", Description: "Fully-qualified domain name of a specific host"}, {Value: "Suffix", Description: "A domain name consisting of one or more labels. Defines a scope consisting of all hosts and subdomains of the given domain."}, {Value: "Prefix", Description: "A specific hostname, on any given domain."}, {Value: "v4Subnet", Description: "An IPv4 subnet for reverse lookup"}, {Value: "v6Subnet", Description: "An IPv6 subnet for reverse lookup"}}, ADMX: nil, ListDelimiter: ""},
							AtomicRequired: true,
						},
						&csp.Node{
							Name: "DNSServers", URI: "./Device/Vendor/MSFT/DnsClient/NRPT/{Policy Table Entry}/DNSServers", Format: "chr",
							Title:          "DNS Servers",
							Access:         []csp.Access{"Get", "Replace"},
							Description:    "Space-separated list of IP addresses of DNS server(s) used to resolve names that match this policy.",
							Occurrence:     "One",
							AtomicRequired: true,
						},
					},
				},
			},
		},
	},
}})

// Trees lists every root of DnsClient in this package.
var Trees = []*csp.Tree{Tree}
