// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package experience

// DeviceRoot is the Device root of Experience.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/Experience"

// DeviceAllowCopyPaste is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowCopyPaste.
// This policy is deprecated.
const DeviceAllowCopyPaste = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowCopyPaste"

// DeviceAllowCortana is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowCortana.
// Specifies whether Cortana is allowed on the device.
const DeviceAllowCortana = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowCortana"

// DeviceAllowDeviceDiscovery is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowDeviceDiscovery.
// Allows users to turn on/off device discovery UX.
const DeviceAllowDeviceDiscovery = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowDeviceDiscovery"

// DeviceAllowManualMDMUnenrollment is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowManualMDMUnenrollment.
// Specifies whether to allow the user to delete the workplace account using the workplace control panel.
const DeviceAllowManualMDMUnenrollment = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowManualMDMUnenrollment"

// DeviceAllowSaveAsOfOfficeFiles is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowSaveAsOfOfficeFiles.
// This policy is deprecated.
const DeviceAllowSaveAsOfOfficeFiles = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSaveAsOfOfficeFiles"

// DeviceAllowScreenCapture is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowScreenCapture.
// Allow screen capture
const DeviceAllowScreenCapture = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowScreenCapture"

// DeviceAllowSharingOfOfficeFiles is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowSharingOfOfficeFiles.
// This policy is deprecated.
const DeviceAllowSharingOfOfficeFiles = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSharingOfOfficeFiles"

// DeviceAllowSIMErrorDialogPromptWhenNoSIM is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowSIMErrorDialogPromptWhenNoSIM.
// Allow SIM error diaglog prompts when no SIM is inserted.
const DeviceAllowSIMErrorDialogPromptWhenNoSIM = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSIMErrorDialogPromptWhenNoSIM"

// DeviceAllowSyncMySettings is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowSyncMySettings.
// Allows or disallows all Windows sync settings on the device.
const DeviceAllowSyncMySettings = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowSyncMySettings"

// DeviceAllowTaskSwitcher is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowTaskSwitcher.
// This policy is deprecated.
const DeviceAllowTaskSwitcher = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowTaskSwitcher"

// DeviceAllowVoiceRecording is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowVoiceRecording.
// This policy is deprecated.
const DeviceAllowVoiceRecording = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowVoiceRecording"

// DeviceAllowWindowsConsumerFeatures is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsConsumerFeatures.
// Prior to Windows 10, version 1803, this policy had User scope.
const DeviceAllowWindowsConsumerFeatures = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsConsumerFeatures"

// DeviceAllowWindowsTips is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsTips.
// Enables or disables Windows Tips / soft landing.
const DeviceAllowWindowsTips = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsTips"

// DeviceDisableTextTranslation is ./Device/Vendor/MSFT/Policy/Config/Experience/DisableTextTranslation.
// Allows Text Translation feature to be enabled/disabled.
const DeviceDisableTextTranslation = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableTextTranslation"

// DeviceDoNotShowFeedbackNotifications is ./Device/Vendor/MSFT/Policy/Config/Experience/DoNotShowFeedbackNotifications.
// Prevents devices from showing feedback questions from Microsoft.
const DeviceDoNotShowFeedbackNotifications = "./Device/Vendor/MSFT/Policy/Config/Experience/DoNotShowFeedbackNotifications"

// DeviceAllowFindMyDevice is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowFindMyDevice.
// This policy turns on Find My Device.
const DeviceAllowFindMyDevice = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowFindMyDevice"

// DeviceAllowClipboardHistory is ./Device/Vendor/MSFT/Policy/Config/Experience/AllowClipboardHistory.
// Allows history of clipboard items to be stored in memory.
const DeviceAllowClipboardHistory = "./Device/Vendor/MSFT/Policy/Config/Experience/AllowClipboardHistory"

// DeviceDoNotSyncBrowserSettings is ./Device/Vendor/MSFT/Policy/Config/Experience/DoNotSyncBrowserSettings.
// You can configure Microsoft Edge, when enabled, to prevent the "browser" group from using the Sync your Settings option to sync information, such as history and favorites, between user's devices.
const DeviceDoNotSyncBrowserSettings = "./Device/Vendor/MSFT/Policy/Config/Experience/DoNotSyncBrowserSettings"

// DevicePreventUsersFromTurningOnBrowserSyncing is ./Device/Vendor/MSFT/Policy/Config/Experience/PreventUsersFromTurningOnBrowserSyncing.
// You can configure Microsoft Edge to allow users to turn on the Sync your Settings option to sync information, such as history and favorites, between user's devices.
const DevicePreventUsersFromTurningOnBrowserSyncing = "./Device/Vendor/MSFT/Policy/Config/Experience/PreventUsersFromTurningOnBrowserSyncing"

// DeviceShowLockOnUserTile is ./Device/Vendor/MSFT/Policy/Config/Experience/ShowLockOnUserTile.
// Shows or hides lock from the user tile menu.
const DeviceShowLockOnUserTile = "./Device/Vendor/MSFT/Policy/Config/Experience/ShowLockOnUserTile"

// DeviceDisableCloudOptimizedContent is ./Device/Vendor/MSFT/Policy/Config/Experience/DisableCloudOptimizedContent.
// This policy controls Windows experiences that use the cloud optimized content client component.
const DeviceDisableCloudOptimizedContent = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableCloudOptimizedContent"

// DeviceDisableConsumerAccountStateContent is ./Device/Vendor/MSFT/Policy/Config/Experience/DisableConsumerAccountStateContent.
// This policy controls Windows experiences that use the cloud consumer account state content client component.
const DeviceDisableConsumerAccountStateContent = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableConsumerAccountStateContent"

// DeviceConfigureChatIcon is ./Device/Vendor/MSFT/Policy/Config/Experience/ConfigureChatIcon.
// This policy is deprecated
const DeviceConfigureChatIcon = "./Device/Vendor/MSFT/Policy/Config/Experience/ConfigureChatIcon"

// DeviceDisableShareAppPromotions is ./Device/Vendor/MSFT/Policy/Config/Experience/DisableShareAppPromotions.
// This policy setting allow IT admins to control whether promotional apps are displayed in the Share sheet.
const DeviceDisableShareAppPromotions = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableShareAppPromotions"

// DeviceDisableInlineCompose is ./Device/Vendor/MSFT/Policy/Config/Experience/DisableInlineCompose.
// This policy controls whether users can compose a message directly in the Share sheet after selecting Outlook.
const DeviceDisableInlineCompose = "./Device/Vendor/MSFT/Policy/Config/Experience/DisableInlineCompose"

// UserRoot is the User root of Experience.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/Experience"

// UserAllowScreenRecorder is ./User/Vendor/MSFT/Policy/Config/Experience/AllowScreenRecorder.
// This policy setting allows you to control whether screen recording functionality is available in the Windows Snipping Tool app.
const UserAllowScreenRecorder = "./User/Vendor/MSFT/Policy/Config/Experience/AllowScreenRecorder"

// UserAllowSpotlightCollection is ./User/Vendor/MSFT/Policy/Config/Experience/AllowSpotlightCollection.
// Specifies whether Spotlight collection is allowed as a Personalization->Background Setting.
const UserAllowSpotlightCollection = "./User/Vendor/MSFT/Policy/Config/Experience/AllowSpotlightCollection"

// UserAllowThirdPartySuggestionsInWindowsSpotlight is ./User/Vendor/MSFT/Policy/Config/Experience/AllowThirdPartySuggestionsInWindowsSpotlight.
// Specifies whether to allow app and content suggestions from third-party software publishers in Windows spotlight features like lock screen spotlight, suggested apps in the Start menu, and Windows tips...
const UserAllowThirdPartySuggestionsInWindowsSpotlight = "./User/Vendor/MSFT/Policy/Config/Experience/AllowThirdPartySuggestionsInWindowsSpotlight"

// UserAllowWindowsSpotlight is ./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlight.
// Specifies whether to turn off all Windows spotlight features at once.
const UserAllowWindowsSpotlight = "./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlight"

// UserAllowWindowsSpotlightOnActionCenter is ./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlightOnActionCenter.
// This policy allows administrators to prevent Windows spotlight notifications from being displayed in the Action Center.
const UserAllowWindowsSpotlightOnActionCenter = "./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlightOnActionCenter"

// UserAllowWindowsSpotlightOnSettings is ./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlightOnSettings.
// This policy allows IT admins to turn off Suggestions in Settings app.
const UserAllowWindowsSpotlightOnSettings = "./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlightOnSettings"

// UserAllowWindowsSpotlightWindowsWelcomeExperience is ./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlightWindowsWelcomeExperience.
// This policy setting lets you turn off the Windows spotlight Windows welcome experience feature.
const UserAllowWindowsSpotlightWindowsWelcomeExperience = "./User/Vendor/MSFT/Policy/Config/Experience/AllowWindowsSpotlightWindowsWelcomeExperience"

// UserAllowTailoredExperiencesWithDiagnosticData is ./User/Vendor/MSFT/Policy/Config/Experience/AllowTailoredExperiencesWithDiagnosticData.
// This policy allows you to prevent Windows from using diagnostic data to provide customized experiences to the user.
const UserAllowTailoredExperiencesWithDiagnosticData = "./User/Vendor/MSFT/Policy/Config/Experience/AllowTailoredExperiencesWithDiagnosticData"

// UserConfigureWindowsSpotlightOnLockScreen is ./User/Vendor/MSFT/Policy/Config/Experience/ConfigureWindowsSpotlightOnLockScreen.
// Allows IT admins to specify whether spotlight should be used on the user's lock screen.
const UserConfigureWindowsSpotlightOnLockScreen = "./User/Vendor/MSFT/Policy/Config/Experience/ConfigureWindowsSpotlightOnLockScreen"

// UserEnableOrganizationalMessages is ./User/Vendor/MSFT/Policy/Config/Experience/EnableOrganizationalMessages.
// Organizational messages allow Administrators to deliver messages to their end users on selected Windows 11 experiences.
const UserEnableOrganizationalMessages = "./User/Vendor/MSFT/Policy/Config/Experience/EnableOrganizationalMessages"
