// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxmsi

// DeviceRoot is the Device root of ADMX_MSI.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI"

// DeviceAllowLockdownBrowse is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownBrowse.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownBrowse
const DeviceAllowLockdownBrowse = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownBrowse"

// DeviceAllowLockdownPatch is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownPatch.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownPatch
const DeviceAllowLockdownPatch = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownPatch"

// DeviceAllowLockdownMedia is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownMedia.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownMedia
const DeviceAllowLockdownMedia = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/AllowLockdownMedia"

// DeviceMSIMaxPatchCacheSize is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_MaxPatchCacheSize.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_MaxPatchCacheSize
const DeviceMSIMaxPatchCacheSize = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_MaxPatchCacheSize"

// DeviceMSIEnforceUpgradeComponentRules is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_EnforceUpgradeComponentRules.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_EnforceUpgradeComponentRules
const DeviceMSIEnforceUpgradeComponentRules = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_EnforceUpgradeComponentRules"

// DeviceMsiDisableEmbeddedUI is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MsiDisableEmbeddedUI.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MsiDisableEmbeddedUI
const DeviceMsiDisableEmbeddedUI = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MsiDisableEmbeddedUI"

// DeviceSafeForScripting is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/SafeForScripting.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/SafeForScripting
const DeviceSafeForScripting = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/SafeForScripting"

// DeviceDisablePatch is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisablePatch.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisablePatch
const DeviceDisablePatch = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisablePatch"

// DeviceDisableFlyweightPatching is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableFlyweightPatching.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableFlyweightPatching
const DeviceDisableFlyweightPatching = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableFlyweightPatching"

// DeviceMSIDisableLUAPatching is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableLUAPatching.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableLUAPatching
const DeviceMSIDisableLUAPatching = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableLUAPatching"

// DeviceMSIDisablePatchUninstall is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisablePatchUninstall.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisablePatchUninstall
const DeviceMSIDisablePatchUninstall = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisablePatchUninstall"

// DeviceDisableRollback2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableRollback_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableRollback_2
const DeviceDisableRollback2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableRollback_2"

// DeviceDisableAutomaticApplicationShutdown is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableAutomaticApplicationShutdown.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableAutomaticApplicationShutdown
const DeviceDisableAutomaticApplicationShutdown = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableAutomaticApplicationShutdown"

// DeviceMSIDisableUserInstalls is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableUserInstalls.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableUserInstalls
const DeviceMSIDisableUserInstalls = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableUserInstalls"

// DeviceDisableBrowse is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableBrowse.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableBrowse
const DeviceDisableBrowse = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableBrowse"

// DeviceTransformsSecure is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/TransformsSecure.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/TransformsSecure
const DeviceTransformsSecure = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/TransformsSecure"

// DeviceMSILogging is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSILogging.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSILogging
const DeviceMSILogging = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSILogging"

// DeviceMSIDisableSRCheckPoints is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableSRCheckPoints.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableSRCheckPoints
const DeviceMSIDisableSRCheckPoints = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/MSI_DisableSRCheckPoints"

// DeviceDisableLoggingFromPackage is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableLoggingFromPackage.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableLoggingFromPackage
const DeviceDisableLoggingFromPackage = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableLoggingFromPackage"

// DeviceDisableSharedComponent is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableSharedComponent.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableSharedComponent
const DeviceDisableSharedComponent = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableSharedComponent"

// DeviceDisableMSI is ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableMSI.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableMSI
const DeviceDisableMSI = "./Device/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableMSI"

// UserRoot is the User root of ADMX_MSI.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_MSI"

// UserDisableMedia is ./User/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableMedia.
// ./User/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableMedia
const UserDisableMedia = "./User/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableMedia"

// UserDisableRollback1 is ./User/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableRollback_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableRollback_1
const UserDisableRollback1 = "./User/Vendor/MSFT/Policy/Config/ADMX_MSI/DisableRollback_1"

// UserSearchOrder is ./User/Vendor/MSFT/Policy/Config/ADMX_MSI/SearchOrder.
// ./User/Vendor/MSFT/Policy/Config/ADMX_MSI/SearchOrder
const UserSearchOrder = "./User/Vendor/MSFT/Policy/Config/ADMX_MSI/SearchOrder"
