// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package desktop

// Root is the User root of Desktop.
const Root = "./User/Vendor/MSFT/Policy/Config/Desktop"

// PreventUserRedirectionOfProfileFolders is ./User/Vendor/MSFT/Policy/Config/Desktop/PreventUserRedirectionOfProfileFolders.
// ./User/Vendor/MSFT/Policy/Config/Desktop/PreventUserRedirectionOfProfileFolders
const PreventUserRedirectionOfProfileFolders = "./User/Vendor/MSFT/Policy/Config/Desktop/PreventUserRedirectionOfProfileFolders"
