// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxsoundrec

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// DeviceTree is the Device root ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec.
var DeviceTree = csp.Inherit(&csp.Tree{Name: "ADMX_SoundRec", File: "ADMX_SoundRec_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "ADMX_SoundRec", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "Soundrec_DiableApplication_TitleText_2", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "SoundRec~AT~WindowsComponents~Soundrec_GroupPolicyCategory", Name: "Soundrec_DiableApplication_TitleText_2", File: "SoundRec.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// UserTree is the User root ./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec.
var UserTree = csp.Inherit(&csp.Tree{Name: "ADMX_SoundRec", File: "ADMX_SoundRec_AreaDDF.xml", Scope: "User", PolicyArea: true, Root: &csp.Node{
	Name: "ADMX_SoundRec", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "Soundrec_DiableApplication_TitleText_1", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_1", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "SoundRec~AT~WindowsComponents~Soundrec_GroupPolicyCategory", Name: "Soundrec_DiableApplication_TitleText_1", File: "SoundRec.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of ADMX_SoundRec in this package.
var Trees = []*csp.Tree{DeviceTree, UserTree}
