// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxsoundrec

// DeviceRoot is the Device root of ADMX_SoundRec.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec"

// DeviceSoundrecDiableApplicationTitleText2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2
const DeviceSoundrecDiableApplicationTitleText2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_2"

// UserRoot is the User root of ADMX_SoundRec.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec"

// UserSoundrecDiableApplicationTitleText1 is ./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_1
const UserSoundrecDiableApplicationTitleText1 = "./User/Vendor/MSFT/Policy/Config/ADMX_SoundRec/Soundrec_DiableApplication_TitleText_1"
