// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package power

// SelectPowerButtonActionPluggedIn values (ENUM).
const (
	// Take no action
	SelectPowerButtonActionPluggedInTakeNoAction = "0"
	// Sleep
	SelectPowerButtonActionPluggedInSleep = "1"
	// System hibernate sleep state
	SelectPowerButtonActionPluggedInSystemHibernateSleepState = "2"
	// System shutdown
	SelectPowerButtonActionPluggedInSystemShutdown = "3"
)

// SelectPowerButtonActionOnBattery values (ENUM).
const (
	// Take no action
	SelectPowerButtonActionOnBatteryTakeNoAction = "0"
	// Sleep
	SelectPowerButtonActionOnBatterySleep = "1"
	// System hibernate sleep state
	SelectPowerButtonActionOnBatterySystemHibernateSleepState = "2"
	// System shutdown
	SelectPowerButtonActionOnBatterySystemShutdown = "3"
)

// SelectSleepButtonActionPluggedIn values (ENUM).
const (
	// Take no action
	SelectSleepButtonActionPluggedInTakeNoAction = "0"
	// Sleep
	SelectSleepButtonActionPluggedInSleep = "1"
	// System hibernate sleep state
	SelectSleepButtonActionPluggedInSystemHibernateSleepState = "2"
	// System shutdown
	SelectSleepButtonActionPluggedInSystemShutdown = "3"
)

// SelectSleepButtonActionOnBattery values (ENUM).
const (
	// Take no action
	SelectSleepButtonActionOnBatteryTakeNoAction = "0"
	// Sleep
	SelectSleepButtonActionOnBatterySleep = "1"
	// System hibernate sleep state
	SelectSleepButtonActionOnBatterySystemHibernateSleepState = "2"
	// System shutdown
	SelectSleepButtonActionOnBatterySystemShutdown = "3"
)

// SelectLidCloseActionPluggedIn values (ENUM).
const (
	// Take no action
	SelectLidCloseActionPluggedInTakeNoAction = "0"
	// Sleep
	SelectLidCloseActionPluggedInSleep = "1"
	// System hibernate sleep state
	SelectLidCloseActionPluggedInSystemHibernateSleepState = "2"
	// System shutdown
	SelectLidCloseActionPluggedInSystemShutdown = "3"
)

// SelectLidCloseActionOnBattery values (ENUM).
const (
	// Take no action
	SelectLidCloseActionOnBatteryTakeNoAction = "0"
	// Sleep
	SelectLidCloseActionOnBatterySleep = "1"
	// System hibernate sleep state
	SelectLidCloseActionOnBatterySystemHibernateSleepState = "2"
	// System shutdown
	SelectLidCloseActionOnBatterySystemShutdown = "3"
)

// TurnOffHybridSleepPluggedIn values (ENUM).
const (
	TurnOffHybridSleepPluggedInValue0 = "0"
	// hybrid sleep
	TurnOffHybridSleepPluggedInHybridSleep = "1"
)

// TurnOffHybridSleepOnBattery values (ENUM).
const (
	TurnOffHybridSleepOnBatteryValue0 = "0"
	// hybrid sleep
	TurnOffHybridSleepOnBatteryHybridSleep = "1"
)

// AllowHibernate values (ENUM).
const (
	// Disable hibernate.
	AllowHibernateDisableHibernate = "0"
	// Allow hibernate.
	AllowHibernateAllowHibernate = "1"
)

// EnableEnergySaver values (ENUM).
const (
	// Disable energy saver policy
	EnableEnergySaverDisableEnergySaverPolicy = "0"
	// Enable energy saver always-on mode.
	EnableEnergySaverEnableEnergySaverAlways = "1"
)
