// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package troubleshooting

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/Troubleshooting.
var Tree = csp.Inherit(&csp.Tree{Name: "Troubleshooting", File: "Troubleshooting_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "Troubleshooting", URI: "./Device/Vendor/MSFT/Policy/Config/Troubleshooting", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AllowRecommendations", URI: "./Device/Vendor/MSFT/Policy/Config/Troubleshooting/AllowRecommendations", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy setting allows IT admins to configure how troubleshooting for known problems can be applied on the devices in their domains or IT environments. Supported values: 0 = Off - Do not allow users, system features, or Microsoft to apply troubleshooting. 1 = Critical - Automatically apply troubleshooting for critical problems detected by system features and Microsoft. Do not notify users when troubleshooting has solved a problem. 2 = Prompt - Automatically apply troubleshooting for critical problems detected by system features and Microsoft. Prompt users when troubleshooting for other problems is available and allow the user to choose to apply or ignore. 3 = Notify - Automatically apply troubleshooting for critical and other problems detected by system features and Microsoft. Notify users when troubleshooting has solved a problem. 4 = Silent - Automatically apply troubleshooting for critical and other problems detected by system features and Microsoft. Do not notify users when troubleshooting has solved a problem. 5 = Configurable - Allow the user to choose their own troubleshooting settings.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.18362"}, CspVersion: "9.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Off - Do not allow users, system features, or Microsoft to apply troubleshooting."}, {Value: "1", Description: "Critical - Automatically apply troubleshooting for critical problems detected by system features and Microsoft. Do not notify users when troubleshooting has solved a problem."}, {Value: "2", Description: "Prompt - Automatically apply troubleshooting for critical problems detected by system features and Microsoft. Prompt users when troubleshooting for other problems is available and allow the user to choose to apply or ignore."}, {Value: "3", Description: "Notify - Automatically apply troubleshooting for critical and other problems detected by system features and Microsoft. Notify users when troubleshooting has solved a problem."}, {Value: "4", Description: "Silent - Automatically apply troubleshooting for critical and other problems detected by system features and Microsoft. Do not notify users when troubleshooting has solved a problem."}, {Value: "5", Description: "Configurable - Allow the user to choose their own troubleshooting settings."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "TroubleshootingAllowRecommendations", AreaPath: "MSDT~AT~System~Troubleshooting~WdiScenarioCategory", Element: ""},
			ConflictResolution: "LowestValueMostSecure",
		},
	},
}})

// Trees lists every root of Troubleshooting in this package.
var Trees = []*csp.Tree{Tree}
