// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxfilesys

// Root is the Device root of ADMX_FileSys.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys"

// DisableDeleteNotification is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableDeleteNotification.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableDeleteNotification
const DisableDeleteNotification = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableDeleteNotification"

// LongPathsEnabled is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/LongPathsEnabled.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/LongPathsEnabled
const LongPathsEnabled = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/LongPathsEnabled"

// DisableCompression is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableCompression.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableCompression
const DisableCompression = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableCompression"

// DisableEncryption is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableEncryption.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableEncryption
const DisableEncryption = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/DisableEncryption"

// TxfDeprecatedFunctionality is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/TxfDeprecatedFunctionality.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/TxfDeprecatedFunctionality
const TxfDeprecatedFunctionality = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/TxfDeprecatedFunctionality"

// EnablePagefileEncryption is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/EnablePagefileEncryption.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/EnablePagefileEncryption
const EnablePagefileEncryption = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/EnablePagefileEncryption"

// ShortNameCreationSettings is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/ShortNameCreationSettings.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/ShortNameCreationSettings
const ShortNameCreationSettings = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/ShortNameCreationSettings"

// SymlinkEvaluation is ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/SymlinkEvaluation.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/SymlinkEvaluation
const SymlinkEvaluation = "./Device/Vendor/MSFT/Policy/Config/ADMX_FileSys/SymlinkEvaluation"
