// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package clientcertificateinstall

import "net/url"

// DeviceRoot is the Device root of ClientCertificateInstall.
const DeviceRoot = "./Device/Vendor/MSFT/ClientCertificateInstall"

// DevicePFXCertInstall is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall.
// Required for PFX certificate installation.
const DevicePFXCertInstall = "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall"

// DevicePFXCertInstallUniqueID is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}.
// Required for PFX certificate installation.
func DevicePFXCertInstallUniqueID(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID)
}

// DevicePFXCertInstallKeyLocation is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/KeyLocation.
// Required for PFX certificate installation.
func DevicePFXCertInstallKeyLocation(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/KeyLocation"
}

// DevicePFXCertInstallContainerName is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/ContainerName.
// Optional.
func DevicePFXCertInstallContainerName(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/ContainerName"
}

// DevicePFXCertInstallPFXCertBlob is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertBlob.
// Required.
func DevicePFXCertInstallPFXCertBlob(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertBlob"
}

// DevicePFXCertInstallPFXCertPassword is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertPassword.
// Password that protects the PFX blob.
func DevicePFXCertInstallPFXCertPassword(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertPassword"
}

// DevicePFXCertInstallPFXCertPasswordEncryptionType is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertPasswordEncryptionType.
// Optional.
func DevicePFXCertInstallPFXCertPasswordEncryptionType(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertPasswordEncryptionType"
}

// DevicePFXCertInstallPFXKeyExportable is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXKeyExportable.
// Optional.
func DevicePFXCertInstallPFXKeyExportable(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXKeyExportable"
}

// DevicePFXCertInstallThumbprint is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/Thumbprint.
// Returns the thumbprint of the PFX certificate installed.
func DevicePFXCertInstallThumbprint(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/Thumbprint"
}

// DevicePFXCertInstallStatus is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/Status.
// Returns the error code of the PFX installation from the GetLastError command called after the PfxImportCertStore.
func DevicePFXCertInstallStatus(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/Status"
}

// DevicePFXCertInstallPFXCertPasswordEncryptionStore is ./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertPasswordEncryptionStore.
// Optional.
func DevicePFXCertInstallPFXCertPasswordEncryptionStore(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertPasswordEncryptionStore"
}

// DeviceSCEP is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP.
// Node for SCEP.
const DeviceSCEP = "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP"

// DeviceSCEPUniqueID is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}.
// Required for SCEP certificate installation.
func DeviceSCEPUniqueID(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID)
}

// DeviceSCEPInstall is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install.
// Required for SCEP certificate enrollment.
func DeviceSCEPInstall(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install"
}

// DeviceSCEPInstallServerURL is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ServerURL.
// Required for SCEP certificate enrollment.
func DeviceSCEPInstallServerURL(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ServerURL"
}

// DeviceSCEPInstallChallenge is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/Challenge.
// Required for SCEP certificate enrollment.
func DeviceSCEPInstallChallenge(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/Challenge"
}

// DeviceSCEPInstallEKUMapping is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/EKUMapping.
// Required.
func DeviceSCEPInstallEKUMapping(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/EKUMapping"
}

// DeviceSCEPInstallKeyUsage is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/KeyUsage.
// Required for enrollment.
func DeviceSCEPInstallKeyUsage(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/KeyUsage"
}

// DeviceSCEPInstallAttestPrivateKey is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/AttestPrivateKey.
// Defines the attest SCEP private key behavior 0 - normal, 1 - best effort, 2 - on error, fail the installation
func DeviceSCEPInstallAttestPrivateKey(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/AttestPrivateKey"
}

// DeviceSCEPInstallSubjectName is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/SubjectName.
// Required.
func DeviceSCEPInstallSubjectName(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/SubjectName"
}

// DeviceSCEPInstallKeyProtection is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/KeyProtection.
// Optional.
func DeviceSCEPInstallKeyProtection(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/KeyProtection"
}

// DeviceSCEPInstallRetryDelay is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/RetryDelay.
// Optional.
func DeviceSCEPInstallRetryDelay(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/RetryDelay"
}

// DeviceSCEPInstallRetryCount is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/RetryCount.
// Optional.
func DeviceSCEPInstallRetryCount(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/RetryCount"
}

// DeviceSCEPInstallTemplateName is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/TemplateName.
// Optional.
func DeviceSCEPInstallTemplateName(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/TemplateName"
}

// DeviceSCEPInstallKeyLength is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/KeyLength.
// Required for enrollment.
func DeviceSCEPInstallKeyLength(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/KeyLength"
}

// DeviceSCEPInstallHashAlgorithm is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/HashAlgorithm.
// Required for enrollment.
func DeviceSCEPInstallHashAlgorithm(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/HashAlgorithm"
}

// DeviceSCEPInstallCAThumbprint is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/CAThumbprint.
// Required.
func DeviceSCEPInstallCAThumbprint(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/CAThumbprint"
}

// DeviceSCEPInstallSubjectAlternativeNames is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/SubjectAlternativeNames.
// Optional.
func DeviceSCEPInstallSubjectAlternativeNames(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/SubjectAlternativeNames"
}

// DeviceSCEPInstallValidPeriod is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ValidPeriod.
// Optional.
func DeviceSCEPInstallValidPeriod(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ValidPeriod"
}

// DeviceSCEPInstallValidPeriodUnits is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ValidPeriodUnits.
// Optional.
func DeviceSCEPInstallValidPeriodUnits(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ValidPeriodUnits"
}

// DeviceSCEPInstallContainerName is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ContainerName.
// Optional.
func DeviceSCEPInstallContainerName(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ContainerName"
}

// DeviceSCEPInstallCustomTextToShowInPrompt is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/CustomTextToShowInPrompt.
// Optional.
func DeviceSCEPInstallCustomTextToShowInPrompt(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/CustomTextToShowInPrompt"
}

// DeviceSCEPInstallEnroll is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/Enroll.
// Required.
func DeviceSCEPInstallEnroll(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/Enroll"
}

// DeviceSCEPInstallAADKeyIdentifierList is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/AADKeyIdentifierList.
// Optional.
func DeviceSCEPInstallAADKeyIdentifierList(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/AADKeyIdentifierList"
}

// DeviceSCEPCertThumbprint is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/CertThumbprint.
// Optional.
func DeviceSCEPCertThumbprint(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/CertThumbprint"
}

// DeviceSCEPStatus is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Status.
// Required.
func DeviceSCEPStatus(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Status"
}

// DeviceSCEPErrorCode is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/ErrorCode.
// Optional.
func DeviceSCEPErrorCode(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/ErrorCode"
}

// DeviceSCEPRespondentServerUrl is ./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/RespondentServerUrl.
// Required.
func DeviceSCEPRespondentServerUrl(uniqueID string) string {
	return "./Device/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/RespondentServerUrl"
}

// UserRoot is the User root of ClientCertificateInstall.
const UserRoot = "./User/Vendor/MSFT/ClientCertificateInstall"

// UserPFXCertInstall is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall.
// Required for PFX certificate installation.
const UserPFXCertInstall = "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall"

// UserPFXCertInstallUniqueID is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}.
// Required for PFX certificate installation.
func UserPFXCertInstallUniqueID(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID)
}

// UserPFXCertInstallKeyLocation is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/KeyLocation.
// Required for PFX certificate installation.
func UserPFXCertInstallKeyLocation(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/KeyLocation"
}

// UserPFXCertInstallContainerName is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/ContainerName.
// Optional.
func UserPFXCertInstallContainerName(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/ContainerName"
}

// UserPFXCertInstallPFXCertBlob is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertBlob.
// Required.
func UserPFXCertInstallPFXCertBlob(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertBlob"
}

// UserPFXCertInstallPFXCertPassword is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertPassword.
// Password that protects the PFX blob.
func UserPFXCertInstallPFXCertPassword(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertPassword"
}

// UserPFXCertInstallPFXCertPasswordEncryptionType is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertPasswordEncryptionType.
// Optional.
func UserPFXCertInstallPFXCertPasswordEncryptionType(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertPasswordEncryptionType"
}

// UserPFXCertInstallPFXKeyExportable is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXKeyExportable.
// Optional.
func UserPFXCertInstallPFXKeyExportable(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXKeyExportable"
}

// UserPFXCertInstallThumbprint is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/Thumbprint.
// Returns the thumbprint of the PFX certificate installed.
func UserPFXCertInstallThumbprint(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/Thumbprint"
}

// UserPFXCertInstallStatus is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/Status.
// Returns the error code of the PFX installation from the GetLastError command called after the PfxImportCertStore.
func UserPFXCertInstallStatus(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/Status"
}

// UserPFXCertInstallPFXCertPasswordEncryptionStore is ./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/{UniqueID}/PFXCertPasswordEncryptionStore.
// Optional.
func UserPFXCertInstallPFXCertPasswordEncryptionStore(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/PFXCertInstall/" + escape(uniqueID) + "/PFXCertPasswordEncryptionStore"
}

// UserSCEP is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP.
// Node for SCEP.
const UserSCEP = "./User/Vendor/MSFT/ClientCertificateInstall/SCEP"

// UserSCEPUniqueID is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}.
// Required for SCEP certificate installation.
func UserSCEPUniqueID(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID)
}

// UserSCEPInstall is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install.
// Required for SCEP certificate enrollment.
func UserSCEPInstall(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install"
}

// UserSCEPInstallServerURL is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ServerURL.
// Required for SCEP certificate enrollment.
func UserSCEPInstallServerURL(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ServerURL"
}

// UserSCEPInstallChallenge is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/Challenge.
// Required for SCEP certificate enrollment.
func UserSCEPInstallChallenge(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/Challenge"
}

// UserSCEPInstallEKUMapping is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/EKUMapping.
// Required.
func UserSCEPInstallEKUMapping(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/EKUMapping"
}

// UserSCEPInstallKeyUsage is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/KeyUsage.
// Required for enrollment.
func UserSCEPInstallKeyUsage(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/KeyUsage"
}

// UserSCEPInstallAttestPrivateKey is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/AttestPrivateKey.
// Defines the attest SCEP private key behavior 0 - normal, 1 - best effort, 2 - on error, fail the installation
func UserSCEPInstallAttestPrivateKey(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/AttestPrivateKey"
}

// UserSCEPInstallSubjectName is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/SubjectName.
// Required.
func UserSCEPInstallSubjectName(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/SubjectName"
}

// UserSCEPInstallKeyProtection is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/KeyProtection.
// Optional.
func UserSCEPInstallKeyProtection(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/KeyProtection"
}

// UserSCEPInstallRetryDelay is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/RetryDelay.
// Optional.
func UserSCEPInstallRetryDelay(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/RetryDelay"
}

// UserSCEPInstallRetryCount is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/RetryCount.
// Optional.
func UserSCEPInstallRetryCount(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/RetryCount"
}

// UserSCEPInstallTemplateName is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/TemplateName.
// Optional.
func UserSCEPInstallTemplateName(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/TemplateName"
}

// UserSCEPInstallKeyLength is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/KeyLength.
// Required for enrollment.
func UserSCEPInstallKeyLength(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/KeyLength"
}

// UserSCEPInstallHashAlgorithm is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/HashAlgorithm.
// Required for enrollment.
func UserSCEPInstallHashAlgorithm(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/HashAlgorithm"
}

// UserSCEPInstallCAThumbprint is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/CAThumbprint.
// Required.
func UserSCEPInstallCAThumbprint(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/CAThumbprint"
}

// UserSCEPInstallSubjectAlternativeNames is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/SubjectAlternativeNames.
// Optional.
func UserSCEPInstallSubjectAlternativeNames(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/SubjectAlternativeNames"
}

// UserSCEPInstallValidPeriod is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ValidPeriod.
// Optional.
func UserSCEPInstallValidPeriod(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ValidPeriod"
}

// UserSCEPInstallValidPeriodUnits is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ValidPeriodUnits.
// Optional.
func UserSCEPInstallValidPeriodUnits(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ValidPeriodUnits"
}

// UserSCEPInstallContainerName is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/ContainerName.
// Optional.
func UserSCEPInstallContainerName(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/ContainerName"
}

// UserSCEPInstallCustomTextToShowInPrompt is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/CustomTextToShowInPrompt.
// Optional.
func UserSCEPInstallCustomTextToShowInPrompt(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/CustomTextToShowInPrompt"
}

// UserSCEPInstallEnroll is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/Enroll.
// Required.
func UserSCEPInstallEnroll(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/Enroll"
}

// UserSCEPInstallAADKeyIdentifierList is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Install/AADKeyIdentifierList.
// Optional.
func UserSCEPInstallAADKeyIdentifierList(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Install/AADKeyIdentifierList"
}

// UserSCEPCertThumbprint is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/CertThumbprint.
// Optional.
func UserSCEPCertThumbprint(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/CertThumbprint"
}

// UserSCEPStatus is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/Status.
// Required.
func UserSCEPStatus(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/Status"
}

// UserSCEPErrorCode is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/ErrorCode.
// Optional.
func UserSCEPErrorCode(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/ErrorCode"
}

// UserSCEPRespondentServerUrl is ./User/Vendor/MSFT/ClientCertificateInstall/SCEP/{UniqueID}/RespondentServerUrl.
// Required.
func UserSCEPRespondentServerUrl(uniqueID string) string {
	return "./User/Vendor/MSFT/ClientCertificateInstall/SCEP/" + escape(uniqueID) + "/RespondentServerUrl"
}

// escape encodes one dynamic segment for a LocURI.
func escape(s string) string { return url.PathEscape(s) }
