// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package printerprovisioning

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the User root ./User/Vendor/MSFT/PrinterProvisioning.
var Tree = csp.Inherit(&csp.Tree{Name: "PrinterProvisioning", File: "PrinterProvisioning.xml", Scope: "User", PolicyArea: false, Root: &csp.Node{
	Name: "PrinterProvisioning", URI: "./User/Vendor/MSFT/PrinterProvisioning", Format: "node",
	Access:           []csp.Access{"Get"},
	Description:      "Printer Provisioning",
	Occurrence:       "One",
	Permanent:        true,
	OwnApplicability: true,
	Applicability:    &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19044.1806", "10.0.19043.1806", "10.0.19042.1806"}, CspVersion: "1.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x62", "0x63", "0x64", "0x65", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
	Children: []*csp.Node{
		&csp.Node{
			Name: "UPPrinterInstalls", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls", Format: "node",
			Access:      []csp.Access{"Get"},
			Description: "This setting will take the action on the specified user account to install or uninstall the specified printer. Install action is selected by default.",
			Occurrence:  "One",
			Permanent:   true,
			Children: []*csp.Node{
				&csp.Node{
					Name: "", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls/{PrinterSharedID}", Format: "node",
					Title:       "PrinterSharedID",
					Access:      []csp.Access{"Add", "Delete", "Get"},
					Description: "Identifies the Universal Print printer, by its Share ID, you wish to install on the targeted user account. The printer's Share ID can be found in the printer's properties via the Universal Print portal. Note: the targeted user account must have access rights to both the printer and to the Universal Print service.",
					Occurrence:  "OneOrMore",
					Dynamic:     true,
					Naming:      csp.Naming{Kind: "UniqueName", Pattern: "PrinterSharedID from the Universal Print system, which is used to discover and install Univeral Print printer"},
					Children: []*csp.Node{
						&csp.Node{
							Name: "CloudDeviceID", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls/{PrinterSharedID}/CloudDeviceID", Format: "chr",
							Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
							Description:   "Identifies the Universal Print printer, by its Printer ID, you wish to install on the targeted user account. The printer's Printer ID can be found in the printer's properties via the Universal Print portal. Note: the targeted user account must have access rights to both the printer and to the Universal Print service.",
							Occurrence:    "One",
							AllowedValues: &csp.AllowedValues{Type: "None", Value: "", Enum: nil, ADMX: nil, ListDelimiter: ""},
						},
						&csp.Node{
							Name: "Install", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls/{PrinterSharedID}/Install", Format: "null",
							Access:      []csp.Access{"Exec", "Get"},
							Description: "Support async execute. Install Universal Print printer.",
							Occurrence:  "One",
						},
						&csp.Node{
							Name: "Status", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls/{PrinterSharedID}/Status", Format: "int",
							Access:      []csp.Access{"Get"},
							Description: "1 finished installation successfully, 2 installation in progress after receiving execute cmd,  4 installation failed, 8 installation initial status, 32 unknown (not used).",
							Occurrence:  "One",
						},
						&csp.Node{
							Name: "ErrorCode", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls/{PrinterSharedID}/ErrorCode", Format: "int",
							Access:      []csp.Access{"Get"},
							Description: "HRESULT of the last installation returned code.",
							Occurrence:  "One",
						},
						&csp.Node{
							Name: "PrinterSharedName", URI: "./User/Vendor/MSFT/PrinterProvisioning/UPPrinterInstalls/{PrinterSharedID}/PrinterSharedName", Format: "chr",
							Access:        []csp.Access{"Add", "Delete", "Get", "Replace"},
							Description:   "Identifies the Universal Print printer, by its Share Name, you wish to install on the targeted user account. The printer's Share Name can be found in the printer's properties via the Universal Print portal. Note: the targeted user account must have access rights to both the printer and to the Universal Print service.",
							Occurrence:    "One",
							AllowedValues: &csp.AllowedValues{Type: "None", Value: "", Enum: nil, ADMX: nil, ListDelimiter: ""},
						},
					},
				},
			},
		},
	},
}})

// Trees lists every root of PrinterProvisioning in this package.
var Trees = []*csp.Tree{Tree}
