// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxactivexinstallservice

// Root is the Device root of ADMX_ActiveXInstallService.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_ActiveXInstallService"

// AxISURLZonePolicies is ./Device/Vendor/MSFT/Policy/Config/ADMX_ActiveXInstallService/AxISURLZonePolicies.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_ActiveXInstallService/AxISURLZonePolicies
const AxISURLZonePolicies = "./Device/Vendor/MSFT/Policy/Config/ADMX_ActiveXInstallService/AxISURLZonePolicies"
