// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package deviceguard

// EnableVirtualizationBasedSecurity values (ENUM).
const (
	// disable virtualization based security.
	EnableVirtualizationBasedSecurityDisableVirtualizationBasedSecurity = "0"
	// enable virtualization based security.
	EnableVirtualizationBasedSecurityEnableVirtualizationBasedSecurity = "1"
)

// RequirePlatformSecurityFeatures values (ENUM).
const (
	// Turns on VBS with Secure Boot.
	RequirePlatformSecurityFeaturesTurnsOnVBSWith = "1"
	// Turns on VBS with Secure Boot and direct memory access (DMA). DMA requires hardware support.
	RequirePlatformSecurityFeaturesTurnsOnVBSWith2 = "3"
)

// RequireMicrosoftSignedBootChain values (ENUM).
const (
	// Require Microsoft Signed Boot Chain.
	RequireMicrosoftSignedBootChainRequireMicrosoftSignedBoot = "1"
)

// LsaCfgFlags values (ENUM).
const (
	// (Disabled) Turns off Credential Guard remotely if configured previously without UEFI Lock.
	LsaCfgFlagsDisabledTurnsOffCredential = "0"
	// (Enabled with UEFI lock) Turns on Credential Guard with UEFI lock.
	LsaCfgFlagsEnabledWithUEFILock = "1"
	// (Enabled without lock) Turns on Credential Guard without UEFI lock.
	LsaCfgFlagsEnabledWithoutLockTurns = "2"
)

// MachineIdentityIsolation values (ENUM).
const (
	// (Disabled) Machine password is only LSASS-bound and stored in $MACHINE.ACC registry key.
	MachineIdentityIsolationDisabledMachinePasswordIs = "0"
	// (Enabled in audit mode) Machine password both LSASS-bound and IUM-bound. It is stored in $MACHINE.ACC and $MACHINE.ACC.IUM registry keys.
	MachineIdentityIsolationEnabledInAuditMode = "1"
	// (Enabled in enforcement mode) Machine password is only IUM-bound and stored in $MACHINE.ACC.IUM registry key.
	MachineIdentityIsolationEnabledInEnforcementMode = "2"
)

// ConfigureSystemGuardLaunch values (ENUM).
const (
	// Unmanaged Configurable by Administrative user
	ConfigureSystemGuardLaunchUnmanagedConfigurableByAdministrative = "0"
	// Unmanaged Enables Secure Launch if supported by hardware
	ConfigureSystemGuardLaunchUnmanagedEnablesSecureLaunch = "1"
	// Unmanaged Disables Secure Launch
	ConfigureSystemGuardLaunchUnmanagedDisablesSecureLaunch = "2"
)
