// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package userrights

// Root is the Device root of UserRights.
const Root = "./Device/Vendor/MSFT/Policy/Config/UserRights"

// AccessCredentialManagerAsTrustedCaller is ./Device/Vendor/MSFT/Policy/Config/UserRights/AccessCredentialManagerAsTrustedCaller.
// This user right is used by Credential Manager during Backup/Restore.
const AccessCredentialManagerAsTrustedCaller = "./Device/Vendor/MSFT/Policy/Config/UserRights/AccessCredentialManagerAsTrustedCaller"

// AccessFromNetwork is ./Device/Vendor/MSFT/Policy/Config/UserRights/AccessFromNetwork.
// This user right determines which users and groups are allowed to connect to the computer over the network.
const AccessFromNetwork = "./Device/Vendor/MSFT/Policy/Config/UserRights/AccessFromNetwork"

// ActAsPartOfTheOperatingSystem is ./Device/Vendor/MSFT/Policy/Config/UserRights/ActAsPartOfTheOperatingSystem.
// This user right allows a process to impersonate any user without authentication.
const ActAsPartOfTheOperatingSystem = "./Device/Vendor/MSFT/Policy/Config/UserRights/ActAsPartOfTheOperatingSystem"

// AllowLocalLogOn is ./Device/Vendor/MSFT/Policy/Config/UserRights/AllowLocalLogOn.
// This user right determines which users can log on to the computer.
const AllowLocalLogOn = "./Device/Vendor/MSFT/Policy/Config/UserRights/AllowLocalLogOn"

// BackupFilesAndDirectories is ./Device/Vendor/MSFT/Policy/Config/UserRights/BackupFilesAndDirectories.
// This user right determines which users can bypass file, directory, registry, and other persistent objects permissions when backing up files and directories.Specifically, this user right is similar to ...
const BackupFilesAndDirectories = "./Device/Vendor/MSFT/Policy/Config/UserRights/BackupFilesAndDirectories"

// ChangeSystemTime is ./Device/Vendor/MSFT/Policy/Config/UserRights/ChangeSystemTime.
// This user right determines which users and groups can change the time and date on the internal clock of the computer.
const ChangeSystemTime = "./Device/Vendor/MSFT/Policy/Config/UserRights/ChangeSystemTime"

// CreatePageFile is ./Device/Vendor/MSFT/Policy/Config/UserRights/CreatePageFile.
// This user right determines which users and groups can call an internal application programming interface (API) to create and change the size of a page file.
const CreatePageFile = "./Device/Vendor/MSFT/Policy/Config/UserRights/CreatePageFile"

// CreateToken is ./Device/Vendor/MSFT/Policy/Config/UserRights/CreateToken.
// This user right determines which accounts can be used by processes to create a token that can then be used to get access to any local resources when the process uses an internal application programmin...
const CreateToken = "./Device/Vendor/MSFT/Policy/Config/UserRights/CreateToken"

// CreateGlobalObjects is ./Device/Vendor/MSFT/Policy/Config/UserRights/CreateGlobalObjects.
// This security setting determines whether users can create global objects that are available to all sessions.
const CreateGlobalObjects = "./Device/Vendor/MSFT/Policy/Config/UserRights/CreateGlobalObjects"

// CreatePermanentSharedObjects is ./Device/Vendor/MSFT/Policy/Config/UserRights/CreatePermanentSharedObjects.
// This user right determines which accounts can be used by processes to create a directory object using the object manager.
const CreatePermanentSharedObjects = "./Device/Vendor/MSFT/Policy/Config/UserRights/CreatePermanentSharedObjects"

// CreateSymbolicLinks is ./Device/Vendor/MSFT/Policy/Config/UserRights/CreateSymbolicLinks.
// This user right determines if the user can create a symbolic link from the computer he is logged on to.
const CreateSymbolicLinks = "./Device/Vendor/MSFT/Policy/Config/UserRights/CreateSymbolicLinks"

// DebugPrograms is ./Device/Vendor/MSFT/Policy/Config/UserRights/DebugPrograms.
// This user right determines which users can attach a debugger to any process or to the kernel.
const DebugPrograms = "./Device/Vendor/MSFT/Policy/Config/UserRights/DebugPrograms"

// DenyAccessFromNetwork is ./Device/Vendor/MSFT/Policy/Config/UserRights/DenyAccessFromNetwork.
// This user right determines which users are prevented from accessing a computer over the network.
const DenyAccessFromNetwork = "./Device/Vendor/MSFT/Policy/Config/UserRights/DenyAccessFromNetwork"

// DenyLocalLogOn is ./Device/Vendor/MSFT/Policy/Config/UserRights/DenyLocalLogOn.
// This security setting determines which service accounts are prevented from registering a process as a service.
const DenyLocalLogOn = "./Device/Vendor/MSFT/Policy/Config/UserRights/DenyLocalLogOn"

// DenyRemoteDesktopServicesLogOn is ./Device/Vendor/MSFT/Policy/Config/UserRights/DenyRemoteDesktopServicesLogOn.
// This user right determines which users and groups are prohibited from logging on as a Remote Desktop Services client.
const DenyRemoteDesktopServicesLogOn = "./Device/Vendor/MSFT/Policy/Config/UserRights/DenyRemoteDesktopServicesLogOn"

// EnableDelegation is ./Device/Vendor/MSFT/Policy/Config/UserRights/EnableDelegation.
// This user right determines which users can set the Trusted for Delegation setting on a user or computer object.
const EnableDelegation = "./Device/Vendor/MSFT/Policy/Config/UserRights/EnableDelegation"

// RemoteShutdown is ./Device/Vendor/MSFT/Policy/Config/UserRights/RemoteShutdown.
// This user right determines which users are allowed to shut down a computer from a remote location on the network.
const RemoteShutdown = "./Device/Vendor/MSFT/Policy/Config/UserRights/RemoteShutdown"

// GenerateSecurityAudits is ./Device/Vendor/MSFT/Policy/Config/UserRights/GenerateSecurityAudits.
// This user right determines which accounts can be used by a process to add entries to the security log.
const GenerateSecurityAudits = "./Device/Vendor/MSFT/Policy/Config/UserRights/GenerateSecurityAudits"

// ImpersonateClient is ./Device/Vendor/MSFT/Policy/Config/UserRights/ImpersonateClient.
// Assigning this user right to a user allows programs running on behalf of that user to impersonate a client.
const ImpersonateClient = "./Device/Vendor/MSFT/Policy/Config/UserRights/ImpersonateClient"

// IncreaseSchedulingPriority is ./Device/Vendor/MSFT/Policy/Config/UserRights/IncreaseSchedulingPriority.
// This user right determines which accounts can use a process with Write Property access to another process to increase the execution priority assigned to the other process.
const IncreaseSchedulingPriority = "./Device/Vendor/MSFT/Policy/Config/UserRights/IncreaseSchedulingPriority"

// LoadUnloadDeviceDrivers is ./Device/Vendor/MSFT/Policy/Config/UserRights/LoadUnloadDeviceDrivers.
// This user right determines which users can dynamically load and unload device drivers or other code in to kernel mode.
const LoadUnloadDeviceDrivers = "./Device/Vendor/MSFT/Policy/Config/UserRights/LoadUnloadDeviceDrivers"

// LockMemory is ./Device/Vendor/MSFT/Policy/Config/UserRights/LockMemory.
// This user right determines which accounts can use a process to keep data in physical memory, which prevents the system from paging the data to virtual memory on disk.
const LockMemory = "./Device/Vendor/MSFT/Policy/Config/UserRights/LockMemory"

// ManageAuditingAndSecurityLog is ./Device/Vendor/MSFT/Policy/Config/UserRights/ManageAuditingAndSecurityLog.
// This user right determines which users can specify object access auditing options for individual resources, such as files, Active Directory objects, and registry keys.
const ManageAuditingAndSecurityLog = "./Device/Vendor/MSFT/Policy/Config/UserRights/ManageAuditingAndSecurityLog"

// ModifyObjectLabel is ./Device/Vendor/MSFT/Policy/Config/UserRights/ModifyObjectLabel.
// This user right determines which user accounts can modify the integrity label of objects, such as files, registry keys, or processes owned by other users.
const ModifyObjectLabel = "./Device/Vendor/MSFT/Policy/Config/UserRights/ModifyObjectLabel"

// ModifyFirmwareEnvironment is ./Device/Vendor/MSFT/Policy/Config/UserRights/ModifyFirmwareEnvironment.
// This user right determines who can modify firmware environment values.
const ModifyFirmwareEnvironment = "./Device/Vendor/MSFT/Policy/Config/UserRights/ModifyFirmwareEnvironment"

// ManageVolume is ./Device/Vendor/MSFT/Policy/Config/UserRights/ManageVolume.
// This user right determines which users and groups can run maintenance tasks on a volume, such as remote defragmentation.
const ManageVolume = "./Device/Vendor/MSFT/Policy/Config/UserRights/ManageVolume"

// ProfileSingleProcess is ./Device/Vendor/MSFT/Policy/Config/UserRights/ProfileSingleProcess.
// This user right determines which users can use performance monitoring tools to monitor the performance of system processes.
const ProfileSingleProcess = "./Device/Vendor/MSFT/Policy/Config/UserRights/ProfileSingleProcess"

// RestoreFilesAndDirectories is ./Device/Vendor/MSFT/Policy/Config/UserRights/RestoreFilesAndDirectories.
// This user right determines which users can bypass file, directory, registry, and other persistent objects permissions when restoring backed up files and directories, and determines which users can set...
const RestoreFilesAndDirectories = "./Device/Vendor/MSFT/Policy/Config/UserRights/RestoreFilesAndDirectories"

// TakeOwnership is ./Device/Vendor/MSFT/Policy/Config/UserRights/TakeOwnership.
// This user right determines which users can take ownership of any securable object in the system, including Active Directory objects, files and folders, printers, registry keys, processes, and threads.
const TakeOwnership = "./Device/Vendor/MSFT/Policy/Config/UserRights/TakeOwnership"

// BypassTraverseChecking is ./Device/Vendor/MSFT/Policy/Config/UserRights/BypassTraverseChecking.
// This user right determines which users can traverse directory trees even though the user may not have permissions on the traversed directory.
const BypassTraverseChecking = "./Device/Vendor/MSFT/Policy/Config/UserRights/BypassTraverseChecking"

// ReplaceProcessLevelToken is ./Device/Vendor/MSFT/Policy/Config/UserRights/ReplaceProcessLevelToken.
// This security setting determines which user accounts can call the CreateProcessAsUser() application programming interface (API) so that one service can start another.
const ReplaceProcessLevelToken = "./Device/Vendor/MSFT/Policy/Config/UserRights/ReplaceProcessLevelToken"

// ChangeTimeZone is ./Device/Vendor/MSFT/Policy/Config/UserRights/ChangeTimeZone.
// This user right determines which users and groups can change the time zone used by the computer for displaying the local time, which is the computer's system time plus the time zone offset.
const ChangeTimeZone = "./Device/Vendor/MSFT/Policy/Config/UserRights/ChangeTimeZone"

// ShutDownTheSystem is ./Device/Vendor/MSFT/Policy/Config/UserRights/ShutDownTheSystem.
// This security setting determines which users who are logged on locally to the computer can shut down the operating system using the Shut Down command.
const ShutDownTheSystem = "./Device/Vendor/MSFT/Policy/Config/UserRights/ShutDownTheSystem"

// LogOnAsBatchJob is ./Device/Vendor/MSFT/Policy/Config/UserRights/LogOnAsBatchJob.
// This security setting allows a user to be logged on by means of a batch-queue facility and is provided only for compatibility with older versions of Windows.
const LogOnAsBatchJob = "./Device/Vendor/MSFT/Policy/Config/UserRights/LogOnAsBatchJob"

// ProfileSystemPerformance is ./Device/Vendor/MSFT/Policy/Config/UserRights/ProfileSystemPerformance.
// This security setting determines which users can use performance monitoring tools to monitor the performance of system processes.
const ProfileSystemPerformance = "./Device/Vendor/MSFT/Policy/Config/UserRights/ProfileSystemPerformance"

// DenyLogOnAsBatchJob is ./Device/Vendor/MSFT/Policy/Config/UserRights/DenyLogOnAsBatchJob.
// This security setting determines which accounts are prevented from being able to log on as a batch job.
const DenyLogOnAsBatchJob = "./Device/Vendor/MSFT/Policy/Config/UserRights/DenyLogOnAsBatchJob"

// LogOnAsService is ./Device/Vendor/MSFT/Policy/Config/UserRights/LogOnAsService.
// This security setting allows a security principal to log on as a service.
const LogOnAsService = "./Device/Vendor/MSFT/Policy/Config/UserRights/LogOnAsService"

// IncreaseProcessWorkingSet is ./Device/Vendor/MSFT/Policy/Config/UserRights/IncreaseProcessWorkingSet.
// Increase a process working set.
const IncreaseProcessWorkingSet = "./Device/Vendor/MSFT/Policy/Config/UserRights/IncreaseProcessWorkingSet"

// DenyLogOnAsService is ./Device/Vendor/MSFT/Policy/Config/UserRights/DenyLogOnAsService.
// Deny log on as a service -This security setting determines which service accounts are prevented from registering a process as a service.
const DenyLogOnAsService = "./Device/Vendor/MSFT/Policy/Config/UserRights/DenyLogOnAsService"

// AdjustMemoryQuotasForProcess is ./Device/Vendor/MSFT/Policy/Config/UserRights/AdjustMemoryQuotasForProcess.
// Adjust memory quotas for a process - This privilege determines who can change the maximum memory that can be consumed by a process.
const AdjustMemoryQuotasForProcess = "./Device/Vendor/MSFT/Policy/Config/UserRights/AdjustMemoryQuotasForProcess"

// AllowLogOnThroughRemoteDesktop is ./Device/Vendor/MSFT/Policy/Config/UserRights/AllowLogOnThroughRemoteDesktop.
// Allow log on through Remote Desktop Services - This policy setting determines which users or groups can access the sign-in screen of a remote device through a Remote Desktop Services connection.
const AllowLogOnThroughRemoteDesktop = "./Device/Vendor/MSFT/Policy/Config/UserRights/AllowLogOnThroughRemoteDesktop"
