// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package games

// Root is the Device root of Games.
const Root = "./Device/Vendor/MSFT/Policy/Config/Games"

// AllowAdvancedGamingServices is ./Device/Vendor/MSFT/Policy/Config/Games/AllowAdvancedGamingServices.
// Specifies whether advanced gaming services can be used.
const AllowAdvancedGamingServices = "./Device/Vendor/MSFT/Policy/Config/Games/AllowAdvancedGamingServices"

// DisableGamingFullScreenExperience is ./Device/Vendor/MSFT/Policy/Config/Games/DisableGamingFullScreenExperience.
// Specifies whether the gaming full screen experience can be used.
const DisableGamingFullScreenExperience = "./Device/Vendor/MSFT/Policy/Config/Games/DisableGamingFullScreenExperience"
