// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package camera

// AllowCamera values (ENUM).
const (
	// Not allowed.
	AllowCameraNotAllowed = "0"
	// Allowed.
	AllowCameraAllowed = "1"
)
