// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxenhancedstorage

// Root is the Device root of ADMX_EnhancedStorage.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage"

// RootHubConnectedEnStorDevices is ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/RootHubConnectedEnStorDevices.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/RootHubConnectedEnStorDevices
const RootHubConnectedEnStorDevices = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/RootHubConnectedEnStorDevices"

// ApprovedEnStorDevices is ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/ApprovedEnStorDevices.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/ApprovedEnStorDevices
const ApprovedEnStorDevices = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/ApprovedEnStorDevices"

// ApprovedSilos is ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/ApprovedSilos.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/ApprovedSilos
const ApprovedSilos = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/ApprovedSilos"

// DisallowLegacyDiskDevices is ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/DisallowLegacyDiskDevices.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/DisallowLegacyDiskDevices
const DisallowLegacyDiskDevices = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/DisallowLegacyDiskDevices"

// DisablePasswordAuthentication is ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/DisablePasswordAuthentication.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/DisablePasswordAuthentication
const DisablePasswordAuthentication = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/DisablePasswordAuthentication"

// LockDeviceOnMachineLock is ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/LockDeviceOnMachineLock.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/LockDeviceOnMachineLock
const LockDeviceOnMachineLock = "./Device/Vendor/MSFT/Policy/Config/ADMX_EnhancedStorage/LockDeviceOnMachineLock"
