// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package windowslogon

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/WindowsLogon.
var Tree = csp.Inherit(&csp.Tree{Name: "WindowsLogon", File: "WindowsLogon_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "WindowsLogon", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "DontDisplayNetworkSelectionUI", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/DontDisplayNetworkSelectionUI", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "Logon~AT~System~Logon", Name: "DontDisplayNetworkSelectionUI", File: "logon.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "DisableLockScreenAppNotifications", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/DisableLockScreenAppNotifications", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "Logon~AT~System~Logon", Name: "DisableLockScreenAppNotifications", File: "logon.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "EnumerateLocalUsersOnDomainJoinedComputers", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/EnumerateLocalUsersOnDomainJoinedComputers", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.17134"}, CspVersion: "7.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "Logon~AT~System~Logon", Name: "EnumerateLocalUsers", File: "logon.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AllowAutomaticRestartSignOn", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/AllowAutomaticRestartSignOn", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.18362"}, CspVersion: "9.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x62", "0x63", "0x64", "0x65", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "WinLogon~AT~WindowsComponents~Logon", Name: "AutomaticRestartSignOn", File: "WinLogon.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "ConfigAutomaticRestartSignOn", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/ConfigAutomaticRestartSignOn", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.18362"}, CspVersion: "9.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x62", "0x63", "0x64", "0x65", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "WinLogon~AT~WindowsComponents~Logon", Name: "ConfigAutomaticRestartSignOn", File: "WinLogon.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "HideFastUserSwitching", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/HideFastUserSwitching", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy setting allows you to hide the Switch User interface in the Logon UI, the Start menu and the Task Manager. If you enable this policy setting, the Switch User interface is hidden from the user who is attempting to log on or is logged on to the computer that has this policy applied. The locations that Switch User interface appear are in the Logon UI, the Start menu and the Task Manager. If you disable or do not configure this policy setting, the Switch User interface is accessible to the user in the three locations.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Disabled (visible)."}, {Value: "1", Description: "Enabled (hidden)."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "HideFastUserSwitching", AreaPath: "Logon~AT~System~Logon", Element: ""},
			ConflictResolution: "HighestValueMostSecure",
		},
		&csp.Node{
			Name: "EnableFirstLogonAnimation", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/EnableFirstLogonAnimation", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "This policy setting allows you to control whether users see the first sign-in animation when signing in to the computer for the first time.  This applies to both the first user of the computer who completes the initial setup and users who are added to the computer later.  It also controls if Microsoft account users will be offered the opt-in prompt for services during their first sign-in.  If you enable this policy setting, Microsoft account users will see the opt-in prompt for services, and users with other accounts will see the sign-in animation.  If you disable this policy setting, users will not see the animation and Microsoft account users will not see the opt-in prompt for services.  If you do not configure this policy setting, the user who completes the initial Windows setup will see the animation during their first sign-in. If the first user had already completed the initial setup and this policy setting is not configured, users new to this computer will not see the animation.  Note: The first sign-in animation will not be shown on Server, so this policy will have no effect.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.18362"}, CspVersion: "9.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Disabled."}, {Value: "1", Description: "Enabled."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "EnableFirstLogonAnimation", AreaPath: "Logon~AT~System~Logon", Element: ""},
			ConflictResolution: "HighestValueMostSecure",
		},
		&csp.Node{
			Name: "EnableMPRNotifications", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/EnableMPRNotifications", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22621"}, CspVersion: "11.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "WinLogon~AT~WindowsComponents~Logon", Name: "EnableMPRNotifications", File: "WinLogon.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "OverrideShellProgram", URI: "./Device/Vendor/MSFT/Policy/Config/WindowsLogon/OverrideShellProgram", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "OverrideShellProgram policy allows IT admin to configure the shell program for Windows OS on a device. This policy has the highest precedence over other ways of configuring the shell program. The policy currently supports below options: 1. Not Configured: Default shell will be launched. 2. Apply Lightweight Shell: Lightweight shell does not have a user interface and helps the device to achieve better performance as the shell consumes limited resources over default shell. Lightweight shell contains a limited set of features which could be consumed by applications. This configuration can be useful if the device needs to have a continuous running user interface application which would consume features offered by Lightweight shell. If you disable or do not configure this policy setting, then the default shell will be launched.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22621.2338"}, CspVersion: "11.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Not Configured"}, {Value: "1", Description: "Apply Lightweight shell"}}, ADMX: nil, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of WindowsLogon in this package.
var Trees = []*csp.Tree{Tree}
