// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package dmacc

import "net/url"

// Root is the Legacy root of DMAcc.
const Root = "./SyncML/DMAcc"

// AccountUID is ./SyncML/DMAcc/{AccountUID}.
// This interior node acts as a placeholder for zero or more OMA DM server accounts.
func AccountUID(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID)
}

// AppID is ./SyncML/DMAcc/{AccountUID}/AppID.
// Specifies the application identifier for the OMA DM account..
func AppID(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppID"
}

// ServerID is ./SyncML/DMAcc/{AccountUID}/ServerID.
// Specifies the OMA DM server's unique identifier for the current OMA DM account.
func ServerID(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/ServerID"
}

// Name is ./SyncML/DMAcc/{AccountUID}/Name.
// Specifies the display name of the application.
func Name(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Name"
}

// PrefConRef is ./SyncML/DMAcc/{AccountUID}/PrefConRef.
// The only supported values include the NAPID of a bootstrapped NAP management object or a connection GUID used by connection manager.
func PrefConRef(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/PrefConRef"
}

// AppAddr is ./SyncML/DMAcc/{AccountUID}/AppAddr.
// Interior node for DM server address.
func AppAddr(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr"
}

// AppAddrObjectName is ./SyncML/DMAcc/{AccountUID}/AppAddr/{ObjectName}.
// Defines the OMA DM server address.
func AppAddrObjectName(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr/" + escape(objectName)
}

// AppAddrAddr is ./SyncML/DMAcc/{AccountUID}/AppAddr/{ObjectName}/Addr.
// Specifies the address of the OMA DM account.
func AppAddrAddr(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr/" + escape(objectName) + "/Addr"
}

// AppAddrAddrType is ./SyncML/DMAcc/{AccountUID}/AppAddr/{ObjectName}/AddrType.
// Specifies the format and interpretation of the Addr node value.
func AppAddrAddrType(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr/" + escape(objectName) + "/AddrType"
}

// AppAddrPort is ./SyncML/DMAcc/{AccountUID}/AppAddr/{ObjectName}/Port.
// Interior node for port information.
func AppAddrPort(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr/" + escape(objectName) + "/Port"
}

// AppAddrPortObjectName is ./SyncML/DMAcc/{AccountUID}/AppAddr/{ObjectName}/Port/{ObjectName}.
// Only one port number can be configured.
func AppAddrPortObjectName(accountUID string, objectName string, objectName2 string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr/" + escape(objectName) + "/Port/" + escape(objectName2)
}

// AppAddrPortPortNbr is ./SyncML/DMAcc/{AccountUID}/AppAddr/{ObjectName}/Port/{ObjectName}/PortNbr.
// Specifies the port number of the OMA MD account address.
func AppAddrPortPortNbr(accountUID string, objectName string, objectName2 string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAddr/" + escape(objectName) + "/Port/" + escape(objectName2) + "/PortNbr"
}

// AAuthPref is ./SyncML/DMAcc/{AccountUID}/AAuthPref.
// Specifies the application authentication preference.
func AAuthPref(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AAuthPref"
}

// AppAuth is ./SyncML/DMAcc/{AccountUID}/AppAuth.
// Defines authentication settings.
func AppAuth(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth"
}

// AppAuthObjectName is ./SyncML/DMAcc/{AccountUID}/AppAuth/{ObjectName}.
// Defines one set of authentication settings.
func AppAuthObjectName(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth/" + escape(objectName)
}

// AppAuthAAuthLevel is ./SyncML/DMAcc/{AccountUID}/AppAuth/{ObjectName}/AAuthLevel.
// Specifies the application authentication level.
func AppAuthAAuthLevel(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth/" + escape(objectName) + "/AAuthLevel"
}

// AppAuthAAuthType is ./SyncML/DMAcc/{AccountUID}/AppAuth/{ObjectName}/AAuthType.
// Specifies the authentication type.
func AppAuthAAuthType(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth/" + escape(objectName) + "/AAuthType"
}

// AppAuthAAuthName is ./SyncML/DMAcc/{AccountUID}/AppAuth/{ObjectName}/AAuthName.
// Specifies the authentication name.
func AppAuthAAuthName(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth/" + escape(objectName) + "/AAuthName"
}

// AppAuthAAuthSecret is ./SyncML/DMAcc/{AccountUID}/AppAuth/{ObjectName}/AAuthSecret.
// Specifies the password or secret used for authentication.
func AppAuthAAuthSecret(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth/" + escape(objectName) + "/AAuthSecret"
}

// AppAuthAAuthData is ./SyncML/DMAcc/{AccountUID}/AppAuth/{ObjectName}/AAuthData.
// Specifies the next nonce used for authentication.
func AppAuthAAuthData(accountUID string, objectName string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/AppAuth/" + escape(objectName) + "/AAuthData"
}

// Ext is ./SyncML/DMAcc/{AccountUID}/Ext.
// Defines a set of extended parameters.
func Ext(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext"
}

// ExtMicrosoft is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft.
// Defines a set of Microsoft-specific extended parameters.
func ExtMicrosoft(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft"
}

// ExtMicrosoftRole is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/Role.
// If this node is unspecified, its default value is the access role of the session that created the server account.
func ExtMicrosoftRole(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/Role"
}

// ExtMicrosoftProtoVer is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/ProtoVer.
// This node value corresponds to what the client would put in the VerDTD element of an OMA-DM package.
func ExtMicrosoftProtoVer(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/ProtoVer"
}

// ExtMicrosoftDefaultEncoding is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/DefaultEncoding.
// This node specifies the encoding that the OMA-DM client will use to encode its first package.
func ExtMicrosoftDefaultEncoding(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/DefaultEncoding"
}

// ExtMicrosoftUseHwDevID is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/UseHwDevID.
// A value of true indicates that, during an OMA-DM session with this server, the value of the ./DevInfo/DevId node is the hardware ID of device (e.g, IMEI for a GSM device, ESN for a CDMA Device, hashed...
func ExtMicrosoftUseHwDevID(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/UseHwDevID"
}

// ExtMicrosoftConnRetryFreq is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/ConnRetryFreq.
// This node specifies how many times DM client will retry a connection to the server if the connection fails.
func ExtMicrosoftConnRetryFreq(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/ConnRetryFreq"
}

// ExtMicrosoftInitialBackOffTime is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/InitialBackOffTime.
// This node specifies the initial amount of time (in milliseconds) that the DM client waits before attempting a connection retry.
func ExtMicrosoftInitialBackOffTime(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/InitialBackOffTime"
}

// ExtMicrosoftMaxBackOffTime is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/MaxBackOffTime.
// This node specifies the maximum number of milliseconds to wait before attempting a connection retry.
func ExtMicrosoftMaxBackOffTime(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/MaxBackOffTime"
}

// ExtMicrosoftBackCompatRetryDisabled is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/BackCompatRetryDisabled.
// This node specifies whether to disable the ability of the DM client to communicate with a down-level server.
func ExtMicrosoftBackCompatRetryDisabled(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/BackCompatRetryDisabled"
}

// ExtMicrosoftUseNonceResync is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/UseNonceResync.
// This node specifies whether the DM client can use the nonce resynchronization protocol when authentication of a server notification fails.
func ExtMicrosoftUseNonceResync(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/UseNonceResync"
}

// ExtMicrosoftCRLCheck is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/CRLCheck.
// Allows connection to the DM server to check the Certificate Revocation List (CRL).
func ExtMicrosoftCRLCheck(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/CRLCheck"
}

// ExtMicrosoftDisableOnRoaming is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/DisableOnRoaming.
// Determines whether the OMA DM client should be launched when roaming.
func ExtMicrosoftDisableOnRoaming(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/DisableOnRoaming"
}

// ExtMicrosoftSSLCLIENTCERTSEARCHCRITERIA is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/SSLCLIENTCERTSEARCHCRITERIA.
// The SSLCLIENTCERTSEARCHCRITERIA parameter is used to specify the client certificate search criteria.
func ExtMicrosoftSSLCLIENTCERTSEARCHCRITERIA(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/SSLCLIENTCERTSEARCHCRITERIA"
}

// ExtMicrosoftInitiateSession is ./SyncML/DMAcc/{AccountUID}/Ext/Microsoft/InitiateSession.
// When this node is added, a session is started with the MDM server.
func ExtMicrosoftInitiateSession(accountUID string) string {
	return "./SyncML/DMAcc/" + escape(accountUID) + "/Ext/Microsoft/InitiateSession"
}

// escape encodes one dynamic segment for a LocURI.
func escape(s string) string { return url.PathEscape(s) }
