// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxcpls

// Root is the Device root of ADMX_Cpls.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_Cpls"

// UseDefaultTile is ./Device/Vendor/MSFT/Policy/Config/ADMX_Cpls/UseDefaultTile.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_Cpls/UseDefaultTile
const UseDefaultTile = "./Device/Vendor/MSFT/Policy/Config/ADMX_Cpls/UseDefaultTile"
