// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxappxruntime

// DeviceRoot is the Device root of ADMX_AppXRuntime.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime"

// DeviceAppxRuntimeBlockFileElevation is ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation
const DeviceAppxRuntimeBlockFileElevation = "./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation"

// DeviceAppxRuntimeBlockProtocolElevation is ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation
const DeviceAppxRuntimeBlockProtocolElevation = "./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation"

// DeviceAppxRuntimeBlockHostedAppAccessWinRT is ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT
const DeviceAppxRuntimeBlockHostedAppAccessWinRT = "./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockHostedAppAccessWinRT"

// DeviceAppxRuntimeApplicationContentUriRules is ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules
const DeviceAppxRuntimeApplicationContentUriRules = "./Device/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeApplicationContentUriRules"

// UserRoot is the User root of ADMX_AppXRuntime.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime"

// UserAppxRuntimeBlockFileElevation is ./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation.
// ./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation
const UserAppxRuntimeBlockFileElevation = "./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockFileElevation"

// UserAppxRuntimeBlockProtocolElevation is ./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation.
// ./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation
const UserAppxRuntimeBlockProtocolElevation = "./User/Vendor/MSFT/Policy/Config/ADMX_AppXRuntime/AppxRuntimeBlockProtocolElevation"
