// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxmmc

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the User root ./User/Vendor/MSFT/Policy/Config/ADMX_MMC.
var Tree = csp.Inherit(&csp.Tree{Name: "ADMX_MMC", File: "ADMX_MMC_AreaDDF.xml", Scope: "User", PolicyArea: true, Root: &csp.Node{
	Name: "ADMX_MMC", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_MMC", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "MMC_Restrict_Author", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_MMC/MMC_Restrict_Author", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "MMC~AT~WindowsComponents~MMC", Name: "MMC_Restrict_Author", File: "MMC.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "MMC_Restrict_To_Permitted_Snapins", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_MMC/MMC_Restrict_To_Permitted_Snapins", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "MMC~AT~WindowsComponents~MMC", Name: "MMC_Restrict_To_Permitted_Snapins", File: "MMC.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "MMC_ActiveXControl", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_MMC/MMC_ActiveXControl", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "MMC~AT~WindowsComponents~MMC~MMC_RESTRICT", Name: "MMC_ActiveXControl", File: "MMC.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "MMC_ExtendView", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_MMC/MMC_ExtendView", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "MMC~AT~WindowsComponents~MMC~MMC_RESTRICT~MMC_ExtensionSnapins", Name: "MMC_ExtendView", File: "MMC.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "MMC_LinkToWeb", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_MMC/MMC_LinkToWeb", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "MMC~AT~WindowsComponents~MMC~MMC_RESTRICT", Name: "MMC_LinkToWeb", File: "MMC.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of ADMX_MMC in this package.
var Trees = []*csp.Tree{Tree}
