// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package desktopappinstaller

// Root is the Device root of DesktopAppInstaller.
const Root = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller"

// EnableAppInstaller is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAppInstaller.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAppInstaller
const EnableAppInstaller = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAppInstaller"

// EnableSettings is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableSettings.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableSettings
const EnableSettings = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableSettings"

// EnableExperimentalFeatures is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableExperimentalFeatures.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableExperimentalFeatures
const EnableExperimentalFeatures = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableExperimentalFeatures"

// EnableLocalManifestFiles is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableLocalManifestFiles.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableLocalManifestFiles
const EnableLocalManifestFiles = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableLocalManifestFiles"

// EnableBypassCertificatePinningForMicrosoftStore is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableBypassCertificatePinningForMicrosoftStore.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableBypassCertificatePinningForMicrosoftStore
const EnableBypassCertificatePinningForMicrosoftStore = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableBypassCertificatePinningForMicrosoftStore"

// EnableHashOverride is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableHashOverride.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableHashOverride
const EnableHashOverride = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableHashOverride"

// EnableLocalArchiveMalwareScanOverride is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableLocalArchiveMalwareScanOverride.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableLocalArchiveMalwareScanOverride
const EnableLocalArchiveMalwareScanOverride = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableLocalArchiveMalwareScanOverride"

// EnableDefaultSource is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableDefaultSource.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableDefaultSource
const EnableDefaultSource = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableDefaultSource"

// EnableMicrosoftStoreSource is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableMicrosoftStoreSource.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableMicrosoftStoreSource
const EnableMicrosoftStoreSource = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableMicrosoftStoreSource"

// SourceAutoUpdateInterval is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/SourceAutoUpdateInterval.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/SourceAutoUpdateInterval
const SourceAutoUpdateInterval = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/SourceAutoUpdateInterval"

// EnableAdditionalSources is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAdditionalSources.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAdditionalSources
const EnableAdditionalSources = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAdditionalSources"

// EnableAllowedSources is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAllowedSources.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAllowedSources
const EnableAllowedSources = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableAllowedSources"

// EnableMSAppInstallerProtocol is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableMSAppInstallerProtocol.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableMSAppInstallerProtocol
const EnableMSAppInstallerProtocol = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableMSAppInstallerProtocol"

// EnableWindowsPackageManagerCommandLineInterfaces is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableWindowsPackageManagerCommandLineInterfaces.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableWindowsPackageManagerCommandLineInterfaces
const EnableWindowsPackageManagerCommandLineInterfaces = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableWindowsPackageManagerCommandLineInterfaces"

// EnableWindowsPackageManagerConfiguration is ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableWindowsPackageManagerConfiguration.
// ./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableWindowsPackageManagerConfiguration
const EnableWindowsPackageManagerConfiguration = "./Device/Vendor/MSFT/Policy/Config/DesktopAppInstaller/EnableWindowsPackageManagerConfiguration"
