// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxeventlogging

// Root is the Device root of ADMX_EventLogging.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_EventLogging"

// EnableProtectedEventLogging is ./Device/Vendor/MSFT/Policy/Config/ADMX_EventLogging/EnableProtectedEventLogging.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_EventLogging/EnableProtectedEventLogging
const EnableProtectedEventLogging = "./Device/Vendor/MSFT/Policy/Config/ADMX_EventLogging/EnableProtectedEventLogging"
