// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package smartscreen

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// Tree is the Device root ./Device/Vendor/MSFT/Policy/Config/SmartScreen.
var Tree = csp.Inherit(&csp.Tree{Name: "SmartScreen", File: "SmartScreen_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "SmartScreen", URI: "./Device/Vendor/MSFT/Policy/Config/SmartScreen", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "EnableSmartScreenInShell", URI: "./Device/Vendor/MSFT/Policy/Config/SmartScreen/EnableSmartScreenInShell", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Allows IT Admins to configure SmartScreen for Windows.",
			Default:            "1",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF", "0xD2"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Disabled."}, {Value: "1", Description: "Enabled."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "ShellConfigureSmartScreen", AreaPath: "SmartScreen~AT~WindowsComponents~SmartScreen~Shell", Element: ""},
			ConflictResolution: "HighestValueMostSecure",
		},
		&csp.Node{
			Name: "PreventOverrideForFilesInShell", URI: "./Device/Vendor/MSFT/Policy/Config/SmartScreen/PreventOverrideForFilesInShell", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Allows IT Admins to control whether users can ignore SmartScreen warnings and run malicious files.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF", "0xD2"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Do not prevent override."}, {Value: "1", Description: "Prevent override."}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "ShellConfigureSmartScreen", AreaPath: "SmartScreen~AT~WindowsComponents~SmartScreen~Shell", Element: "ShellConfigureSmartScreen_Dropdown"},
			ConflictResolution: "HighestValueMostSecure",
		},
		&csp.Node{
			Name: "EnableAppInstallControl", URI: "./Device/Vendor/MSFT/Policy/Config/SmartScreen/EnableAppInstallControl", Format: "int",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Description:        "Allows IT Admins to control whether users are allowed to install apps from places other than the Store. NoteThis policy will block installation only while the device is online. To block offline installation too, SmartScreen/PreventOverrideForFilesInShell and SmartScreen/EnableSmartScreenInShell policies should also be enabled. This policy setting is intended to prevent malicious content from affecting your user's devices when downloading executable content from the internet.",
			Default:            "0",
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.15063"}, CspVersion: "5.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF", "0xD2"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ENUM", Value: "", Enum: []csp.EnumValue{{Value: "0", Description: "Turns off Application Installation Control, allowing users to download and install files from anywhere on the web."}, {Value: "1", Description: "Turns on Application Installation Control, allowing users to only install apps from the Store."}, {Value: "2", Description: "Turns on Application Installation Control, letting users know that there's a comparable app in the Store"}, {Value: "3", Description: "Turns on Application Installation Control, warning users before installing apps from outside the Store"}}, ADMX: nil, ListDelimiter: ""},
			GpMapping:          &csp.GpMapping{EnglishName: "ConfigureAppInstallControl", AreaPath: "SmartScreen~AT~WindowsComponents~SmartScreen~Shell", Element: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of SmartScreen in this package.
var Trees = []*csp.Tree{Tree}
