// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package devicehealthmonitoring

// Root is the Device root of DeviceHealthMonitoring.
const Root = "./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring"

// AllowDeviceHealthMonitoring is ./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/AllowDeviceHealthMonitoring.
// Enable/disable 4Nines device health monitoring on devices.
const AllowDeviceHealthMonitoring = "./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/AllowDeviceHealthMonitoring"

// ConfigDeviceHealthMonitoringScope is ./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/ConfigDeviceHealthMonitoringScope.
// If the device is not opted-in to the DeviceHealthMonitoring service via the AllowDeviceHealthMonitoring then this policy has no meaning.
const ConfigDeviceHealthMonitoringScope = "./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/ConfigDeviceHealthMonitoringScope"

// ConfigDeviceHealthMonitoringUploadDestination is ./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/ConfigDeviceHealthMonitoringUploadDestination.
// If the device is not opted-in to the DeviceHealthMonitoring service via the AllowDeviceHealthMonitoring then this policy has no meaning.
const ConfigDeviceHealthMonitoringUploadDestination = "./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/ConfigDeviceHealthMonitoringUploadDestination"

// ConfigDeviceHealthMonitoringServiceInstance is ./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/ConfigDeviceHealthMonitoringServiceInstance.
// If the device is not opted-in to the DeviceHealthMonitoring service via the AllowDeviceHealthMonitoring then this policy has no meaning.
const ConfigDeviceHealthMonitoringServiceInstance = "./Device/Vendor/MSFT/Policy/Config/DeviceHealthMonitoring/ConfigDeviceHealthMonitoringServiceInstance"
