// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxsecuritycenter

// Root is the Device root of ADMX_Securitycenter.
const Root = "./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter"

// SecurityCenterSecurityCenterInDomain is ./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain
const SecurityCenterSecurityCenterInDomain = "./Device/Vendor/MSFT/Policy/Config/ADMX_Securitycenter/SecurityCenter_SecurityCenterInDomain"
