// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxeaime

// Root is the User root of ADMX_EAIME.
const Root = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME"

// LDoNotIncludeNonPublishingStandardGlyphInTheCandidateList is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_DoNotIncludeNonPublishingStandardGlyphInTheCandidateList.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_DoNotIncludeNonPublishingStandardGlyphInTheCandidateList
const LDoNotIncludeNonPublishingStandardGlyphInTheCandidateList = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_DoNotIncludeNonPublishingStandardGlyphInTheCandidateList"

// LRestrictCharacterCodeRangeOfConversion is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_RestrictCharacterCodeRangeOfConversion.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_RestrictCharacterCodeRangeOfConversion
const LRestrictCharacterCodeRangeOfConversion = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_RestrictCharacterCodeRangeOfConversion"

// LTurnOffCustomDictionary is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffCustomDictionary.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffCustomDictionary
const LTurnOffCustomDictionary = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffCustomDictionary"

// LTurnOffHistorybasedPredictiveInput is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffHistorybasedPredictiveInput.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffHistorybasedPredictiveInput
const LTurnOffHistorybasedPredictiveInput = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffHistorybasedPredictiveInput"

// LTurnOffInternetSearchIntegration is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffInternetSearchIntegration.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffInternetSearchIntegration
const LTurnOffInternetSearchIntegration = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffInternetSearchIntegration"

// LTurnOffOpenExtendedDictionary is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffOpenExtendedDictionary.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffOpenExtendedDictionary
const LTurnOffOpenExtendedDictionary = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffOpenExtendedDictionary"

// LTurnOffSavingAutoTuningDataToFile is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffSavingAutoTuningDataToFile.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffSavingAutoTuningDataToFile
const LTurnOffSavingAutoTuningDataToFile = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOffSavingAutoTuningDataToFile"

// LTurnOnCloudCandidate is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnCloudCandidate.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnCloudCandidate
const LTurnOnCloudCandidate = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnCloudCandidate"

// LTurnOnCloudCandidateCHS is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnCloudCandidateCHS.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnCloudCandidateCHS
const LTurnOnCloudCandidateCHS = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnCloudCandidateCHS"

// LTurnOnLexiconUpdate is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnLexiconUpdate.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnLexiconUpdate
const LTurnOnLexiconUpdate = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnLexiconUpdate"

// LTurnOnLiveStickers is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnLiveStickers.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnLiveStickers
const LTurnOnLiveStickers = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnLiveStickers"

// LTurnOnMisconversionLoggingForMisconversionReport is ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnMisconversionLoggingForMisconversionReport.
// ./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnMisconversionLoggingForMisconversionReport
const LTurnOnMisconversionLoggingForMisconversionReport = "./User/Vendor/MSFT/Policy/Config/ADMX_EAIME/L_TurnOnMisconversionLoggingForMisconversionReport"
