// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package virtualizationbasedtechnology

// Root is the Device root of VirtualizationBasedTechnology.
const Root = "./Device/Vendor/MSFT/Policy/Config/VirtualizationBasedTechnology"

// HypervisorEnforcedCodeIntegrity is ./Device/Vendor/MSFT/Policy/Config/VirtualizationBasedTechnology/HypervisorEnforcedCodeIntegrity.
// Hypervisor-Protected Code Integrity: 0 - Turns off Hypervisor-Protected Code Integrity remotely if configured previously without UEFI Lock, 1 - Turns on Hypervisor-Protected Code Integrity with UEFI l...
const HypervisorEnforcedCodeIntegrity = "./Device/Vendor/MSFT/Policy/Config/VirtualizationBasedTechnology/HypervisorEnforcedCodeIntegrity"

// RequireUEFIMemoryAttributesTable is ./Device/Vendor/MSFT/Policy/Config/VirtualizationBasedTechnology/RequireUEFIMemoryAttributesTable.
// Require UEFI Memory Attributes Table
const RequireUEFIMemoryAttributesTable = "./Device/Vendor/MSFT/Policy/Config/VirtualizationBasedTechnology/RequireUEFIMemoryAttributesTable"
