// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package virtualizationbasedtechnology

// HypervisorEnforcedCodeIntegrity values (ENUM).
const (
	// (Disabled) Turns off Hypervisor-Protected Code Integrity remotely if configured previously without UEFI Lock.
	HypervisorEnforcedCodeIntegrityDisabledTurnsOffHypervisor = "0"
	// (Enabled with UEFI lock) Turns on Hypervisor-Protected Code Integrity with UEFI lock.
	HypervisorEnforcedCodeIntegrityEnabledWithUEFILock = "1"
	// (Enabled without lock) Turns on Hypervisor-Protected Code Integrity without UEFI lock.
	HypervisorEnforcedCodeIntegrityEnabledWithoutLockTurns = "2"
)

// RequireUEFIMemoryAttributesTable values (ENUM).
const (
	// Do not require UEFI Memory Attributes Table
	RequireUEFIMemoryAttributesTableDoNotRequireUEFI = "0"
	// Require UEFI Memory Attributes Table
	RequireUEFIMemoryAttributesTableRequireUEFIMemoryAttributes = "1"
)
