// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package clouddesktop

// BootToCloudMode values (ENUM).
const (
	// Not Configured
	BootToCloudModeNotConfigured = "0"
	// Enable Boot to Cloud Desktop
	BootToCloudModeEnableBootToCloud = "1"
)

// SetMaxConnectionTimeout values (ENUM).
const (
	// 5 min
	SetMaxConnectionTimeoutN5Min = "5"
	// 6 min
	SetMaxConnectionTimeoutN6Min = "6"
	// 7 min
	SetMaxConnectionTimeoutN7Min = "7"
	// 8 min
	SetMaxConnectionTimeoutN8Min = "8"
	// 9 min
	SetMaxConnectionTimeoutN9Min = "9"
	// 10 min
	SetMaxConnectionTimeoutN10Min = "10"
	// 11 min
	SetMaxConnectionTimeoutN11Min = "11"
	// 12 min
	SetMaxConnectionTimeoutN12Min = "12"
	// 13 min
	SetMaxConnectionTimeoutN13Min = "13"
	// 14 min
	SetMaxConnectionTimeoutN14Min = "14"
	// 15 min
	SetMaxConnectionTimeoutN15Min = "15"
	// 16 min
	SetMaxConnectionTimeoutN16Min = "16"
	// 17 min
	SetMaxConnectionTimeoutN17Min = "17"
	// 18 min
	SetMaxConnectionTimeoutN18Min = "18"
	// 19 min
	SetMaxConnectionTimeoutN19Min = "19"
	// 20 min
	SetMaxConnectionTimeoutN20Min = "20"
)
