// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package localusersandgroups

// Root is the Device root of LocalUsersAndGroups.
const Root = "./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups"

// Configure is ./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure.
// This Setting allows an administrator to manage local groups on a Device.
const Configure = "./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure"
