// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package bitlocker

// Root is the Device root of Bitlocker.
const Root = "./Device/Vendor/MSFT/Policy/Config/Bitlocker"

// EncryptionMethod is ./Device/Vendor/MSFT/Policy/Config/Bitlocker/EncryptionMethod.
// This policy specifies the BitLocker Drive Encryption method and cipher strength.
const EncryptionMethod = "./Device/Vendor/MSFT/Policy/Config/Bitlocker/EncryptionMethod"
