// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package taskscheduler

// EnableXboxGameSaveTask values (ENUM).
const (
	// Disabled
	EnableXboxGameSaveTaskDisabled = "0"
	// Enabled
	EnableXboxGameSaveTaskEnabled = "1"
)
