// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxpentraining

// DeviceRoot is the Device root of ADMX_PenTraining.
const DeviceRoot = "./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining"

// DevicePenTrainingOff2 is ./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2.
// ./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2
const DevicePenTrainingOff2 = "./Device/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_2"

// UserRoot is the User root of ADMX_PenTraining.
const UserRoot = "./User/Vendor/MSFT/Policy/Config/ADMX_PenTraining"

// UserPenTrainingOff1 is ./User/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_1.
// ./User/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_1
const UserPenTrainingOff1 = "./User/Vendor/MSFT/Policy/Config/ADMX_PenTraining/PenTrainingOff_1"
