// Code generated by ddfgen; DO NOT EDIT.
// Source: DDFv2Feb2026.zip (sha256 bf667d895af4)

package admxappcompat

import "github.com/deploymenttheory/go-microsoft-dm/schema/csp"

// DeviceTree is the Device root ./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat.
var DeviceTree = csp.Inherit(&csp.Tree{Name: "ADMX_AppCompat", File: "ADMX_AppCompat_AreaDDF.xml", Scope: "Device", PolicyArea: true, Root: &csp.Node{
	Name: "ADMX_AppCompat", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AppCompatPrevent16BitMach", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatPrevent16BitMach", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatPrevent16BitMach", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatRemoveProgramCompatPropPage", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatRemoveProgramCompatPropPage", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatRemoveProgramCompatPropPage", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatTurnOffEngine", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffEngine", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffEngine", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatTurnOffApplicationImpactTelemetry", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffApplicationImpactTelemetry", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffApplicationImpactTelemetry", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatTurnOffProgramInventory", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffProgramInventory", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffProgramInventory", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatTurnOffProgramCompatibilityAssistant_2", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffProgramCompatibilityAssistant_2", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffProgramCompatibilityAssistant_2", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatTurnOffUserActionRecord", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffUserActionRecord", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffUserActionRecord", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
		&csp.Node{
			Name: "AppCompatTurnOffSwitchBack", URI: "./Device/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffSwitchBack", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffSwitchBack", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// UserTree is the User root ./User/Vendor/MSFT/Policy/Config/ADMX_AppCompat.
var UserTree = csp.Inherit(&csp.Tree{Name: "ADMX_AppCompat", File: "ADMX_AppCompat_AreaDDF.xml", Scope: "User", PolicyArea: true, Root: &csp.Node{
	Name: "ADMX_AppCompat", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_AppCompat", Format: "node",
	Access:     []csp.Access{"Get"},
	Occurrence: "One",
	Permanent:  true,
	MIME:       "com.microsoft/11/MDM/Policy",
	Children: []*csp.Node{
		&csp.Node{
			Name: "AppCompatTurnOffProgramCompatibilityAssistant_1", URI: "./User/Vendor/MSFT/Policy/Config/ADMX_AppCompat/AppCompatTurnOffProgramCompatibilityAssistant_1", Format: "chr",
			Access:             []csp.Access{"Add", "Delete", "Get", "Replace"},
			Occurrence:         "ZeroOrOne",
			MIME:               "text/plain",
			OwnApplicability:   true,
			Applicability:      &csp.Applicability{OsBuildVersions: []string{"10.0.22000", "10.0.19043.1202", "10.0.19042.1202", "10.0.19041.1202"}, CspVersion: "10.0", EditionAllowList: []string{"0x4", "0x1B", "0x30", "0x31", "0x48", "0x54", "0x79", "0x7A", "0x7D", "0x7E", "0x81", "0x82", "0x88", "0x8A", "0x8B", "0xA1", "0xA2", "0xA4", "0xA5", "0xAB", "0xAC", "0xAF", "0xBC", "0xBF", "0xCA", "0xCB", "0xCD", "0xCF"}, RequiresAzureAd: false},
			AllowedValues:      &csp.AllowedValues{Type: "ADMX", Value: "", Enum: nil, ADMX: &csp.ADMX{Area: "AppCompat~AT~WindowsComponents~AppCompat", Name: "AppCompatTurnOffProgramCompatibilityAssistant_1", File: "AppCompat.admx"}, ListDelimiter: ""},
			ConflictResolution: "LastWrite",
		},
	},
}})

// Trees lists every root of ADMX_AppCompat in this package.
var Trees = []*csp.Tree{DeviceTree, UserTree}
